### ISSUE TITLE
Please support Vargargs

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#105]
Please take a look at:
http://java.sun.com/j2se/1.5.0/docs/guide/language/varargs.html

So this code is going to work with java but not in beanshell.

```java
public class foo {
    public static void bar(String... a){
        print(a.length);
    }
}
```

// Error: Parser Error: Parse error at line 5, column 32.  Encountered: .
bsh % // Error: Parser Error: Parse error at line 1, column 3.  Encountered: \)
bsh % // Error: EvalError: Class or variable not found: a.length : at Line: 2 : in file: &lt;unknown file&gt; : a .length

bsh % // Error: Parser Error: Parse error at line 4, column 1.  Encountered: \}

This is a feature from java itself many people are waiting for, please support this in beanshell too.

Thanks
Chris

Reported by: somefreestring

Original Ticket: "beanshell/feature-requests/16":https://sourceforge.net/p/beanshell/feature-requests/16

**Comment by nickl-** [comment]
Varargs implemented on 3.0.0-SNAPSHOT.841

```java
bsh % public class foo {
    public static void bar(String... a){
        print(a.length);
    }
}
--> $1 = class foo :Class
bsh % foo.bar(new String[] {"1","2","3"});
3I :int
--> void
```

Closed works as expected.
