### ISSUE TITLE
Remote enhancements

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#107]
Various patches for bsh.Remote:
\- allow trailing / on bsh: URLs \(as per docs\)
\- detect EOF when using bsh: protocol \(looks for :EOF, 
which can be supplied by the script\)
\- close files after processing BSH script

Reported by: *anonymous

Original Ticket: "beanshell/patches/1":https://sourceforge.net/p/beanshell/patches/1

**Comment by nickl-** [comment]
Added attachment from sourceforge

**Comment by nickl-** [comment]
Closed: Superseded by #108
