### ISSUE TITLE
Allow access to exit return code

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#109]
It would be useful sometimes to have access to the exec() return code.

Here is my amended version of the exec() code:

int // NEW
```java
exec( String arg ) {
    this.proc = Runtime.getRuntime().exec(arg);
    this.din = new DataInputStream(proc.getInputStream() );
    while( (line=din.readLine()) != null )
        print(line);
    return this.proc.exitValue(); // NEW
}
```

Reported by: *anonymous

Original Ticket: "beanshell/patches/3":https://sourceforge.net/p/beanshell/patches/3

**Comment by nickl-** [comment]
This is handy but perhaps early access to [the documentation for Process](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/lang/Process.html)  itself is more useful.
 
As also mentioned in #273 and as per the above documentation page we should change to ProcessBuilder

> As of 1.5, [ProcessBuilder.start()](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/lang/ProcessBuilder.html#start()) is the preferred way to create a Process.

Yet keep backwards compatibility...

**Comment by nickl-** [comment]
Replaced by #683
