### ISSUE TITLE
beanshell-2.0b5 cannot be built for target 1.2

### ISSUE THREAD

**Issue by t-arn** [beanshell/beanshell#11]
I tried to make a BeanShell build for Java 1.2 by doing the following:
In 2.0b5 build.xml line 49, I uncommented
         

and then, I added target="1.2" to the "compile" target, but I got the errors
listed below:

compile:
     [javac] Compiling 153 source files to
v:\!Daten\DEV\Java\beanshell-2.0b5\src\classes
     [javac]
     [javac]           WARNING
     [javac]
     [javac] The -source switch defaults to 1.5 in JDK 1.5 and 1.6.
     [javac] If you specify -target 1.2 you now must also specify -source
1.2.
     [javac] Ant will implicitly add -source 1.2 for you.  Please change your
build file.
     [javac]
v:\!Daten\DEV\Java\beanshell-2.0b5\src\engine\src\TestBshScriptEngine.java:4:
static import declarations are not supported in -source 1.2
     [javac] (use -source 5 or higher to enable static import declarations)
     [javac] import static javax.script.ScriptContext.*;
     [javac]        ^
     [javac]
v:\!Daten\DEV\Java\beanshell-2.0b5\src\engine\src\TestBshScriptEngine.java:19:
warning: as of release 1.4, 'assert' is a keyword, and may not be used as an
identifier
     [javac] (use -source 1.4 or higher to use 'assert' as a keyword)
     [javac]             assert( i == 4 );
     [javac]             ^
     [javac]
v:\!Daten\DEV\Java\beanshell-2.0b5\src\engine\src\bsh\engine\BshScriptEngine.java:7:
static import declarations are not supported in -source 1.2
     [javac] (use -source 5 or higher to enable static import declarations)
     [javac] import static javax.script.ScriptContext.*;
     [javac]        ^
     [javac]
v:\!Daten\DEV\Java\beanshell-2.0b5\src\engine\src\bsh\engine\BshScriptEngine.java:201:
variable-arity methods are not supported in -source 1.2
     [javac] (use -source 5 or higher to enable variable-arity methods)
     [javac]     public Object invokeMethod( Object thiz, String name,
Object... args )
     [javac]
^
     [javac]
v:\!Daten\DEV\Java\beanshell-2.0b5\src\engine\src\bsh\engine\BshScriptEngine.java:267:
generics are not supported in -source 1.2
     [javac] (use -source 5 or higher to enable generics)
     [javac]     public <T> T getInterface( Class<T> clasz )
     [javac]            ^
     [javac]
v:\!Daten\DEV\Java\beanshell-2.0b5\src\engine\src\bsh\engine\BshScriptEngineFactory.java:12:
generics are not supported in -source 1.2
     [javac] (use -source 5 or higher to enable generics)
     [javac]     final List<String> extensions = Arrays.asList( "bsh", "java"
);
     [javac]               ^
     [javac]
v:\!Daten\DEV\Java\beanshell-2.0b5\src\engine\src\bsh\engine\BshScriptEngineFactory.java:68:
variable-arity methods are not supported in -source 1.2
     [javac] (use -source 5 or higher to enable variable-arity methods)
     [javac]             String objectName, String methodName, String ...
args )
     [javac]                                                          ^
     [javac]
v:\!Daten\DEV\Java\beanshell-2.0b5\src\engine\src\bsh\engine\ScriptContextEngineView.java:5:
static import declarations are not supported in -source 1.2
     [javac] (use -source 5 or higher to enable static import declarations)
     [javac] import static javax.script.ScriptContext.*;
     [javac]        ^
     [javac]
v:\!Daten\DEV\Java\beanshell-2.0b5\src\engine\src\bsh\engine\ScriptContextEngineView.java:21:
generics are not supported in -source 1.2
     [javac] (use -source 5 or higher to enable generics)
     [javac] public class ScriptContextEngineView implements
Map<String,Object>
     [javac]                                                    ^
     [javac]
v:\!Daten\DEV\Java\beanshell-2.0b5\src\engine\src\bsh\engine\ScriptContextEngineView.java:252:
for-each loops are not supported in -source 1.2
     [javac] (use -source 5 or higher to enable for-each loops)
     [javac]             for ( int i : scopes ) {
     [javac]                         ^
     [javac] 9 errors
     [javac] 1 warning
--

**Comment by stain** [comment]
I must admit I don't know how to make the build work for 1.2. I think you need to build with an actual JDK 1.2 - which would not support the `-source` and `-target` parameters - I believe they were added in 1.5.

As we did #3 we moved to a Maven build, and those optional 1.2 build tricks probably don't work anymore, I'm afraid I'll close this issue for later versions - but feel free to discuss here how to get the 2.0b5/2.0b6 versions building on JDK 1.2.

**Comment by t-arn** [comment]
I don't think you need a JDK 1.2 for this. You just need to add source="1.2" and target="1.2" (you need both or you'll get an Ant warning).
I'm currently trying to make this work. It seems that we'll need to exclude the javax.script stuff as well.
I'll post the necessary changes here, should I succeed in making it work.

**Comment by stain** [comment]
Thanks - feel free to make a branch - we can call it 2.0b6-jdk12 or
something.

On 22 February 2016 at 06:45, Tom <notifications@github.com> wrote:

> I don't think you need a JDK 1.2 for this. You just need to add
> source="1.2" and target="1.2" (you need both or you'll get an Ant warning).
> I'm currently trying to make this work. It seems that we'll need to
> exclude the javax.script stuff as well.
> I'll post the necessary changes here, should I succeed in making it work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beanshell/beanshell/issues/11#issuecomment-187038316>.
>



-- 
Stian Soiland-Reyes
Apache Taverna (incubating), Apache Commons RDF (incubating)
http://orcid.org/0000-0001-9842-9718
