### ISSUE TITLE
Patch for javap.bsh script

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#112]
The javap.bsh script has a bug where if you try to do a
javap on a class that is named "Class" other than
java.lang.Class.

Reported by: *anonymous

Original Ticket: "beanshell/patches/6":https://sourceforge.net/p/beanshell/patches/6

**Comment by jimjag** [comment]
Code still does not use java.class.Class but no bugs have been reported with this usage. Closing this.
