### ISSUE TITLE
Fix For bsh.Reflect.findAccessibleMethod For Proxies

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#116]
The following code should be added to the beginning of
the method in order to unproxy the proxies as their
first implemented interface. This fixes issues where
the proxy is actually from beanshell having created a
proxy for an anonymous class.

```java
// We will have to "unproxy" all of the proxies here because the
// java reflection mechanism will not find methods if we provide
// proxies as the types of the arguments of the method rather than
// the actual Class object.
Class[] unProxiedTypes = new Class[types.length];
for (int i=0; i<types.length; i++) {
    Class c = types[i];
    
    if (c != null && Proxy.isProxyClass(c)) {
        // We will unproxy as the first implemented interface.
        unProxiedTypes[i] = types[i].getInterfaces()[0];
    } else {
        unProxiedTypes[i] = types[i];
    }
}

types = unProxiedTypes;

```
Reported by: *anonymous

Original Ticket: "beanshell/patches/10":https://sourceforge.net/p/beanshell/patches/10

**Comment by nickl-** [comment]
Had this problem with #667 not being able to get to the generated classes namespace being obfuscated by the proxy.

However not sure where this patch is intended for?

Doesn't the proxy handler deal with method lookups?

I really have no idea where this code is supposed to go...

Closed: not enough information
