### ISSUE TITLE
XThis.getInterface() throws RunTimePermission fix

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#117]
/\*\*
Get dynamic proxy for interface, caching those 
it creates.
\*/
public Object getInterface\( Class \[\] ca \) 
\{
if \( interfaces == null \)
interfaces = new Hashtable\(\);

// Make a hash of the interface hashcodes in 
order to cache them
int hash = 21;
for\(int i=0; i&lt;ca.length; i++\)
hash \*= ca\[i\].hashCode\(\) + 3;
Object hashKey = new Integer\(hash\);

Object interf = interfaces.get\( hashKey \);

if \( interf == null \) 
\{
// FIXME: I RAN INTO A 
RunTimePermission PROBLEM HERE, WHEN THE INTERFACES 
HAVE
// BEEN LOADED THROUGH A DIFFERENT 
CLASSLOADER; THIS WAY, I USE THE CLASSLOADER
// THAT DID LOAD THE XThis CLASS, 
WHICH IS PROBABLY MORE CORRECT ANYWAY\(?\)
//ClassLoader classLoader = ca
\[0\].getClassLoader\(\); // ?
ClassLoader classLoader = this.getClass
\(\).getClassLoader\(\);
interf = Proxy.newProxyInstance\( 
classLoader, ca, 
invocationHandler \);
interfaces.put\( hashKey, interf \);
\}

return interf;
\}

Reported by: *anonymous

Original Ticket: "beanshell/patches/11":https://sourceforge.net/p/beanshell/patches/11

**Comment by jimjag** [comment]
This does not seem applicable nor viable anymore for BeanShell v3.
