### ISSUE TITLE
Performance optimization for Name.consumeNextObjectField()

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#118]
/\*
Keep adding parts until we have a class 
\*/
Class clas = null;
int i = 1;
String className = null;

// FIXME: OPTIMIZE THIS FOR PROGRAMMERS TAKING CARE OF 
JAVA NAMING CONVENTIONS
//			for\(; i &lt;= countParts
\(evalName\); i++\)
//			\{
//				className = prefix
\(evalName, i\);
//				if \( \(clas = 
namespace.getClass\(className\)\) \!= null \)
//					break;
//			\}
// first search for a classname that starts with an 
upper case character
int index = 0;
while \( index &lt; evalName.length\(\) \) \{
if \( Character.isUpperCase\(evalName.charAt
\(index\)\) \) \{
className = prefix\(evalName, i\);
if \( \(clas = namespace.getClass
\(className\)\) \!= null \)
break;
\}
if \( \(index = evalName.indexOf\('.' ,index+1\)\) 
&lt; 0 \) break;
++index;
++i;
\}
// if the search above didn't succeed, revert to non-
optimized behaviour
if \( clas == null \) \{
int numParts = countParts\(evalName\);
for\(i = 1; i &lt;= numParts; i++\) \{
className = prefix\(evalName, i\);
if \( \(clas = namespace.getClass
\(className\)\) \!= null \)
break;
\}
\}
// FIXME: END OF OPTIMIZATION

if \( clas \!= null \)  \{
return completeRound\(
className,
suffix\( evalName, countParts\(evalName\)-
i \),
new ClassIdentifier\(clas\) 
\);
\}

Reported by: *anonymous

Original Ticket: "beanshell/patches/12":https://sourceforge.net/p/beanshell/patches/12

**Comment by jimjag** [comment]
This does not seem applicable nor viable anymore for BeanShell v3.
