### ISSUE TITLE
Performance optimization for Reflect.hasObjectPropertySetter

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#121]
public static boolean hasObjectPropertySetter\(
Class clas, String propName \)
\{
String setterName = accessorName\("set", 
propName \);

// FIXME: SMALL OPTIMIZATION: TRY TO GET A 
GETTER METHOD FOR THIS PROPERTY AND DETERMINE 
// ITS RESULT TYPE; THIS SHOULD GIVE A VERY 
LIKELY SETTER METHOD ARGUMENT TYPE
try \{
String accessorName = accessorName
\( "get", propName \);
Method method = clas.getMethod\( 
accessorName, zeroLengthClassArray \);
Class argtype = method.getReturnType\(\);
Class\[\] args = \{ argtype \};
method = clas.getMethod\(setterName, 
args\);
return true;
\} catch \( Exception e \) \{\}
// FIXME: END OF OPTIMIZATION

Method \[\] methods = clas.getMethods\(\);

// we don't know the right hand side of the 
assignment yet.
// has at least one setter of the right name?
// FIXME: THIS DOESN'T APPEAR TO BE CORRECT, 
BECAUSE IT DOESN'T TRAVERSE SUPER CLASSES
for\(int i=0; i&lt;methods.length; i++\)
if \( methods\[i\].getName\(\).equals\( 
setterName \) \)
return true;
return false;
\}

Reported by: *anonymous

Original Ticket: "beanshell/patches/15":https://sourceforge.net/p/beanshell/patches/15

**Comment by jimjag** [comment]
This no longer seems applicable or viable for BeanShell v3
