### ISSUE TITLE
Swiss German keyboard doesn't work...

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#131]
When trying to use it I discovered that the Swiss\_German Keyboard of
my computer is not recognized. Using braces and other special symbols
is quite tedious right now.

Question: Am I doing something wrong or does beanshell have a problem
with Non US Keyboard layouts?

System:
NT4, Sun JDK 1.3

\------------

I'm afraid this is very difficult for me to test, not having a system like this...  Can anyone help?

I'm guessing this is a Java environment problem and probably not anything we can deal with directly...  so I'm giving this a low priority for now.

Thanks,
Pat

Reported by: patn

Original Ticket: "beanshell/bugs/10":https://sourceforge.net/p/beanshell/bugs/10

**Comment by nickl-** [comment]
Pat closed this issue in 2001, not sure why it migrated as open.
