### ISSUE TITLE
Console caret disappears on new win

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#133]
JDK 1.3, Win98SE. When I right-click the desktop and bring up a new window, the text insertion cursor \(caret\) disappears from the workspace window. When the newly opened window is a new workspace window, neither it nor the previous one show a caret. Switching to a different Windows app then back to Bsh restores the caret; switching between workspace windows makes it disappear again.

Bewildered,

Reported by: *anonymous

Original Ticket: "beanshell/bugs/12":https://sourceforge.net/p/beanshell/bugs/12

**Comment by opeongo** [comment]
Cannot reproduce this problem with current master for bsh-3.0.0-SNAPSHOT.jar using java version "11.0.1" 2018-10-16 LTS.  The caret appears correctly in the currently selected workspace window.

**Comment by nickl-** [comment]
@opeongo Tx for verifying

**Closed: Cannot reproduce**
