### ISSUE TITLE
Slowness in BeanShell

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#141]
ii=0;
for \( ; ii &amp;lt; 10000; ii++\)
\{
\}
print \(&amp;quot;after the loop:&amp;quot; + ii\);
This is quite a bit slower in BeanShell than in other programs.
Looking at the source code, I suspect that the problem is not
in the loop but in variable handling. Specifically the follwing:
private Object consumeNextObjectField\( Interpreter interpreter \)
throws EvalError
\{
/\*
Is it a class name?
If we're just starting eval of name \(and it wasn't a variable
reference per above\) try to make it, else fail.
Class names are attempted before long variable chains because
we don't have any way to &amp;quot;back out&amp;quot; if we start down a chain
and we're wrong.  In general this seems ok.
\*/
So each time ii is looked at BeanShell checks to see if it's a class or
a variable, and that takes time. 

Reported by: drormata

Original Ticket: "beanshell/bugs/20":https://sourceforge.net/p/beanshell/bugs/20

**Comment by opeongo** [comment]
It does not seem to be all that slow.  Iterating over an empty loop body 1,000,000 times takes less than a second on my rig.  Probably could close this issue as either being resolved of not being specific enough to deal with.

**Comment by nickl-** [comment]
Yes the performance on loops were fixed as per #504 

@opeongo Tx for resolving this issue.

**Closed: Fixed**
