### ISSUE TITLE
classpath reload failure

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#163]
when starting bsh with rt.jar in the classpath \(eg: 
java -classpath c:\java\jdk\jre\lib\rt.jar;bsh.jar 
bsh.Interpreter\), I cannot use internal functions like 
print\(\), source\(\), exit\(\)... after doing a 
reloadClasses\(\);

I always get a security exception.

If a remove rt.jar from the classpath, everything 
works perfectly.

here's the trace:

// Error: Unknown error: java.lang.SecurityException: 
Prohibited package name: java.lang
java.lang.SecurityException: 
Prohibited package name: java.lang
at java.lang.ClassLoader.defineClass
\(ClassLoader.java:477\)
at java.security.SecureClassLoader.defineClass
\(SecureClassLoader.java:111\)
at java.net.URLClassLoader.defineClass
\(URLClassLoader.java:248\)
at java.net.URLClassLoader.access$100
\(URLClassLoader.java:56\)
at java.net.URLClassLoader$1.run
\(URLClassLoader.java:195\)
at java.security.AccessController.doPrivileged
\(Native Method\)
at java.net.URLClassLoader.findClass
\(URLClassLoader.java:188\)
at bsh.classpath.BshClassLoader.findClass
\(BshClassLoader.java:140\)
at bsh.classpath.BshClassLoader.loadClass
\(BshClassLoader.java:90\)
at java.lang.ClassLoader.loadClass
\(ClassLoader.java:253\)
at bsh.BshClassManager.getClassForName
\(BshClassManager.java:147\)
at bsh.BshClassManager.classForName
\(BshClassManager.java:402\)
at bsh.NameSpace.classForName
\(NameSpace.java:479\)
at bsh.NameSpace.getClassImpl
\(NameSpace.java:449\)
at bsh.NameSpace.getClass\(NameSpace.java:390\)
at bsh.Name.toClass\(Name.java:304\)
at bsh.BSHAmbiguousName.toClass
\(BSHAmbiguousName.java:56\)
at bsh.BSHType.getType\(BSHType.java:70\)
at bsh.BSHBinaryExpression.eval
\(BSHBinaryExpression.java:65\)
at bsh.BSHIfStatement.evaluateCondition
\(BSHIfStatement.java:62\)
at bsh.BSHIfStatement.eval
\(BSHIfStatement.java:45\)
at bsh.BSHBlock.eval\(BSHBlock.java:49\)
at bsh.BshMethod.invokeDeclaredMethod
\(BshMethod.java:127\)
at bsh.Name.invokeLocalMethod\(Name.java:527\)
at bsh.Name.invokeMethod\(Name.java:439\)
at bsh.BSHMethodInvocation.eval
\(BSHMethodInvocation.java:48\)
at bsh.BSHPrimaryExpression.eval
\(BSHPrimaryExpression.java:67\)
at bsh.Interpreter.run\(Interpreter.java:334\)
at bsh.Interpreter.main\(Interpreter.java:290\)

Reported by: *anonymous

Original Ticket: "beanshell/bugs/42":https://sourceforge.net/p/beanshell/bugs/42

**Comment by opeongo** [comment]
This does not appear to be a bug.  rt.jar should be on the Xbootclasspath not on the classpath.  Should close this one.

**Comment by nickl-** [comment]
@opeongo Tx for verifying

**Closed: works as implemented**
