### ISSUE TITLE
No endorsed packages in class browser

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#168]
The class browser does not display overriding 
endorsed packages with J2SE 1.4b3. See 
http://java.sun.com/j2se/1.4/docs/guide/standards/inde
x.html

For example, if I place the latest Apache xerces, 
xalan, and jaxp-api jar files in the 
$JAVA\_HOME/jre/lib/endorsed directory, the class 
browser still reveals only the original org.apache.\* 
classes for crimson and xalan, archived in rt.jar , 
rather than the newer, overriding ones.

Reported by: dwette

Original Ticket: "beanshell/bugs/47":https://sourceforge.net/p/beanshell/bugs/47

**Comment by Sailsman63** [comment]
The Endorsed Packages mechanism was removed in java9. Should this just be closed as no longer relevant?

**Comment by nickl-** [comment]
Agree with @Sailsman63 , closed no relevance
