### ISSUE TITLE
Change groupId to org.beanshell ?

### ISSUE THREAD

**Issue by stain** [beanshell/beanshell#17]
#### Vote for your preference of group id.

[![](https://api.gh-polls.com/poll/01CM1MXDSMFEW6H6TPKG1EVSAJ/Go%20back%20to%20using%20beanshell.org)](https://api.gh-polls.com/poll/01CM1MXDSMFEW6H6TPKG1EVSAJ/Go%20back%20to%20using%20beanshell.org/vote)
[![](https://api.gh-polls.com/poll/01CM1MXDSMFEW6H6TPKG1EVSAJ/Stick%20with%20org.apache-extras.beanshell%20-%20and%20actively%20pursue%20incubation)](https://api.gh-polls.com/poll/01CM1MXDSMFEW6H6TPKG1EVSAJ/Stick%20with%20org.apache-extras.beanshell%20-%20and%20actively%20pursue%20incubation/vote)
[![](https://api.gh-polls.com/poll/01CM1MXDSMFEW6H6TPKG1EVSAJ/Stick%20with%20org.apache-extras.beanshell%20-%20but%20wait%20for%20apache.org%20to%20invite%20us)](https://api.gh-polls.com/poll/01CM1MXDSMFEW6H6TPKG1EVSAJ/Stick%20with%20org.apache-extras.beanshell%20-%20but%20wait%20for%20apache.org%20to%20invite%20us/vote)

Before moving to Apache Extras, Beanshell from beanshell.org was released with MAven Group Id [org.beanshell](http://central.maven.org/maven2/org/beanshell/) - including [2.0b4](http://central.maven.org/maven2/org/beanshell/bsh/2.0b4/) and [2.0b5](http://central.maven.org/maven2/org/beanshell/bsh/2.0b5/)

As the first Apache Extras release was the relicensed 2.0b5, we used instead groupId [org.apache-extras.beanshell](http://central.maven.org/maven2/org/apache-extras/beanshell/) - which remained the same for the fresh [2.0b6](http://central.maven.org/maven2/org/apache-extras/beanshell/bsh/2.0b6/).

Should we change the groupId back to `org.beanshell` to avoid confusion? I think we can only do this if we get some pointers to this GitHub repository from http://beanshell.org/ - e.g. from http://beanshell.org/download.html and http://beanshell.org/developer.html which point to older versions and a [dead SVN repository](http://ikayzo.org/svn/beanshell). 

(or perhaps make http://beanshell.github.io/ and change DNS to point http://beanshell.org there ?)

What is your view @patniemeyer  ..?

**Comment by ctrueden** [comment]
I have personally already observed people being confused by the groupId change, and I think `org.beanshell` as groupId would be much more intuitive for users.

Also, as a naive complete outsider, the `beanshell.github.io` route seems totally the way to go. 😄

**Comment by stain** [comment]
Thanks, @ctrueden - I'll talk to @patniemeyer - I think as a minimum http://beanshell.org/ should point to https://github.com/beanshell/beanshell/ before we do such a change.

**Comment by Ktar5** [comment]
I second this

**Comment by ebourg** [comment]
I think the old groupId should be preserved, otherwise some projects may pull both 2.0b4 and 2.0b6 through their transitive dependencies and there is no guarantee the more recent classes will be loaded first.

Who controls the beanshell.org domain? I think it's important to clarify the situation and explain that this project isn't a random fork but the official continuation of the old beanshell code. The domain is going to expire in 44 days, if it isn't renewed http://beanshell.github.io should be used to advertise the project.

**Comment by stain** [comment]
btw, the `beanshell.org` domain name does not expire yet, but in October (which is when it tends to be renewed)

> Registry Expiry Date: 2017-10-07T18:13:51Z

**Comment by nickl-** [comment]
@stain have we reached consensus on this?

Also where should we release to? Is the current pom configuration still valid? 

I believe there is a way to publish to GitHub with the [github/maven-plugins](/github/maven-plugins) which may be a solution to the group-id issue without updating beanshell.org as well.

**Comment by pgiffuni** [comment]
I updated the developer.html site to point to github. Is this enough?

**Comment by nickl-** [comment]
@pgiffuni can you provide a link please, I might have misunderstood before...

**Comment by nickl-** [comment]
On the topic of the group id, these are the thoughts from the back of my head.

if we think we want to get back on incubator track and there is a plausible expectation that this will eventually succeed then it makes sense to stick with the apache extras group id and release to sonatype.

If this is not realistic pipe dream then beanshell.org is a much more relevant group id me think, and we can find easily find some other venue for release.

Your thoughts?

**Comment by ebourg** [comment]
I think having two versions of the same libraries, using the same package and the same classes but using different groupIds is a recipe for jar hell and must stop as soon as possible, especially for a well known library like beanshell. If beanshell joins the incubator the groupId can be changed at this moment, as well as the package name.

**Comment by nickl-** [comment]
@ebourg Ty for your input.

I agree there should not be overlap of version numbers with different group-ids, hell indeed. This is not the idea.

Currently the group-id is **org.apache-extras.beanshell** as we did have aspirations for incubation at one point but that never realised and currently we are no closer to become an apache project then we ever are to getting JSR-274 accepted as a specification.

This thread is questioning whether we should return to the beanshell.org group id we used before. I'w assuming your vote goes for banshell.org as the group id? Hey why didn't I think about this before, this calls for a poll.

**Comment by nickl-** [comment]
Added the poll see 1st post.

**Comment by nickl-** [comment]
@pgiffuni this thread is about the group-id you were looking for #82 with discussions on the websitee

**Comment by pgiffuni** [comment]
@nickl Before changing back the group id it was important to point that github holds the auhoritative source so that had to be done:
http://beanshell.org/developer.html

**Comment by nickl-** [comment]
@pgiffuni  ty

**Comment by nickl-** [comment]
org.beanshell won thank you for your participation.
