### ISSUE TITLE
C-style array syntax doesn't work.

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#172]
This does not work:

int a\[\] = \{ 1, 2, 3\};

this, of course, does:

int \[\] a = \{ 1, 2, 3 \};

Reported by: patn

Original Ticket: "beanshell/bugs/51":https://sourceforge.net/p/beanshell/bugs/51

**Comment by opeongo** [comment]
The first part of this appears to be fixed, probably by #89.

There is still a bit of weirdness however.  Declaring these two in sequence causes an error:
```java
int a[] = { 1, 2, 3};
int [] a = { 1, 2, 3 };
// Error: Evaluation Error: Typed variable declaration : Typed variable: a was previously declared with type: int : at Line: 10 : in file: <unknown file> : int [ ] a = { 
```
I would think that the two declarations are equivalent, yet they appear to be different.  

On the other had, this works fine:
```java
      int a[] = {1,2,3};
      a = new int[] {1,2,3};
```

**Comment by nickl-** [comment]
The error is correct, we cannot redeclare a typed variable regardless if it is of the same type or not. This should give you a compile error in java as well.

@opeongo Thank you for verifying!

**Closed: works as implemented**

**Comment by opeongo** [comment]
In BeanShell it is possible to redeclare a variable to the same type.  This code works just fine:

```java
int[] a = new int[] {1 ,2, 3};
int[] a = new int[] {4 ,5, 6};
int[] a = new int[] {7 ,8, 9};
```

This is unsurprising to me, declared variables can be encountered in loops where the interpreter will re-execute them many times.  

However, I thought ```int[] a``` and ```int a[]``` were essentially the same thing, so I was surprised that the redeclaration fails in this case.  Not a problem, just unexpected.

**Comment by nickl-** [comment]
> This is unsurprising to me, declared variables can be encountered in loops where the interpreter will re-execute them many times.

What you are observing is the block scope of the loop this will be a new variable declaration every time the loop is executed which is not the same as inline.

Redeclaring an existing scoped variable, even with same type should actually cause an error.
Alternatively the type does not change with the different array declaration syntax so this should not throw an error.

I suggest we investigate the impact of both scenarios before deciding on a fix.

**ReOpen:  Not resolved**

**Comment by jimjag** [comment]
I think that the current behavior is the least surprising and more correct (Java seems to think so as well)... I vote we close

**Comment by nickl-** [comment]
Agreed with @jimjag - closed
