### ISSUE TITLE
Class Browser not find java.* on MacOSX

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#175]
On Mac OS X... BeanShell desktop's ClassBrowser does not find the classes that come with the VM.  I have mentioned on the mailing list how you can find them in cross-platform programmatic ways using ClassLoader.getResource\(\) tricks.

Reported by: dsmiley

Original Ticket: "beanshell/bugs/54":https://sourceforge.net/p/beanshell/bugs/54

**Comment by jimjag** [comment]
No longer applicable in BeanShell 3.0.0-SNAPSHOT.841
