### ISSUE TITLE
load() uses wrong class namespace

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#178]
Here's a weird problem: BeanShell does not use the most
up-to-date version of a class definition when one uses
the save/load commands.

Particularly, let's assume you start a bsh session,
working with a class. Then add a method to the class
outside of bsh, and do reloadClasses. At this point bsh
is able to recognize the changes in the class when new
instances are created. Then save the new instance of
this object to a serialized file with the save\(\) bsh
command. So far everything is fine, but when you try to
load\(\) the file to bsh back, you get the previous
description of the class \(the state before the
modification explained above\)\!

I have replicated the situation in many ways, but never
the same way twice. The following is an attempt to
demonstrate it simply:

Original class definition before bsh is started:
\---
import java.io.\*;

public class a implements Serializable \{
public void hello\(\) \{\}
\}
\---

Beginning of the bsh session:
\---
1.2b5 - by Pat Niemeyer \(pat@pat.net\)
bsh % b = new a\(\);
bsh % javap\(b\);
Class class a extends class java.lang.Object
public void a.hello\(\)
\---

At this point the class is changed externally \(by
simply adding a new method &amp;quot;bye&amp;quot;\):
\---
import java.io.\*;

public class a implements Serializable \{
public void hello\(\) \{\}
public void bye\(\) \{\}
\}
\---

The bsh session resumes:
\---
bsh % reloadClasses\(&amp;quot;a&amp;quot;\);
bsh % b3 = new a\(\);
bsh % javap\(b3\);
Class class a extends class java.lang.Object
public void a.hello\(\)
public void a.bye\(\)
bsh % save\(b3,&amp;quot;a.data&amp;quot;\);
bsh % javap\(b3\);
Class class a extends class java.lang.Object
public void a.hello\(\)
public void a.bye\(\)
bsh % b4 = load\(&amp;quot;a.data&amp;quot;\);
// Error: // Uncaught Exception: Method Invocation
oin.readObject : at Line: 10 : in file:
commands/load.bsh : oin .readObject \( \) 
Target exception: java.io.InvalidClassException: a;
Local class not compatible: stream classdesc
serialVersionUID=-4164003422557000035 local class
serialVersionUID=-21366284452840403
\---

This example is a little different from the original
way I discovered the problem. In my cases, after the
load\(\) command I would find the object to have the
previous definition\! That is it would be missing the
&amp;quot;bye&amp;quot; method that I introduced earlier in the same
session. This time I got an exception so I think it
shows that something is really wrong.

I hope my description helps to diagnose the problem.

Best regards,

Reported by: cengique

Original Ticket: "beanshell/bugs/57":https://sourceforge.net/p/beanshell/bugs/57

**Comment by nickl-** [comment]
Appears to be resolved in 3.0.0-SNAPSHOT.841

```java
bsh % b = new a();
--> $1 = a@606d8acf :a
bsh % javap(b);
Class class a extends class java.lang.Object
public void a.hello() :Method
--> void
bsh % reloadClasses("a");
Start ClassPath Mapping
End ClassPath Mapping
Start ClassPath Mapping
Mapping: Archive: file:/beanshell/target/bsh-3.0.0-SNAPSHOT.jar
Mapping: Directory /beanshell
End ClassPath Mapping
--> void
bsh % b3 = new a();
--> $2 = a@5479e3f :a
bsh % javap(b3);
Class class a extends class java.lang.Object
public void a.hello() :Method
public void a.bye() :Method
--> void
bsh % save(b3, "a.data");
--> void
bsh % b4 = load("a.data");
--> $3 = a@68c4039c :a
bsh % javap(b4);
Class class a extends class java.lang.Object
public void a.hello() :Method
public void a.bye() :Method
--> void
```

Closed: works as expected
