### ISSUE TITLE
public method in package scope super

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#180]
Problem:
Beanshell cannot invoke a public method in a package 
scope superclass, when Java can. 

Below is a summary of how to reproduce the problem, 
where the problem is in the code, and possible emthods 
of fixing it.

Reproducing
\-----------

1\) Create a subdirectory foo.
2\) Make the following two classes in the subdirectory.

Parent.java ----
package foo;

class Parent \{
public int foo\(\) \{
return 1;
\}
\}// Parent
\---- end Parent.java

Child.java ------
package foo;

public class Child extends Parent\{

\}// Child
\----- end Child.java

3\) Compile the classes.
4\) Take a copy of the Beanshell jar to the parent 
directory, so you have a directory tree looking like 
this:
. - bsh-1.2b5.jar
\- foo/
\- Child.java
\- Child.class
\- Parent.java
\- Parent.class

5\)Run Beanshell with the command line:
java -classpath &amp;quot;.;bsh-1.2b5.jar&amp;quot; bsh.Console

6\) In the Beanshell workspace do the following:

1.2b51 - by Pat Niemeyer \(pat@pat.net\)
bsh % System.out.println\(new foo.Child\(\).foo\(\)\);
// Error: reflection error: bsh.ReflectError: No args 
method foo\(\) not found in class'foo.Child' : at Line: 
1 : in file: &amp;lt;unknown file&amp;gt; : .foo \( \) 

As you can see the method is not being found. However, 
the following java class compiles fine:

Test.java -----------

public class Test \{
public static void main\(String \[\] args\) \{
System.out.println\(new foo.Child\(\).foo\(\)\);
\}
\}// Test

\---- end Test.java

What the problem is
\-------------------

In bsh.Reflect.java first Accessible methods are 
checked, then a check for no argument methods is done,
then the getMethods call is used. The method would be 
found if the getMethods\(\) call was used, but it is 
failing at the check for no argument methods.

How to fix it.
\--------------
The solution is either to remove the no argument check 
and fix the error message a few lines down to cover 
the no arguments case, or to add an additional check 
for no args methods using the getMethods\(\) call.

Reported by: nfortescue

Original Ticket: "beanshell/bugs/59":https://sourceforge.net/p/beanshell/bugs/59

**Comment by opeongo** [comment]
This works when run with the following command line:
```
java -classpath .;target/bsh-3.0.0-SNAPSHOT.jar bsh.Interpreter
BeanShell 3.0.0-SNAPSHOT.463
bsh % print(new foo.Child().foo());
1
--> void
```
I did have problems running this in the BeanShell Desktop, so I assume that this is related to passing along the classpath correctly.  If I first used the command ```addClassPath(".");``` then everything worked correctly.

This issue should probably be closed.

File foo/Parent.java
```java
package foo;

class Parent {
public int foo() {
return 1;
}
}// Parent
```

File foo/Child.java
```java
package foo;

public class Child extends Parent{

}// Child
```

File FooTest.java
```java
public class FooTest {
   public static void main(String [] args) {
      System.out.println(new foo.Child().foo());
   }
}// FooTest
```

**Comment by nickl-** [comment]
@opeongo Tx for verifying!

**Closed: Cannot reproduce**
