### ISSUE TITLE
polymorphism with hotspot/classic differ

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#201]
Having a script like:

//startscript///////////////////
perform\(Callback callbackobject\)\{
callbackobject.install\(super\);
\}
//return \(Sub1\)this; //switch between the two types..
return \(Sub2\)this;
//startscript///////////////////

and the classes:

public class Callback \{
public void install\(Sub1 s\)\{
System.out.println\(&amp;quot;install\(Sub1\)&amp;quot;\);
\}
public void install\(Sub2 s\)\{
System.out.println\(&amp;quot;install\(Sub1\)&amp;quot;\);
\}
\}

public class Base\{
//...
\}
public class Sub1 extends Base\{
//...
\}
public class Sub2 extends Base\{
//...
\}

running the script in jdk1.3.0-classic gives correct 
output.
running the same in jdk1.3.0-hotspot sometimes takes 
wrong install-method\!
workaround is to cast return-value to the correct Type:

//startscript///////////////////
perform\(Callback callbackobject\)\{
callbackobject.install\(\(Sub2\)super\);
\}
return \(Sub2\)this;
//startscript///////////////////

...which is not really bad.

The fact that beanshell \(or java\) behaves different 
in -classic mode is really ugly, since we develop in 
classic mode cause of the debuggers slow speed with 
hotspot.

Reported by: *anonymous

Original Ticket: "beanshell/bugs/63":https://sourceforge.net/p/beanshell/bugs/63

**Comment by opeongo** [comment]
There is insufficient information to reproduce this problem.

**Comment by nickl-** [comment]
**Closed: cannot reproduce**
