### ISSUE TITLE
Exceptions unweildy when bsh embedded

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#205]
We are embedding bsh into an application to provide a
scripting capability to our software.  I'm currently
trying to fix up the error handling capabilities. 
Right now bsh seems to always add the entire contents
of the script to the exception message, making the
Exception almost completely unreadable.  I've caught
the EvalError and been able to chop it into a more
readable version using .getErrorLineNumber\(\) and
getErrorText\(\), except that there seems to be no way to
get at the actual error message without also getting
the entire contents of the string passed to
Interpreter.eval\(\) because something somewhere has
called prependMessage\(\) with the contents of the
evaluation.  Is there a clean way to handle this?

Reported by: nsharp

Original Ticket: "beanshell/bugs/67":https://sourceforge.net/p/beanshell/bugs/67

**Comment by opeongo** [comment]
Feature request, not a bug

**Comment by nickl-** [comment]
This was resolved with the addition of `showEvalString`

https://github.com/beanshell/beanshell/blob/53be48718ef7a731e2d6d4bcee5d2e9af9b8176d/src/main/java/bsh/Interpreter.java#L769-L792

**Closed: resolved**
