### ISSUE TITLE
Error in demo links in online doc

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#208]
The links to the demo applets on 
http://www.beanshell.org/manual/appletmode.html\#The\_BeanShell\_Demo\_Applet 
doesn't work.

Reported by: *anonymous

Original Ticket: "beanshell/bugs/70":https://sourceforge.net/p/beanshell/bugs/70

**Comment by nickl-** [comment]
**Closed: moved to #82 **
