### ISSUE TITLE
Bad major version number in JDK 1.1.8 /2

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#219]
I tried to run bsh-1.2b6.jar with the following .CMD:

@echo off
SetLocal
set 
CLASSPATH=F:\Util\Java\BeanShel\bsh-1.2b6.jar;%CLASSP
ATH%
java -verbose %1 %2 %3 %4 %5 %6 %7 %8 %9
endLocal

and bsh.Console \(or  bsh.Interpreter as arguments\).

I get an error &amp;quot;Bad major version number&amp;quot; error \(I added 
some context before:

\[Loaded java/util/Vector.class from 
E:\JAVA11\DLL\\..\lib\classes.zip\]
\[Loaded 
com/ibm/security12/java/security/ProtectionDomainStore.cl
ass from E:\JAVA11\LIB\SecMa.jar\]
\[Loaded 
com/ibm/security12/java/security/ProtectionDomain.class 
from E:\JAVA11\LIB\SecMa.jar\]
\[Loaded 
com/ibm/security12/java/security/AccessControlContext.cla
ss from E:\JAVA11\LIB\SecMa.jar\]
\[Loaded 
com/ibm/security12/java/security/AccessControlContextSe
curityManager.class from E:\JAVA11\LIB\SecMa.jar\]
\[Loaded DLL 'E:\JAVA11\DLL\\..\bin\javaz.dll' \(rc = 0 module 
handle = 0x144f\)\]
\[Failed to load bsh/Console.class from 
F:\Util\Java\BeanShel\bsh-1.2b6.jar for this reason: Bad 
major version number\]
Can't find class bsh/Console or something it requires

I think that this error is related to compiling with JDK &amp;gt;1.2 
and running with 1.1.8. The wesite claims some 
compatibility wtih 1.1.
Maybe compiling with -target would help. I have Swing 1.1 
and 1.1.1.

This is JDK 1.1.8 on OS/2 Warp 4 Fixpack 15.

Reported by: davidme

Original Ticket: "beanshell/bugs/81":https://sourceforge.net/p/beanshell/bugs/81

**Comment by opeongo** [comment]
This looks like a byte code/runtime version mis-match.  Not reproducible.  Should be closed.

**Comment by nickl-** [comment]
@opeongo Tx for verifying

**Closed: cannot reproduce**
