### ISSUE TITLE
2bytes character string parsing problem

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#226]
I have some problem with several Korean characters.
all of these unlucky character's codes contain 0x5C \('\' 
in ascii\); 

In range 0xAC5C ~ 0xD75C, all of 0x??5C characters...

For example, if XX were a  korean character 0xB85C in 
uni-code. \(sorry i know you can not read real 0xB85C 
letter in your non-korean system\).

bsh % some = 'XX';
// Error: Error parsing input: bsh.TokenMgrError: 
Lexical error at line 1, column 21.  Encountered: &amp;quot;;&amp;quot; 
\(59\), after : &amp;quot;\'\\\\\'&amp;quot;

I have found that all of double byte code languages 
\(Japanese, Chinese, Korean\) have same problem...

Reported by: eirny

Original Ticket: "beanshell/bugs/88":https://sourceforge.net/p/beanshell/bugs/88

**Comment by nickl-** [comment]
You probably want to use the `\u` for unicode instead of `0x` for hexadecimal or base 16 number

BeanShell 3.0.0-SNAPSHOT.841 speaks Korean
```java
bsh % some = "0xB85C";
--> $2 = "0xB85C" :String
bsh % some = "\uB85C";
--> $3 = "로" :String
```
Cannot reproduce, works as expected
