### ISSUE TITLE
Undef vars not detected in if statement

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#228]
If an undefined variable is used in an &amp;quot;if&amp;quot; statement,
no error is produced:

if \(undefinedvar \!= null\) \{
print\(&amp;quot;This is a bogus result&amp;quot;\);
\}

This should throw an exception instead.

Reported by: shankarunni

Original Ticket: "beanshell/bugs/90":https://sourceforge.net/p/beanshell/bugs/90

**Comment by nickl-** [comment]
It is allowed to compare undefined variables, the correct truthy check for this example would be:

```java
if ( undefinedvar == void ) {
    print("This is an undefined variable");
}
```
