### ISSUE TITLE
Support for varargs

### ISSUE THREAD

**Issue by thevpc** [beanshell/beanshell#23]
The Latest version seems not to support varargs 

(
see Types.java 
private static boolean isSignatureVarargsAssignable(
        Class[] from, Class[] to )
    {
        return false; // ?
    }
)

Some dude seems to have resolved that since 2007 still this is not integrated
http://beanshell.2283338.n4.nabble.com/Support-of-varargs-an-example-td3316504.html

Could one fix this plz?

**Comment by thirion** [comment]
I found this fork of BeanShell: https://github.com/pejobo/beanshell2

The following works in that version(2.1.8) but not 2.0b6:
ArrayList entries = new ArrayList(Arrays.asList(new String[]{"hey", "you"}));
for(String entry : entries) {
print(entry);
}

Any chance of incorporating the functionality from there?

Unfortunately this still doesn't work:
Map.Entry<String, String> entries = runtime.getParameters().entrySet();
for(String entry : entries) {
print(entry);
}

**Comment by nickl-** [comment]
We now have full support for varargs. see beanshell/beanshell@c1adf5d

**Comment by geovanny1781** [comment]
Not support varargs?, I try this simple function:
interpreter.eval("int sumTwoNum(int... numeros) {  return 1;}");
and error: 
bsh.ParseException: Parse error at line 1, column 18.  Encountered: int

**Comment by nickl-** [comment]
@geovanny1781 See  #761
