### ISSUE TITLE
java.lang.NoSuchMethodError: bsh.util.ClassBrowser$PackageTr

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#245]
I'm trying to run BeanShell's class browser but I'm 
getting a method not found.

java.lang.NoSuchMethodError: 
bsh.util.ClassBrowser$PackageTree: method 
setExpandsSelectedPaths\(Z\)V not found

I'm using bsh-1.2b7.jar on 
SunOS sunstorm 5.7 Generic\_106541-12 sun4u sparc 
SUNW,Ultra-4
with java full version &amp;quot;Solaris\_JDK\_1.2.2\_06&amp;quot;.

Reported by: bbrooks

Original Ticket: "beanshell/bugs/107":https://sourceforge.net/p/beanshell/bugs/107

**Comment by opeongo** [comment]
Not a BeanShell bug

**Comment by nickl-** [comment]
**Closed: Cannot reproduce**
