### ISSUE TITLE
Octal escape ParseException

### ISSUE THREAD

**Issue by peetscott** [beanshell/beanshell#25]
The lexical specification of the <tt>STRING_LITERAL</tt> token allows for octal escape sequences of one, two, of three digits in the range 000-377.

This is a legal <tt>STRING_LITERAL</tt>:

```
"\12"  // --> newline character
```

Try this

```
bsh % show();
bsh % "..\12..";
<..
..>
```

Fine. Now

```
bsh % "\12";
// Error: Parser Error: ...
```

Actually, this is a <tt>StringIndexOutOfBoundsException</tt> repackaged as a <tt>ParseException</tt>. <tt>BSHLiteral.stringSetup()</tt> expects the octal escape sequence to be three digits long and reads beyond the end of the <tt>String</tt> argument. This occurs when the escape sequence is at the end of the <tt>String</tt> AND is less than three digits long.

Try this

```
bsh % "\012";
<
>
```

Fine.

Octal escape sequences are intended for characters in the range 000-377 (0-255). Try this

```
bsh % "\777";
<?>
bsh % $_.codePointAt(0);
<511>
```

This is legal because the lexer accepts 77 as an octal value, and treats the third 7 as a simple character. But <tt>BSHLiteral</tt> sees the third 7 as a continuation of an octal number and consumes
it.

---

Possible Fixes

1.) Redefine <tt>STRING_LITERAL</tt> to require three digit octal escapes.

```
      ...
  /*   Scratch This Line | ["0"-"7"] ( ["0"-"7"] )?   */
  | ["0"-"3"] ["0"-"7"] ["0"-"7"]
      ...
```

2.) Test the end-of-string boundary in <tt>BSHLiteral.stringSetup()</tt>.
   And ?
   Do some range testing.

**Comment by stain** [comment]
Agree that this is a bug - beanshell should support the same [string escapes as Java](http://docs.oracle.com/javase/specs/jls/se7/html/jls-3.html#jls-3.10.6) which would include `\12` also at the end of the string.

I think `"\777"` would be interpreted as octal 77 plus the character `7` also in Java.

**Comment by nickl-** [comment]
This should be resolved now.

TODO: Need unit tests see #72

**Comment by nickl-** [comment]
Fixed including unit tests.

see beanshell/beanshell@30f36ee
