### ISSUE TITLE
Unable to call inherited methods

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#256]
Bean shell version 1.2.7
Here is the sample program that highlights the 
problem...

import java.util.\*;
abstract class AbstractA \{
abstract public String getValue\(\);
public void print\(\) \{
System.out.println\(getValue\(\)\);
\}
\}

public class A extends AbstractA \{
public String getValue\(\) \{
return \(&amp;quot;Class A&amp;quot;\);
\}

public static void main \(String\[\] args\) \{
/\* This works if called from java. If I try to put 
following two lines in bsh
\* I get error like
\* // Error: Error in method invocation: 
\* No args method print\(\) not found in class'A' : 
at Line: 2 : in file: &amp;lt;unknown file&amp;gt; : a .print \( \)
\*/
A a = new A\(\);
a.print\(\);
\}
\}

Reported by: *anonymous

Original Ticket: "beanshell/bugs/118":https://sourceforge.net/p/beanshell/bugs/118

**Comment by opeongo** [comment]
Works as expected in current master bsh-3.0.0-SNAPSHOT.jar

**Comment by nickl-** [comment]
**Closed: Works as expected**
