### ISSUE TITLE
Methods not working for inner classes inside SecurityManager

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#266]
BeanShell 1.3 \(always\)
BeanShell 1.2.7 \(Sometimes. I believe it is only if
setAccessible\(true\) has been called.\)

When I run a script that tries to iterate through a
Hashtable's keys
\(ie: Enumeration keys = h.keys\(\);
while\(keys.hasMoreElements\(\)\)\{\}\)

I encounterd an Exception:
Error in method invocation: No args method
hasMoreElements\(\) not found in
class'java.util.Hashtable$Enumerator'

I am running this in a SecurityManager that doesn't
allow access to the suppressAccessChecks permission. 

I debugged this using the Beanshell 1.3 source, and
found the problem is in findAccessibleMethod\(\) where it
checks the permissions. While it's checking the
permissions, an AccessControlException is thrown. This hits
a higher level and eventually results in the method not
being found.
I have solved this in my build by adding:
\-----Begin Snippit-----
catch \(AccessControlException e\)
\{
// if this is an exception about suppressAccessChecks
// we need to continue on so we can check the
// interface &amp;amp; superclass methods.

if\(\!e.getPermission\(\).getName\(\).equals\(&amp;quot;suppressAccessChecks&amp;quot;\)\)
throw e;
\}
\-----End Snippit-----
Immediately after
\-----Begin Snippit-----
\} catch \( NoSuchMethodException e \) \{ 
// ignore and move on
\}
\-----End Snippit-----
in findAccessibleMethod\(\)

Once I introduced this code the problem went away. I
believe there is a similar issue for for Fields, and I
added identical code to findAccessibleField\(\).

I dont know what compatability issues this raises for
older jvm's, as I'm using this with the 1.4.1 jvm

I have attached the file I have with fixes for both
Field and Method for Beanshell 1.3 \(updated from head
CVS 7/7/03\)

Reported by: cgoudie

Original Ticket: "beanshell/bugs/128":https://sourceforge.net/p/beanshell/bugs/128

**Comment by nickl-** [comment]
seems to work in BeanShell 3.0.0-SNAPSHOT.936

```java
bsh % numbers = new Hashtable<String, Integer>();
--> $0 = {} :Map
numbers.put("one", 1);
--> $1 = null :null
numbers.put("two", 2);
--> $2 = null :null
numbers.put("three", 3);
--> $3 = null :null
bsh % keys = numbers.keys();
--> $4 = java.util.Hashtable$Enumerator@7de26db8 :Enumerator
bsh % while(keys.hasMoreElements()) print(keys.nextElement());
two
one
three
--> void
```

Closed: cannot reproduce
