### ISSUE TITLE
calling methods of script classes with null parameters fails

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#267]
I have a class defined in a script as: 
```java
class LURLEntityResolver implements EntityResolver {
    InputSource resolveEntity(String publicID, String systemID) {
        System.err.println("resolveEntity "+systemID);
    }
}
```

It works fine when publicID and systemID are non null. When 
one of them is null, BSH throws: 

bsh.InterpreterError: Null value in getAssignableForm: class 
java.lang.String, null 
at bsh.NameSpace.getAssignableForm\(Unknown Source\) 
at bsh.BshMethod.invokeImpl\(Unknown Source\) 
at bsh.BshMethod.invoke\(Unknown Source\) 
at bsh.BshMethod.invoke\(Unknown Source\) 
at bsh.This.invokeMethod\(Unknown Source\) 
at bsh.This.invokeMethod\(Unknown Source\) 
at bsh.XThis$Handler.invokeImpl\(Unknown Source\) 
at bsh.XThis$Handler.invoke\(Unknown Source\) 
at $Proxy0.resolveEntity\(Unknown Source\) 

It seems that Reflect.getTypes sets the type to null if the arg is 
null.  When I add 
if\(rhs == null\) 
rhs = Primitive.NULL; 
at the top of NameSpace.getAssignableForm it does not throw 
anything anymore and it seems to work. 

Reported by: neillie

Original Ticket: "beanshell/bugs/129":https://sourceforge.net/p/beanshell/bugs/129

**Comment by nickl-** [comment]
There are a few things wrong here:

1. you will need an EntityResolver interface
2. you will also need an InputSource class
3. then you will have to make sure that resolveEntity method actually returns said InputSource

Like I said, many things wrong here but what is not an issue is passing null as parameters:

```java
bsh % interface EntityResolver {}
--> $0 = interface EntityResolver :Class
bsh % class InputSource {}
--> $1 = class InputSource :Class
bsh % class LURLEntityResolver implements EntityResolver {
    InputSource resolveEntity(String publicID, String systemID) {
        System.err.println("resolveEntity " + systemID);
        return new InputSource();
    }
}
--> $2 = class LURLEntityResolver :Class
bsh % new LURLEntityResolver().resolveEntity(null, null);
resolveEntity null
--> $3 = InputSource@7d417077 :InputSource
```

Closed: works as expected
