### ISSUE TITLE
Integration with ATG Dynamo has wrong URL

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#268]
In the documentation

http://www.beanshell.org/docs.html

There's a link to the integration with ATG Dynamo:

Integrating BeanShell with ATG Dynamo application
server \(by Will Sargent, ATG\)

This link should be updated to
http://tersesystems.com/code/bsh/ and the reference to
ATG taken out \(since I don't work for them anymore\).

Reported by: wsargent

Original Ticket: "beanshell/bugs/130":https://sourceforge.net/p/beanshell/bugs/130

**Comment by pgiffuni** [comment]
The link is not there anymore .
