### ISSUE TITLE
Problem with String.valueOf(int)

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#269]
I have a problem only with 1.3.b2.

In Java I load and execute a beanshell file
In this file I have extarct the problem.

String stringVersion=informationVersion.getValue\(\);
if \(stringVersion\!=null\)
\{
int version=Integer.valueOf\(stringVersion\);
version++;

print\(&amp;quot;stringVersion=&amp;quot;+stringVersion\);
print\(&amp;quot;version=&amp;quot;+version\);

stringVersion=String.valueOf\(version\);
print\(&amp;quot;NewstringVersion=&amp;quot;+stringVersion\);
\}

==============

The result is for example :

stringVersion=1
version=2
NewstringVersion=1 ???

Reported by: *anonymous

Original Ticket: "beanshell/bugs/131":https://sourceforge.net/p/beanshell/bugs/131

**Comment by opeongo** [comment]
When I try this code under the current master bsh-3.0.0-SNAPSHOT.jar I get the expected result.

Not reproducible.

**Comment by nickl-** [comment]
**Closed: Not reproducible**
