### ISSUE TITLE
0xFFFFFFFF doesn't work

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#270]
Bsh does not understand integer constant 0xFFFFFFFF,
Java does.

Reported by: yozh

Original Ticket: "beanshell/bugs/132":https://sourceforge.net/p/beanshell/bugs/132

**Comment by opeongo** [comment]
Works as expected in current master bsh-3.0.0-SNAPSHOT.jar

**Comment by nickl-** [comment]
**Closed: Works as expected**
