### ISSUE TITLE
Uncaught exception in class browser

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#271]
Right click a new class browser from the 2.0 desktop.
I browsed lots of classes.  I modal dialog from a windows 
application opened. I think it was a yahoo email reminder 
from internet explorer. Then I got the following stack 
trace.

bash-2.05b$ $JAVA\_HOME/bin/java -
cp &amp;quot;$BEANSHELLEXEJAR&amp;quot; bsh.Console
Start ClassPath Mapping
Mapping: Archive: file:/C:/bin/bsh-2.0b1.jar
Mapping: Archive: file:/C:/j2sdk1.4.1\_01/jre/lib/rt.jar
End ClassPath Mapping
java.lang.NoClassDefFoundError: 
javax/servlet/http/HttpServlet
at java.lang.ClassLoader.defineClass0\(Native 
Method\)
at java.lang.ClassLoader.defineClass
\(ClassLoader.java:502\)
at java.security.SecureClassLoader.defineClass
\(SecureClassLoader.java:123\)
at java.net.URLClassLoader.defineClass
\(URLClassLoader.java:250\)
at java.net.URLClassLoader.access$100
\(URLClassLoader.java:54\)
at java.net.URLClassLoader$1.run
\(URLClassLoader.java:193\)
at java.security.AccessController.doPrivileged
\(Native Method\)
at java.net.URLClassLoader.findClass
\(URLClassLoader.java:186\)
at java.lang.ClassLoader.loadClass
\(ClassLoader.java:299\)
at sun.misc.Launcher$AppClassLoader.loadClass
\(Launcher.java:265\)
at java.lang.ClassLoader.loadClass
\(ClassLoader.java:255\)
at 
bsh.classpath.ClassManagerImpl.classForName\(Unknown 
Source\)
at bsh.util.ClassBrowser.setMlist\(Unknown 
Source\)
at bsh.util.ClassBrowser.valueChanged
\(Unknown Source\)
at javax.swing.JList.fireSelectionValueChanged
\(JList.java:1318\)
at 
javax.swing.JList$ListSelectionHandler.valueChanged
\(JList.java:1332\)
at 
javax.swing.DefaultListSelectionModel.fireValueChanged
\(DefaultListSelectionModel.java:187\)
at 
javax.swing.DefaultListSelectionModel.fireValueChanged
\(DefaultListSelectionModel.java:167\)
at 
javax.swing.DefaultListSelectionModel.fireValueChanged
\(DefaultListSelectionModel.java:214\)
at 
javax.swing.DefaultListSelectionModel.changeSelection
\(DefaultListSelectionModel.java:402\)
at 
javax.swing.DefaultListSelectionModel.changeSelection
\(DefaultListSelectionModel.java:411\)
at 
javax.swing.DefaultListSelectionModel.setSelectionInterv
al\(DefaultListSelectionModel.java:435\)
at javax.swing.JList.setSelectionInterval
\(JList.java:1605\)
at 
javax.swing.plaf.basic.BasicListUI$MouseInputHandler.adj
ustFocusAndSelection\(BasicListUI.java:1332\)
at 
javax.swing.plaf.basic.BasicListUI$MouseInputHandler.mo
usePressed\(BasicListUI.java:1294\)
at 
java.awt.AWTEventMulticaster.mousePressed
\(AWTEventMulticaster.java:218\)
at java.awt.Component.processMouseEvent
\(Component.java:5090\)
at java.awt.Component.processEvent
\(Component.java:4890\)
at java.awt.Container.processEvent
\(Container.java:1566\)
at java.awt.Component.dispatchEventImpl
\(Component.java:3598\)
at java.awt.Container.dispatchEventImpl
\(Container.java:1623\)
at java.awt.Component.dispatchEvent
\(Component.java:3439\)
at 
java.awt.LightweightDispatcher.retargetMouseEvent
\(Container.java:3450\)
at 
java.awt.LightweightDispatcher.processMouseEvent
\(Container.java:3162\)
at 
java.awt.LightweightDispatcher.dispatchEvent
\(Container.java:3095\)
at java.awt.Container.dispatchEventImpl
\(Container.java:1609\)
at java.awt.Window.dispatchEventImpl
\(Window.java:1585\)
at java.awt.Component.dispatchEvent
\(Component.java:3439\)
at java.awt.EventQueue.dispatchEvent
\(EventQueue.java:450\)
at 
java.awt.EventDispatchThread.pumpOneEventForHierarch
y\(EventDispatchThread.java:197\)
at 
java.awt.EventDispatchThread.pumpEventsForHierarchy
\(EventDispatchThread.java:150\)
at java.awt.EventDispatchThread.pumpEvents
\(EventDispatchThread.java:144\)
at java.awt.EventDispatchThread.pumpEvents
\(EventDispatchThread.java:136\)
at java.awt.EventDispatchThread.run
\(EventDispatchThread.java:99\)
java.lang.NoClassDefFoundError: 
javax/servlet/http/HttpServlet
at java.lang.ClassLoader.defineClass0\(Native 
Method\)
at java.lang.ClassLoader.defineClass
\(ClassLoader.java:502\)
at java.security.SecureClassLoader.defineClass
\(SecureClassLoader.java:123\)
at java.net.URLClassLoader.defineClass
\(URLClassLoader.java:250\)
at java.net.URLClassLoader.access$100
\(URLClassLoader.java:54\)
at java.net.URLClassLoader$1.run
\(URLClassLoader.java:193\)
at java.security.AccessController.doPrivileged
\(Native Method\)
at java.net.URLClassLoader.findClass
\(URLClassLoader.java:186\)
at java.lang.ClassLoader.loadClass
\(ClassLoader.java:299\)
at sun.misc.Launcher$AppClassLoader.loadClass
\(Launcher.java:265\)
at java.lang.ClassLoader.loadClass
\(ClassLoader.java:255\)
at 
bsh.classpath.ClassManagerImpl.classForName\(Unknown 
Source\)
at bsh.util.ClassBrowser.setMlist\(Unknown 
Source\)
at bsh.util.ClassBrowser.valueChanged
\(Unknown Source\)
at javax.swing.JList.fireSelectionValueChanged
\(JList.java:1318\)
at 
javax.swing.JList$ListSelectionHandler.valueChanged
\(JList.java:1332\)
at 
javax.swing.DefaultListSelectionModel.fireValueChanged
\(DefaultListSelectionModel.java:187\)
at 
javax.swing.DefaultListSelectionModel.fireValueChanged
\(DefaultListSelectionModel.java:157\)
at 
javax.swing.DefaultListSelectionModel.setValueIsAdjustin
g\(DefaultListSelectionModel.java:554\)
at javax.swing.JList.setValueIsAdjusting
\(JList.java:1672\)
at 
javax.swing.plaf.basic.BasicListUI$MouseInputHandler.mo
useReleased\(BasicListUI.java:1370\)
at 
java.awt.AWTEventMulticaster.mouseReleased
\(AWTEventMulticaster.java:228\)
at java.awt.Component.processMouseEvent
\(Component.java:5093\)
at java.awt.Component.processEvent
\(Component.java:4890\)
at java.awt.Container.processEvent
\(Container.java:1566\)
at java.awt.Component.dispatchEventImpl
\(Component.java:3598\)
at java.awt.Container.dispatchEventImpl
\(Container.java:1623\)
at java.awt.Component.dispatchEvent
\(Component.java:3439\)
at 
java.awt.LightweightDispatcher.retargetMouseEvent
\(Container.java:3450\)
at 
java.awt.LightweightDispatcher.processMouseEvent
\(Container.java:3165\)
at 
java.awt.LightweightDispatcher.dispatchEvent
\(Container.java:3095\)
at java.awt.Container.dispatchEventImpl
\(Container.java:1609\)
at java.awt.Window.dispatchEventImpl
\(Window.java:1585\)
at java.awt.Component.dispatchEvent
\(Component.java:3439\)
at java.awt.EventQueue.dispatchEvent
\(EventQueue.java:450\)
at 
java.awt.EventDispatchThread.pumpOneEventForHierarch
y\(EventDispatchThread.java:197\)
at 
java.awt.EventDispatchThread.pumpEventsForHierarchy
\(EventDispatchThread.java:150\)
at java.awt.EventDispatchThread.pumpEvents
\(EventDispatchThread.java:144\)
at java.awt.EventDispatchThread.pumpEvents
\(EventDispatchThread.java:136\)
at java.awt.EventDispatchThread.run
\(EventDispatchThread.java:99\)
bash-2.05b$ 

Thank you again for beanshell.  When will you integrate 
with IBM's Eclipse? ;\)

cmagid@kronos.com

Reported by: cmagid

Original Ticket: "beanshell/bugs/133":https://sourceforge.net/p/beanshell/bugs/133

**Comment by opeongo** [comment]
Not reproducible

**Comment by nickl-** [comment]
**Closed: Not reproducible**
