### ISSUE TITLE
exec() command doesn't print all output

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#273]
exec\(\) command doesn't print all output.

Example \(myfile exists, blah does not\):

at the linux prompt:
-&amp;gt; diff myfile blah
diff: blah: No such file or directory

at the bsh prompt:
bsh % exec\(&amp;quot;diff myfile blah&amp;quot;\);
bsh % 

Reported by: jswap

Original Ticket: "beanshell/bugs/135":https://sourceforge.net/p/beanshell/bugs/135

**Comment by opeongo** [comment]
Currently the ```exec()``` command will only print the standard output of the command that is being executed.  Standard error is ignored.

This could be changed by using ProcessBuilder to create the task and merging the output and error streams.  This would change the behaviour of an existing command, and may break existing users.

**Comment by nickl-** [comment]
Standard error should print to `interpreter.getErr()'

**Comment by nickl-** [comment]
I don't think the process to execute will change anything for anyone, as long as the command can execute it should be transparent.

**Comment by nickl-** [comment]
That said as far as the `diff myfile blah` is concerned:

```java
bsh % exec("diff t8.java.txt t9.java.txt");
1,6c1,11
< public class t8 {
<   public static void main(java.lang.String[] $0s) {
<     byte b1;
<     b1 = 127;
<     return;
<   }
---
> public class t9 {
>     public static void main(java.lang.String[] $0s) {
>         setStrictJava(true);
>         byte b2 = 128; //should not compile
>         byte b1 = -b2; //should not compile
>         System.out.println("b1 = "+b1+"b2 = "+b2);
>         byte b3 = 1;
>         byte b4 = -b3; //should not compile
>         System.out.println("b3 = "+b3+"b4 = "+b4);
>         return;
>     }
--> void
```

Works as expected, we can also make improvements at a later stage.
