### ISSUE TITLE
for-loop indexes and += broken in 1.3.0

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#274]
for \(int i = 0; i &amp;lt; 10; i++\) \{ print\(i+=i\); \}

In Beanshell 1.2b8

0
2
6
14

In Beanshell 1.3.0

0
2
4
6
8
10
12
14
16
18

The first output appears to be correct and the second 
incorrect.

Reported by: redross

Original Ticket: "beanshell/bugs/136":https://sourceforge.net/p/beanshell/bugs/136

**Comment by opeongo** [comment]
Works as expected in current master bsh-3.0.0-SNAPSHOT

**Comment by nickl-** [comment]
**Closed: Works as expected**
