### ISSUE TITLE
Wrong line and col numbers with 2.0b1 GUI Console

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#275]
Looks like 2.0b1 doesn't count lines properly when
reading from the GUI console, so it thinks the entire
input is one line, with an ever-increasing column
number.  This only happens in the GUI console, however.

Try entering the following into the GUI console:

foo\(\)
\{
x\(\(y\);
\}

On the third line above, it says

// Error: Parser Error: Parse error at line 1, column
55\.  Encountered: \(

Should be line 3, column 2. 

This works fine in the bsh.Interpreter class when it
reads from the standard input.

Reported by: shankarunni

Original Ticket: "beanshell/bugs/137":https://sourceforge.net/p/beanshell/bugs/137

**Comment by opeongo** [comment]
This appears to have been fixed.  The correct line numbers are displayed in the error message using current master bsh-3.0.0-SNAPSHOT

**Comment by nickl-** [comment]
**Closed: Works as expected**
