### ISSUE TITLE
Cut/Paste should involve the System clipboard

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#277]
To facilitate data exchange intra apps, the cut/paste
should use the System clipboard.

Thanks,

Ben

Reported by: binhph

Original Ticket: "beanshell/bugs/139":https://sourceforge.net/p/beanshell/bugs/139

**Comment by opeongo** [comment]
Should be closed

**Comment by nickl-** [comment]
**Closed by reporter**
