### ISSUE TITLE
Can't use static fields of nested classes as parameters

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#278]
Given a class B nested within a class A:

public class A
\{
private B b;

public static class B
\{
public static final B THING = new B\(\);
\}

public void setB\(B b\)
\{
this.b = b;
\}
\}

The following bsh code fails at line 2 with &amp;quot;Method setB
\(A$B\) not found in class A&amp;quot;:

a = new A\(\);
a.setB\(A.B.THING\);

Reported by: ejain

Original Ticket: "beanshell/bugs/140":https://sourceforge.net/p/beanshell/bugs/140

**Comment by opeongo** [comment]
Works as expected under current master bsh-3.0.0-SNAPSHOT

**Comment by nickl-** [comment]
**Closed: Works as expected**
