### ISSUE TITLE
Variable handling in bsh1.3.0

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#279]
There seem to be a bug quite important in the beanshell
interpreter. Using version 1.3.0 \(seems to be fixed in
2.0b1\) and jdk 1.4.2, the following occurs when
executing a script file:
The following code :
String test\(\) \{
String a = &amp;quot;aaa&amp;quot;;
if \(true\) \{
a = &amp;quot;true&amp;quot;;
\} else \{
a = &amp;quot;false&amp;quot;;
\}
System.out.println\(&amp;quot;a = &amp;quot;+a\);
return &amp;quot;blabla&amp;quot;;
\}
will print &amp;quot;a = true&amp;quot;. BUT the following code
String test\(\) \{
if \(true\) \{
String a = &amp;quot;aaa&amp;quot;;
if \(true\) \{
a = &amp;quot;true&amp;quot;;
\} else \{
a = &amp;quot;false&amp;quot;;
\}
System.out.println\(&amp;quot;a = &amp;quot;+a\);
\}
return &amp;quot;blabla&amp;quot;;
\}
will print &amp;quot;a = aaa&amp;quot;.
Now here is some code that works:
String test\(\) \{
String a = &amp;quot;aaa&amp;quot;;
if \(true\) \{
if \(true\) \{
a = &amp;quot;true&amp;quot;;
\} else \{
a = &amp;quot;false&amp;quot;;
\}
System.out.println\(&amp;quot;a = &amp;quot;+a\);
\}
return &amp;quot;blabla&amp;quot;;
\}
This one prints &amp;quot;a = true&amp;quot;;
This is happening only if the flag strictJava is set to
false. If it is set to true, the following exception is
thrown in the second case:
Typed variable declaration : \(Strict Java mode\)
Assignment to undeclared variable: a : at Line: 33 : in
file: \*\*\*\*\* : a = &amp;quot;true&amp;quot;
The same thing happen if the variable is changed in a
&amp;quot;for&amp;quot; block. It seems that variable handling is not
working if variable is declared in an inner block. I
don't believe that this is the required behaviour but
if it is it's not specified anywhere and does not make
any sense anyway.
Cheers,
Jean-Baptiste REURE \(jbreure@allette.com.au\)

Reported by: *anonymous

Original Ticket: "beanshell/bugs/141":https://sourceforge.net/p/beanshell/bugs/141

**Comment by opeongo** [comment]
Works as expected in current master bsh-3.0.0-SNAPSHOT
