### ISSUE TITLE
Capabilities.classExists() -- caching bug?

### ISSUE THREAD

**Issue by tm2git** [beanshell/beanshell#28]
Summary:  classes.put(c,"unused") should really be classes.put(name, "unused"), no?

In the  current bsh.Capabilities.classExists() code:

```java
	public static boolean classExists( String name ) 
	{
		Object c = classes.get( name );

		if ( c == null ) {
			try {
				/*
					Note: do *not* change this to 
					BshClassManager plainClassForName() or equivalent.
					This class must not touch any other bsh classes.
				*/
				c = Class.forName( name );
			} catch ( ClassNotFoundException e ) { }

			if ( c != null )
				classes.put(c,"unused");
		}

		return c != null;
	}
```

the cache key for the get() is the String name, but the cache key for the put() is the Class c.

Unless I'm missing something, this means that at present the classes Hashtable isn't helping at all.

**Comment by nickl-** [comment]
TODO: We need a unit test for this. see #72

**Comment by nickl-** [comment]
This is currently correctly referenced by name:

```java
    public static boolean classExists( String name )
    {
        Class<?> c = classes.get( name );

        if ( c == null ) {
            try {
                /*
                    Note: do *not* change this to
                    BshClassManager plainClassForName() or equivalent.
                    This class must not touch any other bsh classes.
                */
                c = Class.forName( name );
            } catch ( ClassNotFoundException e ) { }

        }
        classes.put(name, c);
        return c != null;
    }
```

But I think we can still improve on this.

**Comment by nickl-** [comment]
Now prevent additional class not found exceptions by checking if key exists instead.

https://github.com/beanshell/beanshell/blob/a8a1f5cb28caf9288dad5ce8922005807ecd6ea5/src/main/java/bsh/Capabilities.java#L96-L115

beanshell/beanshell@a8a1f5c also completes code coverage unit tests.
