### ISSUE TITLE
Beanshell 2.0b1 hangs on start

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#281]
The splash screen appears, but never disappears, and
the console window never appears. This happens
infrequently, and has been observed on both Linux and
Mac OS X with Java 1.4.1.

Reported by: redross

Original Ticket: "beanshell/bugs/143":https://sourceforge.net/p/beanshell/bugs/143

**Comment by opeongo** [comment]
Not reproducible under Windows 7 Pro 64, java version "11.0.1" 2018-10-16 LTS, current master bsh-3.0.0-SNAPSHOT

**Comment by nickl-** [comment]
Need to test on MacOS and Linux

**Comment by nickl-** [comment]
Tested on MacOS and Linux

**Closed: cannot reproduce**
