### ISSUE TITLE
source() should support an include path

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#282]
The source\(\) command \(and Interpreter.source\(\) as well\)
should support an include path. The include path should
have, at the very least, `.`, and the directory of the
including file.

\(I know about the sourceRelative\(\) command, but that's
very limited in functionality - what I was envisioning
was a `source` that would subsume the sourceRelative\(\)
functionality, and also allow the specification of
additional include paths..\)

Reported by: shankarunni

Original Ticket: "beanshell/bugs/144":https://sourceforge.net/p/beanshell/bugs/144

**Comment by opeongo** [comment]
This should be tagged as feature request and not a bug.

**Comment by nickl-** [comment]
@opeongo are you clear about what is expected here? 

I don't believe this is a parsing issue so am removing that.

Please add detailed instruction and tag issue as checked or else close it as lacking enough information.

**Comment by nickl-** [comment]
Still think this needs more information, marked checked for now but if details remain unclear then close would be preferred.
