### ISSUE TITLE
bsh.Interpreter.main arguments should be documented

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#285]
Document the fact that the args array passed to
bsh.Interpreter.main is
used as follows: args\[0\] is the name of a script file,
and args\[1-n\]
are placed in the context \(is that the right word\) as
bsh.args\[0-\(n-1\)\].

Also include similar information in the BeanShell Users
Manual under
the Standalone mode of operation.

Reported by: sdrach

Original Ticket: "beanshell/bugs/147":https://sourceforge.net/p/beanshell/bugs/147

**Comment by jimjag** [comment]
Incredibly old report

**Comment by nickl-** [comment]
This should be covered when documenting  Arrays 3.0 with Collections #89 
Closed: duplicate
