### ISSUE TITLE
java bsh.Remote bsh://... does not exit

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#287]
Background: bsh 2.0b1, Win 2000, JDK 1.4.2

The file is uploaded and executed correctly.  But, java
does not terminate.  I guess the client is waiting for
the server to close the socket.

Ben

Reported by: binhph

Original Ticket: "beanshell/bugs/149":https://sourceforge.net/p/beanshell/bugs/149

**Comment by opeongo** [comment]
I see that the code in Remote.java has been changed to use try-with-resources, so now the socket will be closed.

**Comment by nickl-** [comment]
Closed: Works as expected
