### ISSUE TITLE
Wrong ClassLoader consulted

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#288]
There's a bug in The the plainClassName method of the
bsh.classpath.ClassManagerImpl class.

The problem is, this method consults the context class
loader \*before\* it checks the user-specified
&amp;quot;externalClassLoader&amp;quot;.

Because of this, under JDK1.2 or above, no matter what
you specify to the setClassLoader method, it won't be
consulted.

Nowadays there are many applications \(such as Ant,
Maven\) that requires a rather sophisticated class
loading scheme that doesn't use the context class loader.

This bug makes it impossible to use bsh in such
context, and it defeats the purpose of the
setClassLoader method.

The proper look up order shoud be:

1\. externalClassLoader, if supplied.
2\. contextClassLoader, if available.
3\. Class.forName\(...\)

Reported by: kkawa

Original Ticket: "beanshell/bugs/150":https://sourceforge.net/p/beanshell/bugs/150

**Comment by nickl-** [comment]
The current order is:

For bsh.* classes 

1. Interpreter.class.getClassLoader
2. Class.forName

For the rest:

1. baseLoader
2. externalClassLoader
3. contextClassLoader
4. Class.forName
5. loadSourceClass

I believe that is what the OP was after with the addition of a baseLoader and loading from source java, the other loaders are in the desired order.

Closed: resolved
