### ISSUE TITLE
error in Reflect.resolveJavaMethod

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#289]
As the following comment says:

\-------------------------
```java
// Why do we do this?  Won't the overloaded resolution below find it
// just as well -- try to merge these next 

try {
    method = findAccessibleMethod(clas, name, types, onlyStatic);
} catch ( SecurityException e ) { }

if ( Interpreter.DEBUG &amp;&amp; method != null )
    Interpreter.debug("findAccessibleMethod found: "+ method );
```
-------------------------

The findAccessibleMethod call is unnecessary, and it is
causing a problem. If I have a class:
```java
class Foo {
    public void foo(Object o) {
        //...
    }
    private void foo(String a) {
        //...
    }
}
```

Then if I do fooObject.foo\(&amp;quot;abc&amp;quot;\) from beanshell, it
reports an error, saying the method is inaccessible.

Reported by: kkawa

Original Ticket: "beanshell/bugs/151":https://sourceforge.net/p/beanshell/bugs/151

**Comment by nickl-** [comment]
Well the method is private so it is inaccessible. Nothing BeanShell did it is all in your code. Just make the method public or alternatively just don't make it private and BeanShell will do the rest.

Not even going to test that, this is silly: closed
