### ISSUE TITLE
"Blank" final variable can not be initialized

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#290]
Background: bsh 2.0

With Java, the following is OK:

final int i;
i = 12;  //OK

With same above code, BSH will complain:
Variable assignment: i: Final variable, can't re-assign.

Ben

Reported by: binhph

Original Ticket: "beanshell/bugs/152":https://sourceforge.net/p/beanshell/bugs/152

**Comment by opeongo** [comment]
Works as expected in current master bsh-3.0.0-SNAPSHOT

**Comment by nickl-** [comment]
Closed: Works as expected
