### ISSUE TITLE
JConsole threading model causes BSH GUI to deadlock

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#293]
Sun java 1.4.2

Two pipe streams \[with limited buffers\] are used for 
communication between JConsole and Interpreter.
When Interpreter has something to print, it calls 
invokeAndWait\[in JConsole\], thus it's blocked until event 
thread will finish processing current event. It's possible 
for JConsole to try to feed some input to Interpreter at 
the same time and being blocked on a pipe stream \[since 
Interpreter does not read anything\], blocking event 
thread.

To reproduce, open BSH workspace window, type 'pr' 
and press TAB and ENTER many times. It looks like on 
some systems you'll run into another bug and won't be 
able to reproduce this one.

Reported by: *anonymous

Original Ticket: "beanshell/bugs/155":https://sourceforge.net/p/beanshell/bugs/155

**Comment by nickl-** [comment]
Duplicate #585
