### ISSUE TITLE
bsh.CallStack is not Serializable

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#294]
I'm running beanshell scripts over an RMI connection and 
I'm trying to return beanshell exceptions over the 
connection, but I can't. I get the following exception:

java.rmi.UnmarshalException: error unmarshalling return; 
nested exception is:
java.io.WriteAbortedException: writing aborted; 
java.io.NotSerializableException: bsh.CallStack
at sun.rmi.server.UnicastRef.invoke\(Unknown 
Source\)

After looking at the source, it seems a simple change to 
just implement the Serializable interface on the 
bsh.CallStack class. An oversite perhaps?

Reported by: frdfsnlght

Original Ticket: "beanshell/bugs/156":https://sourceforge.net/p/beanshell/bugs/156

**Comment by nickl-** [comment]
`CallStack` is serializable in BeanShell 3.0.0-SNAPSHOT.936

![Screenshot_20221208_235809](https://user-images.githubusercontent.com/1404606/206576294-3c6f7f03-6f72-439e-9fdc-c78b51ac91db.png)

Closed: is as expected
