### ISSUE TITLE
Parse error with valid input 2.0b1

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#295]
BSH fails to parse the following valid input:

x.equals\(new Cloneable\(\) \{ public Object foo\(\) \{
return null; \} \}\);

However, if you remove the "x.equals\(\)" or the "public
Object"
it parses fine. But if both are there, can't parse
that. Why?

Reported by: archiecobbs

Original Ticket: "beanshell/bugs/157":https://sourceforge.net/p/beanshell/bugs/157

**Comment by opeongo** [comment]
Works as expected, cannot reproduce.

**Comment by nickl-** [comment]
**Closed: Works as expected**
