### ISSUE TITLE
Parse error on valid string literal

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#299]
Version 1.3.0.

Could not parse string literal "\0\0\0\0\0\0\0\0". Here is 
short console dialog showing the problem:

```java
BeanShell 1.3.0 - by Pat Niemeyer \(pat@pat.net\)
bsh % "\0\0\0\0\0\0\0\0".hashCode();
// Error: Parser Error: Parse error at line 1, column 1 :
Error parsing string:
"\0\0\0\0\0\0\0\0"
bsh % "\000\000\000\000\000\000\000\000".hashCode();
<0>
```

Reported by: *anonymous

Original Ticket: "beanshell/bugs/161":https://sourceforge.net/p/beanshell/bugs/161

**Comment by nickl-** [comment]
BeanShell 3.0.0-SNAPSHOT.841 has your back

```java
bsh % "\0\0\0\0\0\0\0\0".hashCode();
--> $0 = 0I :int
bsh % "\000\000\000\000\000\000\000\000".hashCode();
--> $1 = 0I :int
```

Cannot reproduce, works as expected
