### ISSUE TITLE
Extending a non-static inner class fails

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#302]
When using BeanShell \(bsh-2.0b1.jar\) to extend a
non-static inner class, I get the following
exception/error:

/\*\* START ERROR \*\*/
cls.newInstance\(\) caught Exception : can't find
constructor for args\!
bsh.InterpreterError: can't find constructor for args\!
at
bsh.ClassGeneratorUtil.getConstructorArgs\(Unknown Source\)
at
beanshell.InnerClassExtension.&lt;init&gt;\(BeanShell
Generated via ASM \(www.objectweb.org\)\)
at
sun.reflect.NativeConstructorAccessorImpl.newInstance0\(Native
Method\)
at
sun.reflect.NativeConstructorAccessorImpl.newInstance\(NativeConstructorAccessorImpl.java:39\)
at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance\(DelegatingConstructorAccessorImpl.java:27\)
at
java.lang.reflect.Constructor.newInstance\(Constructor.java:274\)
at java.lang.Class.newInstance0\(Class.java:308\)
at java.lang.Class.newInstance\(Class.java:261\)
at
beanshell.InnerClassTest.getInnerClassExtension\(InnerClassTest.java:46\)
at
beanshell.InnerClassTest.testMethod\(InnerClassTest.java:21\)
at
beanshell.InnerClassTest.main\(InnerClassTest.java:84\)

/\*\* END ERROR \*\*/

This occurs when trying to get an instance of the Class
that is created by "Interpreter.eval\(...\)".  Changing
the inner class to "static" allows me to get an Object
from Class.newInstance\(\), and use it as a normal java
Object.

See the attached source code for the test code.

Thanks,
William Headrick \(headw01@fastmail.fm\)

Reported by: headw01

Original Ticket: "beanshell/bugs/164":https://sourceforge.net/p/beanshell/bugs/164

**Comment by nickl-** [comment]
I wish this proof was simpler or more forthcoming. The Test Code doesn't even compile in java, even after some tweaking its classpath is upside down. A simpler example of just the root cause would've been appreciated.

Not sure what to do about this.

The modified source that manages to build, but not run:

[InnerClassTest.java.txt](https://github.com/beanshell/beanshell/files/10201789/InnerClassTest.java.txt)

**Comment by nickl-** [comment]
Ok so I finally figured it out, they were trying to extend a non static innerclass via a scripted class, of course that is not going to work.
  
Here is the updated script:   [InnerClassTest.java.txt](https://github.com/beanshell/beanshell/files/10401152/InnerClassTest.java.txt)

Changes made to get it to work:
1. commented out the package declaration to make it simpler
2. changed LocalInnerClass to static
3. changed reflection constructor lookup to empty constructor

```java
ic = (LocalInnerClass)cls.getDeclaredConstructor(new Class<?>[0]).newInstance();
```

Compile and execute to receive the following output:

```
Test 0...
LocalInnerClass.innerClassMethod...
Test 1...
EVALUATED 1: class InnerClassExtension
evaled class 1: java.lang.Class
LocalInnerClass.innerClassMethod...
InnerClassExtension.innerClassMethod...
```

Closed: works if inner class is static

**Comment by nickl-** [comment]
Ok my bad I just saw the title we are trying to extend a non-static inner class.

For this to work the constructor needs to be correct as it should take the instance.

The updated script extending a non-static inner class: [InnerClassTest.java.txt](https://github.com/beanshell/beanshell/files/10401241/InnerClassTest.java.txt)

Changes made:
1. commented out the package declaration to make it simpler
2. changed scripted class constructor
3. changed reflection newInstance to take 1 argument

New scripted class with updated constructor:
```java
public class InnerClassExtension extends InnerClassTest.LocalInnerClass {
    public InnerClassExtension(InnerClassTest ict) {
        super(ict);
    }
    public void innerClassMethod() {
        super.innerClassMethod();
        print("InnerClassExtension.innerClassMethod...");
    }
}
```

Updated reflection call for new instance:
```java
ic = (LocalInnerClass)cls.getDeclaredConstructor(new Class<?>[] {InnerClassTest.class}).newInstance(this);
```

And the successful output:
```
Test 0...
LocalInnerClass.innerClassMethod...
Test 1...
EVALUATED 1: class InnerClassExtension
evaled class 1: java.lang.Class
LocalInnerClass.innerClassMethod...
InnerClassExtension.innerClassMethod...
```

Closed: works if using the correct constructor to extend a non-static inner class
