### ISSUE TITLE
Incorrect evaluation of if-else if-else statement

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#303]
bsh 1.2b7, bsh 2.0beta, and possibly all bsh versions
gave wrong result for the following:

a = 2;
if \(a == 1\)
;
else if \(a == 2\)
a = 22;
else
a = 33;

System.out.println \(a\); //print 2 instead of 22

To circumvent this bug, I use a dummy statement 
instead of an empty one. Example:

a = 2;
if \(a == 1\)
0;
else if \(a == 2\)
a = 22;
else
a = 33;

System.out.println \(a\); //print 22 which is correct

PS: By the way, when will the next version come
out? Thanks.

Ben

Reported by: binhph

Original Ticket: "beanshell/bugs/165":https://sourceforge.net/p/beanshell/bugs/165

**Comment by nickl-** [comment]
duplicate #342
