### ISSUE TITLE
Can't anonymous subclass with non-default constructor

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#304]
This should work but it doesn't:

bsh % x = new
java.io.FilterOutputStream\(this.interpreter.out\) \{ \} ;
// Error: EvalError: Error constructing inner class
instance: bsh.ReflectError: Can't find constructor:
global$4\( java.io.PrintStream \) in class: global$4 : at
Line: 1 : in file: &lt;unknown file&gt; : new java .io
.FilterOutputStream \( this .interpreter .out \) \{ 

The problem seems to be that BSH can't handle an
anonymous inner subclass when the superclass
constructor takes any parameters.

It appears to be looking for the constructor in the
inner subclass rather than the superclass.

Reported by: archiecobbs

Original Ticket: "beanshell/bugs/166":https://sourceforge.net/p/beanshell/bugs/166

**Comment by nickl-** [comment]
Seems to work in BeanShell 3.0.0-SNAPSHOT.936

```java
bsh % x = new java.io.FilterOutputStream(this.interpreter.out) { } ;
--> $0 = global$anon1@7907ec20 :global$anon1
```

Closed: cannot reproduce
