### ISSUE TITLE
null String does not print null 

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#306]
String s; s=null; System.out.println\(s\);
does not print null, but gives NullPointerException instead

Reported by: *anonymous

Original Ticket: "beanshell/bugs/168":https://sourceforge.net/p/beanshell/bugs/168

**Comment by nickl-** [comment]
Works in BeanShell 3.0.0-SNAPSHOT.857

actually outputs a lot of nulls
```java
bsh % String s; s=null; System.out.println(s);
--> $0 = null :null
--> $1 = null :null
null
--> void
bsh %
```

**Comment by nickl-** [comment]
> This is caused by bug #213066. It ends up invoking System.out.println(char[]) rather than the expected System.out.println(Object), because null could match either of those methods and the wrong one is selected.
> 
Not sure what exactly `#213066` refers to but method negotiation was given a lot of attention as well.

**Comment by nickl-** [comment]
Closed works as expected
