### ISSUE TITLE
"loose type" problem with float

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#307]
float e=3.14; System.out.println\(e+1\);
seems to be OK but should give a
"possible loss of precision" error, at 
least with "strict Java"

Reported by: *anonymous

Original Ticket: "beanshell/bugs/169":https://sourceforge.net/p/beanshell/bugs/169

**Comment by nickl-** [comment]
**Closed: Fixed as per #71**
