### ISSUE TITLE
which does not work properly

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#309]
The which command seems broken. Looking at the code 
in which.bsh :

which\( clas \) 
\{
// make the class into a name
Class clas;
if \( clas instanceof ClassIdentifier \)
etc...

it's clear that the clas variable shadows the parameter 
with the same name. Removing the local variable seems 
to solve the problem.

Reported by: maxtardiveau

Original Ticket: "beanshell/bugs/171":https://sourceforge.net/p/beanshell/bugs/171

**Comment by jimjag** [comment]
Can't reproduce. No info. Stale
