### ISSUE TITLE
Please provide ability to switch on enums

### ISSUE THREAD

**Issue by davidekholm** [beanshell/beanshell#31]
Please provide ability to switch on enums as that's supported in Java since Java 5.

**Comment by nickl-** [comment]
This first requires enum support, currently enum still gives parser error... then we can look into switching enums.

```
bsh % enum Name { VAL }
// Error: Parser Error: In file: <unknown> Encountered  "enum" enum  at line 2, column 1.
```

**Comment by nickl-** [comment]
Enum support implemented including the ability to switch on enum

nJoy!

**Comment by davidekholm** [comment]
Awesome! Thanks Nickl

**Comment by nickl-** [comment]
@davidekholm yw =)
