### ISSUE TITLE
Invoking a method with null args fails if Interpreter.DEBUG

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#311]
A NullPointerException occurs if you invoke a method
\(for example a static method\) with an argument with
null value, this problem only occurs if
Interpreter.DEBUG is enabled.

The problem is in the class bsh.Reflect \(line 143\):

```java
Interpreter.debug( "tmpArgs["+i+"] = "+tmpArgs[i]+" type = " + tmpArgs[i].getClass());
```
I solved this problem making the following modification:
```java
Interpreter.debug("tmpArgs["+i+"] = "+tmpArgs[i]+" type = " + (tmpArgs[i] == null ?"NULL" : tmpArgs[i].getClass().getName()));
```

I believe the solution is good, so please commit this
change or a similar solution.

Thanks

Reported by: mrostan

Original Ticket: "beanshell/bugs/173":https://sourceforge.net/p/beanshell/bugs/173

**Comment by nickl-** [comment]
What are `tmpArgs`? Where is the static method called with null?

I get:
```java
bsh % Interpreter.debug( "tmpArgs["+i+"] = "+tmpArgs[i]+" type = " + tmpArgs[i].getClass());
// Error: Evaluation Error: illegal use of undefined variable, class, or 'void' literal : at Line: 3 : in file: <unknown file> : + "] = " + tmpArgs [ i ] + " type = " + tmpArgs [ i ].getClass ( ) ) ;
```

Which is to be expected.

Closed: not enough information
