### ISSUE TITLE
2.0b1 invoke(name,args) not used when method def missing

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#315]
Using invoke\( name, args \) as a catch-all for methods
that one has not implemented for an interface does not
work in some cases.

Windows XP Pro/
Java HotSpot\(TM\) Client VM \(build 1.4.2\_02-b03, mixed mode\)

See attached file - a script to duplicate the error.

The error received was:

Called from method: test : at Line: 39 : in file:
test1.bsh : test \( m2 \) 
Target exception: bsh.InterpreterError: null variable value

bsh.InterpreterError: null variable value

at bsh.NameSpace.setVariable\(Unknown Source\)

at bsh.NameSpace.setLocalVariable\(Unknown Source\)

at bsh.BshMethod.invokeImpl\(Unknown Source\)

at bsh.BshMethod.invoke\(Unknown Source\)

at bsh.BshMethod.invoke\(Unknown Source\)

at bsh.This.invokeMethod\(Unknown Source\)

at bsh.This.invokeMethod\(Unknown Source\)

at bsh.XThis$Handler.invokeImpl\(Unknown Source\)

at bsh.XThis$Handler.invoke\(Unknown Source\)

at $Proxy6.getB\(Unknown Source\)

email: m\_sample at canada.com

Reported by: *anonymous

Original Ticket: "beanshell/bugs/177":https://sourceforge.net/p/beanshell/bugs/177

**Comment by opeongo** [comment]
Here is the sample code from Sourceforge (slightly modified).
```java

public interface MyIntf {
    String getA();
    int getB();
} 

public class MyImpl implements MyIntf {
    public String getA() { 
        return "MyImpl A value";
    }

    public invoke( name, args ) { 
        print ("MyImpl.invoke() called with name/args: " + name + " / " + args ); 
        return 10; 
    }
}
```
I think the issue is that the invoke method only works magically in scriped objects, not in java-style class definitions.  So I would not expect the above to work.

```java
void test( MyIntf m ) {
   print("MyIntf.getA() == " + m.getA() );
   print("MyIntf.getB() == " + m.getB() );
}

String getA() { 
    return "Global A value"; 
}

invoke( name, args ) { 
    print ("Global invoke() called with name/args: " + name + " / " + args );
    return 10; 
}


MyIntf m1 = ( MyIntf) new MyImpl();

MyIntf m2 = ( MyIntf) this;

print("Testing  cast of MyImpl to MyIntf, where MyIntf relies on invoke() to provide getB()");
test( m1 );

print("Testing cast of 'this' to interface, where 'this' relies on invoke() to provide getB()");
test( m2 );
```
Wow, I never would have though to code something that way.  I sortof expected the 'm2' example to work.  Instead it fails with:
```
Testing cast of 'this' to interface, where 'this' relies on invoke() to provide getB()
// Error: Target Exception: Method Invocation this.interpreter.source : at Line: 14 : in file: /bsh/commands/source.bsh : this .interpreter .source ( filename , this .caller .namespace ) 

Called from method: source : at Line: 1 : in file: <unknown file> : source ( "test1.bsh" ) Caused by: java.lang.StackOverflowError
```
I am guessing that this is because the invoke method is defined in the Interpreter object, and not inside a scripted object that gets generated in to a class along with the invoke magic.

Still, the StackOverFlowError seems a bit odd.

**Comment by nickl-** [comment]
I need to look into this deeper but at a quick glance...

The "magic" invoke takes `Interpreter env, CallStack callstack` not `String name, Object[] args` afaik but I might be completely off the mark.

The `dir` command should serve as a working example.

https://github.com/beanshell/beanshell/blob/0ad109fb38beec022adc88035d931f9a71137f8f/src/main/java/bsh/commands/dir.java#L57-L61

**Comment by nickl-** [comment]
This is a duplicate of #347 reporting the same exception.

Minimum required for unit test:

```java
public interface MyIntf {
    int getB();
}

public class MyImpl implements MyIntf {
    public invoke( name, args ) { 
        print ("MyImpl.invoke() called with name/args: " + name + " / " + args ); 
        return 10; 
    }
}

MyIntf m1 = ( MyIntf) new MyImpl();

m1.getB(); // should print MyImpl.invoke...

invoke( name, args ) {
    print ("Global invoke() called with name/args: " + name + " / " + args );
    return 10;
}

MyIntf m2 = ( MyIntf) this;

m2.getB(); // should print Global invoke...
```
Nothing special here, even the cast global works as tested and new issues will be dealt with at #667.

Closed: duplicate
