### ISSUE TITLE
Illegal static sections support

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#318]
This code is absolutely leggal from java's point of view, 
but it doesn't work in BeanShell:
Mapper.java:

import java.util.\*;

class Mapper \{
static HashMap mapping = new HashMap\(\);
static \{
mapping.put\("a","a"\);
\}
public static get\(String name\) \{
return \(String\)mapper.get\(name\);
\}
\}

Test.bsh:
source\("Mapper.java"\);
print\(Mapper.get\("a"\)\);

and report following problem:
Target exception: Parse error at line 5, column 3.  
Encountered: static

Reported by: *anonymous

Original Ticket: "beanshell/bugs/180":https://sourceforge.net/p/beanshell/bugs/180

**Comment by nickl-** [comment]
Had to fix the source, the get method must return from mapping field and not mapper which does not exist.
[Mapper.java.txt](https://github.com/beanshell/beanshell/files/10147960/Mapper.java.txt)

Then it all works like a charm:

```java
bsh % source("Mapper.java");
--> $2 = class Mapper :Class
bsh % Mapper.get("a");
--> $3 = "a" :String
```

Closed: works as expected
