### ISSUE TITLE
order of import qualifiers

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#321]
Java's 1.5 release notes describe static import using an example of 
the form, for which BeanShell reports a parse error:

```java
import static java.lang.Math.*;
```
BeanShell only accepts the following:
```java
static import java.lang.Math.*;
```

Reported by: twall

Original Ticket: "beanshell/bugs/183":https://sourceforge.net/p/beanshell/bugs/183

**Comment by nickl-** [comment]
This is working in BeanShell 3.0.0-SNAPSHOT.841

```java
bsh % import static java.lang.Math.*;
--> void
bsh % max(1,2);
--> $5 = 2I :int
bsh % pow(2,2);
--> $6 = 4.0d :double
```

Plus the incorrect order `static import` will not parse.

```java
bsh % static import java.lang.Math.*;
// Error: Parser Error: Unable to parse code syntax. Encountered: static import at line 1, column 1
bsh % // Error: Parser Error: Unable to parse code syntax. Encountered: . * at line 1, column 15
```

Cannot reproduce, works as expected.
