### ISSUE TITLE
EvalError must be Serializable

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#323]
Exceptions must be Serializable so they can be passed
via RMI. EvalError is not \(as the embedded CallStack is
not\), thus an EvalError cannot be passed from a server
evaluating a bsh script to a J2EE client. This results
in a StackTrace like this \(the original exception gets
lost\):

\[java\] Caused by: java.rmi.UnmarshalException:
Error unmarshaling return; nested exception is:
\[java\]     java.io.WriteAbortedException: writing
aborted; java.io.NotSerializableException: bsh.CallStack
\[java\]     at
sun.rmi.transport.StreamRemoteCall.executeCall\(StreamRemoteCall.java:217\)
\[java\]     at
sun.rmi.server.UnicastRef.invoke\(UnicastRef.java:133\)
\[java\]     at
org.jboss.invocation.jrmp.server.JRMPInvoker\_Stub.invoke\(Unknown
Source\)
\[java\]     at
org.jboss.invocation.jrmp.interfaces.JRMPInvokerProxy.invoke\(JRMPInvokerProxy.java:140\)
\[java\]     at
org.jboss.invocation.InvokerInterceptor.invoke\(InvokerInterceptor.java:108\)
\[java\]     at
org.jboss.proxy.TransactionInterceptor.invoke\(TransactionInterceptor.java:77\)
\[java\]     at
org.jboss.proxy.SecurityInterceptor.invoke\(SecurityInterceptor.java:80\)
\[java\]     at
org.jboss.proxy.ejb.StatelessSessionInterceptor.invoke\(StatelessSessionInterceptor.java:111\)
\[java\]     at
org.jboss.proxy.ClientContainer.invoke\(ClientContainer.java:76\)
\[java\]     at $Proxy13.create\(Unknown Source\)
\[java\]     at
de.novabit.elisa.client.leasedobject.LeasedObjectDelegate.create\(LeasedObjectDelegate.java:187\)
\[java\]     ... 39 more
\[java\] Caused by: java.io.WriteAbortedException:
writing aborted; java.io.NotSerializableException:
bsh.CallStack
\[java\]     at
java.io.ObjectInputStream.readObject0\(ObjectInputStream.java:1278\)
\[java\]     at
java.io.ObjectInputStream.defaultReadFields\(ObjectInputStream.java:1845\)
\[java\]     at
java.io.ObjectInputStream.readSerialData\(ObjectInputStream.java:1769\)
\[java\]     at
java.io.ObjectInputStream.readOrdinaryObject\(ObjectInputStream.java:1646\)
\[java\]     at
java.io.ObjectInputStream.readObject0\(ObjectInputStream.java:1274\)
\[java\]     at
java.io.ObjectInputStream.defaultReadFields\(ObjectInputStream.java:1845\)
\[java\]     at
java.io.ObjectInputStream.readSerialData\(ObjectInputStream.java:1769\)
\[java\]     at
java.io.ObjectInputStream.readOrdinaryObject\(ObjectInputStream.java:1646\)
\[java\]     at
java.io.ObjectInputStream.readObject0\(ObjectInputStream.java:1274\)
\[java\]     at
java.io.ObjectInputStream.defaultReadFields\(ObjectInputStream.java:1845\)
\[java\]     at
java.io.ObjectInputStream.readSerialData\(ObjectInputStream.java:1769\)
\[java\]     at
java.io.ObjectInputStream.readOrdinaryObject\(ObjectInputStream.java:1646\)
\[java\]     at
java.io.ObjectInputStream.readObject0\(ObjectInputStream.java:1274\)
\[java\]     at
java.io.ObjectInputStream.defaultReadFields\(ObjectInputStream.java:1845\)
\[java\]     at
java.io.ObjectInputStream.readSerialData\(ObjectInputStream.java:1769\)
\[java\]     at
java.io.ObjectInputStream.readOrdinaryObject\(ObjectInputStream.java:1646\)
\[java\]     at
java.io.ObjectInputStream.readObject0\(ObjectInputStream.java:1274\)
\[java\]     at
java.io.ObjectInputStream.readObject\(ObjectInputStream.java:324\)
\[java\]     at
sun.rmi.transport.StreamRemoteCall.executeCall\(StreamRemoteCall.java:215\)
\[java\]     ... 49 more
\[java\] Caused by:
java.io.NotSerializableException: bsh.CallStack
\[java\]     at
java.io.ObjectOutputStream.writeObject0\(ObjectOutputStream.java:1054\)
\[java\]     at
java.io.ObjectOutputStream.defaultWriteFields\(ObjectOutputStream.java:1332\)
\[java\]     at
java.io.ObjectOutputStream.writeSerialData\(ObjectOutputStream.java:1304\)
\[java\]     at
java.io.ObjectOutputStream.writeOrdinaryObject\(ObjectOutputStream.java:1247\)
\[java\]     at
java.io.ObjectOutputStream.writeObject0\(ObjectOutputStream.java:1052\)
\[java\]     at
java.io.ObjectOutputStream.defaultWriteFields\(ObjectOutputStream.java:1332\)
\[java\]     at
java.io.ObjectOutputStream.defaultWriteObject\(ObjectOutputStream.java:367\)
\[java\]     at
java.lang.Throwable.writeObject\(Throwable.java:648\)
\[java\]     at
sun.reflect.NativeMethodAccessorImpl.invoke0\(Native Method\)
\[java\]     at
sun.reflect.NativeMethodAccessorImpl.invoke\(NativeMethodAccessorImpl.java:39\)
\[java\]     at
sun.reflect.DelegatingMethodAccessorImpl.invoke\(DelegatingMethodAccessorImpl.java:25\)
\[java\]     at
java.lang.reflect.Method.invoke\(Method.java:324\)
\[java\]     at
java.io.ObjectStreamClass.invokeWriteObject\(ObjectStreamClass.java:809\)
\[java\]     at
java.io.ObjectOutputStream.writeSerialData\(ObjectOutputStream.java:1296\)
\[java\]     at
java.io.ObjectOutputStream.writeOrdinaryObject\(ObjectOutputStream.java:1247\)
\[java\]     at
java.io.ObjectOutputStream.writeObject0\(ObjectOutputStream.java:1052\)
\[java\]     at
java.io.ObjectOutputStream.defaultWriteFields\(ObjectOutputStream.java:1332\)
\[java\]     at
java.io.ObjectOutputStream.writeSerialData\(ObjectOutputStream.java:1304\)
\[java\]     at
java.io.ObjectOutputStream.writeOrdinaryObject\(ObjectOutputStream.java:1247\)
\[java\]     at
java.io.ObjectOutputStream.writeObject0\(ObjectOutputStream.java:1052\)
\[java\]     at
java.io.ObjectOutputStream.defaultWriteFields\(ObjectOutputStream.java:1332\)
\[java\]     at
java.io.ObjectOutputStream.writeSerialData\(ObjectOutputStream.java:1304\)
\[java\]     at
java.io.ObjectOutputStream.writeOrdinaryObject\(ObjectOutputStream.java:1247\)
\[java\]     at
java.io.ObjectOutputStream.writeObject0\(ObjectOutputStream.java:1052\)
\[java\]     at
java.io.ObjectOutputStream.writeObject\(ObjectOutputStream.java:278\)
\[java\]     at
sun.rmi.server.UnicastServerRef.dispatch\(UnicastServerRef.java:299\)
\[java\]     at
sun.rmi.transport.Transport$1.run\(Transport.java:148\)
\[java\]     at
java.security.AccessController.doPrivileged\(Native Method\)
\[java\]     at
sun.rmi.transport.Transport.serviceCall\(Transport.java:144\)
\[java\]     at
sun.rmi.transport.tcp.TCPTransport.handleMessages\(TCPTransport.java:460\)
\[java\]     at
sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run\(TCPTransport.java:701\)
\[java\]     at java.lang.Thread.run\(Thread.java:534\)

Reported by: *anonymous

Original Ticket: "beanshell/bugs/185":https://sourceforge.net/p/beanshell/bugs/185

**Comment by nickl-** [comment]
CallStack is Serializable in 3.0.0-SNAPSHOT.841:

```java
public final class CallStack implements Serializable {
    // snip implementation
}
```
Closed: resolved
