### ISSUE TITLE
JConsole freezes when pasting in multiple statements

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#324]
\(First of all, I have recently discovered a workaround,
which is to surround the statements with \{curly braces\}\).

For many multi-line scripts, JConsole freezes; for some
others, it doesn't. This is bad because the GUI for the
app in which the console is running also freezes.

Example script demonstrating the problem:

import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;
import java.lang.String;

Reported by: jonathanaquino

Original Ticket: "beanshell/bugs/186":https://sourceforge.net/p/beanshell/bugs/186

**Comment by nickl-** [comment]
Closed: duplicate #585
