### ISSUE TITLE
JAlbum +Tomcat + Solaris 8: Errors launching from bash. 

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#328]
Running JAlbum libraries, we have got the following
exception related with BeanShell libraries: 

We hace developed a web application which uses JAlbum
library to generate a Photo Album. This application is
deployed in Tomcat \(4.1.30\) JSP/Servlet Container in a
Solaris 8 OS.

We first had problems with the graphics libraries.
Launching Tomcat from a graphic enviroment \(CDE\), the
web application works fine, and the photo album is
generated.

If we launch Tomcat, from a console terminal, we had
the graphics problem which is already documented in
this forum, so we added the -Djava.awt.headless=true
option to the Tomcat Launcher \(catalina.sh\).

We got the following error:

java.lang.NoClassDefFoundError: bsh/Variable
at bsh.NameSpace.setVariable\(Unknown Source\)
at bsh.NameSpace.setVariable\(Unknown Source\)
at bsh.Interpreter.set\(Unknown Source\)
at bsh.Interpreter.setu\(Unknown Source\)
at bsh.Interpreter.initRootSystemObject\(Unknown Source\)
at bsh.Interpreter.&lt;init&gt;\(Unknown Source\)
at bsh.Interpreter.&lt;init&gt;\(Unknown Source\)
at bsh.Interpreter.&lt;init&gt;\(Unknown Source\)
at
se.datadosen.jalbum.AlbumBean.initInterpreter\(AlbumBean.java:81\)
at se.datadosen.jalbum.AlbumBean.&lt;init&gt;\(AlbumBean.java:77\)

...
...

If we launch stop Tomcat and re-launch it from a sh
interpreter, the album is generated correctly. And also
if we change once again the interpreter from sh to
bash, this time the album is generated correctly. \(It
just fails the first time, if we use bash to startup
Tomcat\).

Maybe it has nothing to do with JAlbum libraries but
Sun Java libraries on solaris. We are quite surprised
with this behaviour.

żAny idea? Any help would be appreciated.

Thanks in advance. 

Reported by: *anonymous

Original Ticket: "beanshell/bugs/190":https://sourceforge.net/p/beanshell/bugs/190

**Comment by nickl-** [comment]
> żAny idea? Any help would be appreciated.

No idea and support on migrated issues are pointless.

Closed: stale
