### ISSUE TITLE
How to enter beanshell inside felix or karaf

### ISSUE THREAD

**Issue by dynamodan** [beanshell/beanshell#33]
How can the beanshell console be entered into from inside of karaf or felix?  I installed the bundle and it shows when I do bundle:list inside karaf, but I don't know what to do from there, to get a beanshell prompt.  Are there some integration tutorials anywhere?

**Comment by opeongo** [comment]
If you can modify the source code to your application the official BeanShell documentation describes how to do it: http://beanshell.org/manual/embeddedmode.html#Embedding_BeanShell_in_Your_Application

If you can't modify your source code then BeanShell also supports the Java Scripting API (JSR 223):
https://docs.oracle.com/javase/8/docs/technotes/guides/scripting/prog_guide/api.html

**Comment by nickl-** [comment]
Closed: Question answered by @opeongo 

@dynamodan if you still have a problem please open a new issue.

**Comment by dynamodan** [comment]
Please reopen this case.  I know how to modify *my* application (which is a non-karaf hack job), and I have done it.  My question was "How can the beanshell console be entered into *from inside of karaf or felix*" ?  What I was looking for was any help or resources *specific to karaf.* and specific to a console. I'm aware of the JSR 223 scripting api, but that isn't one and the same as entering a console where you type something in and get a response.  This is usually referred to as a CLI (command line interface) or a REPL (read-eval-print-loop).

**Comment by stefanofornari** [comment]
Hi Dynamo,
we are more familiar with beanshell itself, maybe you can find more helpful
hints from karaf/felix community?

Ste
