### ISSUE TITLE
"static field imports not supported yet"

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#331]
In 2.0b2 this statement fails:

bsh % static import Float.NaN;
// Error: EvalError: static field imports not supported
yet : at Line: 4 : in file: &lt;unknown file&gt; : static
import Float .NaN ;

However, the statement

bsh % static import Float.\*;

runs without problem, and imports also fields, which
can be checked easily by issuing the statement

bsh % print\(NaN\);
NaN

Reported by: *anonymous

Original Ticket: "beanshell/bugs/193":https://sourceforge.net/p/beanshell/bugs/193

**Comment by nickl-** [comment]
Use `import static` instead

```java
bsh % import static java.lang.Float.*;
--> void
bsh % print(NaN);
NaNf :float
--> void
```

Closed: works as implemented.
