### ISSUE TITLE
Bitwise operators do not work with booleans

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#336]
Bitwise operators work fine with 0 or 1 but not with
true or false, and fail with the error message: "Error:
Internal Error: unimplemented binary operator".

Using Java 1.5.0 and bsh-2.0b2.jar

Reported by: *anonymous

Original Ticket: "beanshell/bugs/198":https://sourceforge.net/p/beanshell/bugs/198

**Comment by nickl-** [comment]
Appears to work as expected in 3.0.0-SNAPSHOT.857

```java
bsh % true & false;
--> $1 = false :boolean
bsh % true ^ false;
--> $2 = true :boolean
bsh % true | false;
--> $3 = true :boolean
```

Closed: resolved
