### ISSUE TITLE
a fix for a bug in JConsole

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#339]
more details of the bug and how to fix it is provided at: 

http://sourceforge.net/tracker/index.php?func=detail&aid=935020&group_id=4075&atid=304075

Reported by: barak_naveh

Original Ticket: "beanshell/bugs/201":https://sourceforge.net/p/beanshell/bugs/201

**Comment by nickl-** [comment]
> more details of the bug and how to fix it is provided at:
> 
> http://sourceforge.net/tracker/index.php?func=detail&aid=935020&group_id=4075&atid=304075

Refers to #110 

Closed duplicate
