### ISSUE TITLE
importing static nested classes

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#340]
Greetings,

I've discovered a bug in BeanShell's import mechanism.
I couldn't find this bug in the bug database, I apologize
if it's been submitted before...

The JLS \(2nd edition\) allows an import statement to import
static nested classes declared in a top-level class.

In 7.5.2, the production preceeding the '.\*' notation
can be a
PackageOrTypeName, and the text says:
"A type-import-on-demand declaration allows all
accesible
types declared IN THE TYPE or package named by a
canonical
name to be imported as needed" \[emphasis mine\]

Both Jikes and Javac support this.

Note: This is NOT a new JDK 1.5 feature.

Example:

If you have a class as follows:

```java
package com.funpeople;
public class Person {
    public static String Arm() { return "Forearm"; }
}
```

In another file, you can do this:

import com.funpeople.Person.\*;
...
new Arm \(\)
...

This pattern is useful, particularly when you have a bunch
of public utility classes that you don't want to create
top-level
java files for, and that you don't want to qualify
constantly at
use point. \(it's one of the few ways you can create
multiple
public classes in a single file in Java\)

BeanShell's import mechanism doesn't work in this case
\(if you do a .\* import, BeanShell assumes that it is a
package
name, and never looks for an nested / inner class\).

I worked around this in my application by installing a
custom
BshClassHandler, which I could provide if it would help.

If you have any questions, please email me.

Thanks very much for your time,
-Shawn Vincent.

\--
svincent@svincent.com
http://www.svincent.com/

Reported by: *anonymous

Original Ticket: "beanshell/bugs/202":https://sourceforge.net/p/beanshell/bugs/202

**Comment by nickl-** [comment]
Using `import static` instead works as expected

```java
bsh % package com.funpeople;
public class Person {
    public static String Arm() { return "Forearm"; }
}--> void
bsh % import static com.funpeople.Person.*;
--> void
bsh % Arm();
--> $1 = "Forearm" :String
```

Closed: works as implemented
