### ISSUE TITLE
Can't access Map entires as bean properties

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#341]
Code:

Interpreter i = new Interpreter\(\);
Map bean = new HashMap\(\);
bean.put\("id", "798976"\);
i.set\("emp", new HashMap\(\)\);
System.err.println\(i.eval\("import emp; emp.id"\)\);

Results in an error:

Sourced file: inline evaluation of: \`\`import emp; 
emp.id;'' : Cannot access field: id, on object: \{\} : at 
Line: 1 : in file: inline evaluation of: \`\`import emp; 
emp.id;'' : emp .id 

at bsh.UtilEvalError.toEvalError\(Unknown 
Source\)
at bsh.UtilEvalError.toEvalError\(Unknown 
Source\)
at bsh.BSHAmbiguousName.toObject\(Unknown 
Source\)
at bsh.BSHAmbiguousName.toObject\(Unknown 
Source\)
at bsh.BSHPrimaryExpression.eval\(Unknown 
Source\)
at bsh.BSHPrimaryExpression.eval\(Unknown 
Source\)
at bsh.Interpreter.eval\(Unknown Source\)
at bsh.Interpreter.eval\(Unknown Source\)
at bsh.Interpreter.eval\(Unknown Source\)
at edu.ucsd.som.reports.Main.main
\(Main.java:47\)
at 
sun.reflect.NativeMethodAccessorImpl.invoke0\(Native 
Method\)
at sun.reflect.NativeMethodAccessorImpl.invoke
\(NativeMethodAccessorImpl.java:39\)
at 
sun.reflect.DelegatingMethodAccessorImpl.invoke
\(DelegatingMethodAccessorImpl.java:25\)
at java.lang.reflect.Method.invoke
\(Method.java:324\)
at 
com.intellij.rt.execution.application.AppMain.main
\(AppMain.java:78\)

Reported by: *anonymous

Original Ticket: "beanshell/bugs/203":https://sourceforge.net/p/beanshell/bugs/203

**Comment by nickl-** [comment]
Well there is a problem, you are setting `emp` to an empty `HashMap` instead of the populated bean variable.

Not to worry 3.0.0-SNAPSHOT.841 is your friend.

```java
bsh % Interpreter i = new Interpreter();
Map bean = new HashMap();
bean.put("id", "798976");
i.set("emp", new HashMap());
System.err.println(i.eval("import emp; emp.id"));--> $1 = bsh.Interpreter@6108b2d7 :bsh.Interpreter
bsh % --> $2 = {} :Map
bsh % --> $3 = null :null
bsh % --> void
bsh %
null
--> void
```
But this is probably what we wanted, right?

```java
bsh % i.set("emp", bean);
--> void
bsh % System.err.println(i.eval("import emp; emp.id"));
798976
--> void
bsh % bean.id
--> $4 = "798976" :String
```

Closed cannot reproduce, works as expected.
