### ISSUE TITLE
Comparing Strings dependant on how they are instantiated

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#343]
```java
class T1{
    public static void main (String[] args){
        String s0 = "Nigel is best";
        String s1 = "Nigel"+" is best";
        if(s0 == s1) System.out.println(s0);
        else System.out.println(s1+" not");
    }
}
```
Running the above class in BeanShell produces:
\[nigel@localhost temp\]
$ /home/java/j2re1.4.2\_02/bin/java -classpath ../../bsh-
2.0b1.jar bsh.Interpreter t1.java 
Nigel is best not

Compiling it and running it with java produces the 
preferred:
\[nigel@localhost temp\]$ javac t1.java               
\[nigel@localhost temp\]
$ /home/java/j2re1.4.2\_02/bin/java t1
Nigel is best

Reported by: nigel_galloway

Original Ticket: "beanshell/bugs/205":https://sourceforge.net/p/beanshell/bugs/205

**Comment by nickl-** [comment]
Can reproduce:

```java
bsh % T1.main(new String[0]);
Nigel is best not
--> void
```

**Comment by nickl-** [comment]
Resolved:
```java
BeanShell 3.0.0-SNAPSHOT.4043
class T1{
    public static void main (String[] args){
        String s0 = "Nigel is best";
        String s1 = "Nigel"+" is best";
        if(s0 == s1) System.out.println(s0);
        else System.out.println(s1+" not");
    }
}
--> $0 = class T1 :Class
T1.main({""});
Nigel is best
--> void
```

Turns out [intern](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#intern--) was missing from the `PLUS` operators implementation.
