### ISSUE TITLE
Impossible to eval. class with a nested class?

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#344]
It seems that BeanShell is not able to evaluate the
following code:

```java
class Impossible2EvaluateByBeanshell {
    // Causes internal Error: Attempting to load class in the
    // process of being defined

    public static void iWillFail( java.io.File dir )
            throws MyInnerClassException {}

    static class MyInnerClassException extends Exception {}
}
```

It seems to be related to the fact that I use a nested
class of the class being defined. But I believe it
should be able to evaluate such a class. Maybe
BeanShell is trying to evaluate all at once i.e.
doesn't finish evaluating the nested class before it
goes on with the method iWillFail.
Thus I guess this is a bug. 

Thanks for any help with that\!

/Kuba

Reported by: malyvelky

Original Ticket: "beanshell/bugs/206":https://sourceforge.net/p/beanshell/bugs/206

**Comment by nickl-** [comment]
Inner classes implemented in 3.0.0-SNAPSHOT.841

```java
bsh % Impossible2EvaluateByBeanshell.iWillFail(new File("t.txt"));
--> void
```

Closed cannot reproduce, works as expected.
