### ISSUE TITLE
Cannot stop server threads

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#345]
After starting server threads with server\(\) command
there is no way to stop them. Issuing interrupt\(\) will
not suffice as serversocket.accept\(\) will not be
interrupted.

Reported by: tawek

Original Ticket: "beanshell/bugs/207":https://sourceforge.net/p/beanshell/bugs/207

**Comment by nickl-** [comment]
The Interpreter process now considers `Thread.interrupted` which should allow termination.

```java
    public void run() {
        if ( evalOnly )
            throw new RuntimeException("bsh Interpreter: No stream");

        // init the callstack.
        CallStack callstack = new CallStack(globalNameSpace);

        Node node = null;
        EOF = false;
        int idx = -1;
        while( !Thread.interrupted() && !EOF ) {
            try {
                if ( interactive )
                    console.prompt(getBshPrompt());

                EOF = readLine();

```

Closed: resolved
