### ISSUE TITLE
Locks up when pasting more than four lines of code.

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#346]
BeanShell locks up and is unresponsive whenever more
than a few  lines of code are pasted into the workspace
console.  Depending on the environment, this effect can
show up with as few as three lines.  Clicking on the
window close button usually has no effect and BeanShell
has to be killed.

This occurs in version 2.0b1 and 2.0b2, but is not a
problem in 1.2b6.  The issue occurs on both Mac OS X
and Windows 2000 using Java 1.4.2.

To recreate this bug, paste the following 12 lines into
a workspace console:

show\(\);
USER\_HOME = System.getProperty\("user.home"\);
addClassPath\(USER\_HOME + "/src/java"\);
addClassPath\(USER\_HOME + "/src/test"\);
addClassPath\(USER\_HOME + "/lib/junit.jar"\);
addClassPath\(USER\_HOME + "/lib/ant.jar"\);
addClassPath\(USER\_HOME + "/lib/mockobjects-core-0.09.jar"\);
addClassPath\(USER\_HOME +
"/lib/mockobjects-jdk1.4-0.09.jar"\);
addClassPath\(USER\_HOME + "/lib/ant.jar"\);
addClassPath\(USER\_HOME + "/build/WEB-INF/classes"\);
addClassPath\(USER\_HOME +
"/build/WEB-INF/lib/webmacro.jar"\);
addClassPath\(USER\_HOME +
"/build/WEB-INF/lib/log4j-1.2.8.jar"\);

I know this is more than three or four lines, but I
wanted a demo that's guaranteed to lock up BeanShell
and this does it every time in all of the platforms I
tested.  

Note that whether or not you actually have the paths
and jars in the example above is irrelevant...
BeanShell locks up regardless of whether these paths
and jars exist or not.  

This does not seem to be a problem with the addClass or
other particular code above, but rather a simple issue
of how many lines are pasted.  Plenty of other examples
produce the same result.  One strange observation is
that it is possible to paste in many lines with simple
primitive and literal string assignments and not have
any problem at all.  For some reason, there have to be
real method calls on objects to produce the problem.

Reported by: mcrocker

Original Ticket: "beanshell/bugs/208":https://sourceforge.net/p/beanshell/bugs/208

**Comment by nickl-** [comment]
Duplicate #585
