### ISSUE TITLE
Scripted Interface: Error on invoke for 0 param method

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#347]
Calling a 0 parameter method on a scripted interface
that does 
not implement the method throws an Exception. This is
happening when BeanShell is attempting to call the
interface's invoke 
method.  The problem does not occur when the method has
one 
or more parameters:

```java
BeanShell 2.0b2 - by Pat Niemeyer ([pat@pat.net](mailto:pat@pat.net))
bsh % m = new Map() {
    get(key) { return "value"; }
    invoke(meth, args) {
        if ("remove".equals(meth)) return "remove not implemented.";
        if ("size".equals(meth)) return 12;
}};
bsh % print(m.get("foo")); // OK - implemented method value
bsh % print(m.remove("foo")); // OK - method has a parameter remove not implemented.
bsh % print(m.size());
// Error: // Uncaught Exception: Method Invocation m.size : at Line: 9 : in file: <unknown file> : m .size( )
```

Target exception: bsh.InterpreterError: null variable value

bsh.InterpreterError: null variable value
at bsh.NameSpace.setVariable\(Unknown Source\)
at bsh.NameSpace.setLocalVariable\(Unknown Source\)
at bsh.BshMethod.invokeImpl\(Unknown Source\)
at bsh.BshMethod.invoke\(Unknown Source\)
at bsh.BshMethod.invoke\(Unknown Source\)
at bsh.This.invokeMethod\(Unknown Source\)
at bsh.This.invokeMethod\(Unknown Source\)
at bsh.XThis$Handler.invokeImpl\(Unknown Source\)
at bsh.XThis$Handler.invoke\(Unknown Source\)
at $Proxy0.size\(Unknown Source\)
at
sun.reflect.NativeMethodAccessorImpl.invoke0\(Native Method\)
at
sun.reflect.NativeMethodAccessorImpl.invoke\(NativeMethodAccessorImpl.java:39\)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke\(DelegatingMethodAccessorImpl.java:25\)
at java.lang.reflect.Method.invoke\(Method.java:324\)
at bsh.Reflect.invokeOnMethod\(Unknown Source\)
at bsh.Reflect.invokeObjectMethod\(Unknown Source\)
at bsh.Name.invokeMethod\(Unknown Source\)
at bsh.BSHMethodInvocation.eval\(Unknown Source\)
at bsh.BSHPrimaryExpression.eval\(Unknown Source\)
at bsh.BSHPrimaryExpression.eval\(Unknown Source\)
at bsh.BSHArguments.getArguments\(Unknown Source\)
at bsh.BSHMethodInvocation.eval\(Unknown Source\)
at bsh.BSHPrimaryExpression.eval\(Unknown Source\)
at bsh.BSHPrimaryExpression.eval\(Unknown Source\)
at bsh.Interpreter.run\(Unknown Source\)
at bsh.Interpreter.main\(Unknown Source\)

=========================================================
The following patch fixes this problem:

RCS file:
/cvsroot/beanshell/BeanShell/src/bsh/Primitive.java,v
retrieving revision 1.23
diff -r1.23 Primitive.java
822,828c822,829
&lt;               if \( args == null \)
&lt;                       return null;
&lt; 
&lt;               Object \[\] oa = new Object\[ args.length \];
&lt;         for\(int i=0; i&lt;args.length; i++\)
&lt;             oa\[i\] = wrap\( args\[i\], paramTypes\[i\] \);
&lt;               return oa;
\---
&gt;         Object\[\] oa = new Object\[ paramTypes.length \];
&gt;               if \( args == null \)
&gt;             for\(int i=0; i&lt;oa.length; i++\)
&gt;                 oa\[i\] = null;
&gt;         else
&gt;             for\(int i=0; i&lt;oa.length; i++\)
&gt;                 oa\[i\] = wrap\( args\[i\], paramTypes\[i\] \);
&gt;         return oa;

Reported by: d-esterkin

Original Ticket: "beanshell/bugs/209":https://sourceforge.net/p/beanshell/bugs/209

**Comment by nickl-** [comment]
This is some serious voodoo, never attempted to override a method by overriding the invoke method, but hey seen stranger things.

Unfortunately the OP's original `Map` implementation wouldn't work.

```java
bsh % m = new Map() {
    get(key) { return "value"; }
    invoke(meth, args) {
        if ("remove".equals(meth)) return "remove not implemented.";
        if ("size".equals(meth)) return 12;
}};
// Error: Unknown error: java.lang.NullPointerException: Cannot invoke "java.util.Set.iterator()" because the return value of "java.util.Map.entrySet()" is null
```
It obviously needs an empty `Set` to instantiate the `Map`.
So I implemented the `entrySet` method too, returning an empty `Set`, then it all just worked.

```java
bsh % m = new Map() {
    get(key) { return "value"; }
    entrySet() { return new HashSet(); }
    invoke(meth, args) {
        if ("remove".equals(meth)) return "remove not implemented.";
        if ("size".equals(meth)) return 12;
}};
--> $3 = {} :Map
bsh % m.get("foo");
--> $4 = "value" :String
bsh % m.remove("foo");
--> $5 = "remove not implemented." :String
bsh % m.size();
--> $6 = 12I :int
```

Totally flabbergasted but very much pleased that we can deliver on the expectation.

Closed: works as expected
