### ISSUE TITLE
NullPointerException in bsh.NameSpace.getAllNamesAux(Vector)

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#348]
I got the following NPE

java.lang.NullPointerException
at bsh.NameSpace.getAllNamesAux\(Unknown Source\)
at bsh.NameSpace.getAllNames\(Unknown Source\)
...

when executing this code:

bsh.Interpreter beanshellInterpreter = ..;
bsh.NameSpace nameSpace = beanshellInterpreter.getNameSpace\(\);
final String\[\] allNames = nameSpace.getAllNames\(\);

Reported by: *anonymous

Original Ticket: "beanshell/bugs/210":https://sourceforge.net/p/beanshell/bugs/210

**Comment by nickl-** [comment]
Issue appears to be resolved on BeanShell 3.0.0-SNAPSHOT.841

```java
bsh % Interpreter bsh = new Interpreter();
--> $0 = bsh.Interpreter@200a570f :bsh.Interpreter
bsh % nameSpace = bsh.getNameSpace();
--> $1 = NameSpace: global (bsh.NameSpace@5680a178) :bsh.NameSpace
bsh % nameSpace.getAllNames();
--> $2 = {"bsh"} :String[]
```

Closed: cannot reproduce
