### ISSUE TITLE
Problem accessing maps getter from a script

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#350]
Hello, we have a beanshell script here which    
gets a     
Map as parameter.     
If the Map is a HashMap, for example, this is not     
a problem. However, if the Map given as     
parameter is a Map returned by     
java.util.Collections.unmodifiableMap\(Map m\), i     
get the following bsh error when accessing the     
'public Object get\(Object key\)' method of the Map:  

\--     
Error in method invocation: Cannot access      
method get\( java.lang.Object \) in 'class      
java.util.Collections$UnmodifiableMap' :java.lang.IllegalAccessException:       
Class bsh.Reflect can not access a member of      
class java.util.Collections$UnmodifiableMap      
with modifiers "public"       
\--  

I tried to do an explicit convertion of that to a Map,     
but it was of not help. The bsh Reflect still     
consider the Map as of private class     
java.util.Collections$UnmodifiableMap and do 
not seems to take into account the fact the 
method is public.    

I know it's possible to deactivate all the    
accessibility checks in bsh, but this is not what i    
need. I need what is private to stay private but, as    
long as i get any Object i consider i should be    
able to access it's public Methods \(it's legal to    
access public Methods of an interface in java,    
whatever the implementation of the interface is    
private or public\)    

The following scripts all fail when the    
implementation of Map named transientVars is   
private:    

print\(transientVars.get\("caller"\)\);    

print\(\(\(java.util.Map\)transientVars\).get\("caller"\)\);    

java.util.Map myMap = transientVars;        
print\(myMap.get\("caller"\)\);    

Suggestions:    
\- either do not check the class accessibility in    
itself when dealing with non-static methods    
\- either when the objet's class is non-public,    
check if it implements any public interface or it's    
ancestor is public. If the requested public    
method is part of an interface or any public    
ancestor, allow access.    

Side node:    
This is quite common in java to use an object    
which's implementation is private. This is the    
case with factories pattern when a factory    
method return an object implementing a given    
interface \(java.util.Collections is a good example    
of such factory\)    
This is also quite often the case in j2ee   
environnement, when, for example, you call   
methods from HttpRequest or HttpResponse.   

Reported by: tchize

Original Ticket: "beanshell/bugs/212":https://sourceforge.net/p/beanshell/bugs/212

**Comment by nickl-** [comment]
I wish they bothered to give us an example, I cannot imagine this would be a problem on 3.0.0-SNAPSHOT.841

Lets test just to make sure. Should be something like:

```java
public class T {
    private static Map transientVars = java.util.Collections.unmodifiableMap({"caller"=true});

    public static void t() {
        print(transientVars.get("caller"));

        print(((java.util.Map)transientVars).get("caller"));

        java.util.Map myMap = transientVars;
        print(myMap.get("caller"));
    }
}
```
And the result is a success: (as expected)

```java
bsh % T.t();
true :boolean
true :boolean
true :boolean
--> void
```

**Comment by nickl-** [comment]
Closed cannot reproduce, works as expected.
