### ISSUE TITLE
dir() returns bad output on Windows

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#351]
I saw this on 2 Windows 2000 machines.

bsh % pwd\(\);
E:\Documents and Settings\Yaron\Desktop\BeanShell

bsh % cd\(".."\);
bsh % dir\(\);
\--\_ Jan 1         0 100\_FUJI
\--\_ Jan 1         0 BOINC
\--\_ Jan 1         0 BeanShell
\--\_ Jan 1         0 Bills
\--\_ Jan 1         0 Bills and Taxes
\--\_ Jan 1         0 Boston Snow
\--\_ Jan 1         0 CIFS Book.url
\--\_ Jan 1         0 CallDetails.csv

All files are listed, in the right order. But
permissions and date are nonsense.

Thanks, Yaron.

yaronf at gmx dot net

Reported by: *anonymous

Original Ticket: "beanshell/bugs/213":https://sourceforge.net/p/beanshell/bugs/213

**Comment by nickl-** [comment]
Works on linux as expected.

Help wanted:
Need to test this on Windows.

**Comment by nickl-** [comment]
In the absence of much needed assistance, had to spend time raising a windows environment myself.

Seems to work on: BeanShell 3.0.0-SNAPSHOT.841
```java
bsh % pwd();
C:\code\beanshell\src
--> void
bsh % cd("..");
--> void
bsh % dir();
rw_ Dec 9      4096 .git/
rw_ Dec 9         0 .github/
rw_ Dec 9       257 .gitignore
rw_ Dec 9     54482 CHANGES.md
rw_ Dec 9     13225 LICENSE
rw_ Dec 9       165 NOTICE
rw_ Dec 9     14971 README.md
rw_ Dec 9         0 bsh-bsf-engine/
rw_ Dec 9       987 build.xml
rw_ Dec 9     15086 favicon.ico
rw_ Dec 9      1007 maven-build.properties
rw_ Dec 9     12470 maven-build.xml
rw_ Dec 9      9904 maven-bundle-plugin-3.5.1.pom
rw_ Dec 9     11808 pom.xml
rw_ Dec 9         0 scripts/
rw_ Dec 9         0 src/
rw_ Dec 9      4096 target/
rw_ Dec 9        88 testBshScriptEngine.out
rw_ Dec 9        83 test_interpreter.out
--> void
```

Closed: works as expected
