### ISSUE TITLE
\u in comment creates problems

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#352]
I got the following error while using the beanshell
interpreter.The problem was caused because i had the
character sequence "\uXYZ" as
part of a comment in the script file.

Here is an example script that caused the problem.
\---START-----------------------------------------------------------------------------------
// this is an \ugly comment

/\*
\* this is another \ugly comment
\*/

String getResult\(String input\)
\{
return "test";
\}
\--END-------------------------------------------------------------------------------------

Exception message.

\--START-----------------------------------------------------------------------------------------------
Stack Trace:
java.lang.Error: Invalid escape character at line 1
column 16.
at bsh.JavaCharStream.readChar\(Unknown Source\)
at bsh.ParserTokenManager.jjMoveNfa\_0\(Unknown
Source\)
at bsh.ParserTokenManager.jjStartNfa\_0\(Unknown
Source\)
at
bsh.ParserTokenManager.jjMoveStringLiteralDfa1\_0\(Unknown
Source\)
at
bsh.ParserTokenManager.jjMoveStringLiteralDfa0\_0\(Unknown
Source\)
at bsh.ParserTokenManager.getNextToken\(Unknown
Source\)
at bsh.Parser.jj\_ntk\(Unknown Source\)
at bsh.Parser.Line\(Unknown Source\)
at bsh.Interpreter.Line\(Unknown Source\)
at bsh.Interpreter.eval\(Unknown Source\)
at bsh.Interpreter.eval\(Unknown Source\)
\--END-----------------------------------------------------------------------------------------------

I have tested this with bsh-2.0b1.jar and
bsh-2.0b2.jar. Both had the above mentioned problem.

Reported by: *anonymous

Original Ticket: "beanshell/bugs/214":https://sourceforge.net/p/beanshell/bugs/214

**Comment by nickl-** [comment]
Not sure we should do anything about this, the error message is precise.

Should we allow unicode escape strings in comments?

**Comment by nickl-** [comment]
infact if it is a valid unicode character it parses correctly 

Closed works as expected
