### ISSUE TITLE
Runtime error (Target Exception) using super

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#357]
```java
class t3 {
  public String answer = "Yes";

  public void w() {
    String answer = "No!";
  }
}
public class t3ext extends t3 {
  public String answer = "No!";

  public void w() {
    String answer = "Maybe";
    System.out.println("Is Nigel best? > " + super.answer);
  }

  public static void main(String[] args) {
    t3 w = new t3ext();
    w.w();
  }
}
```
Process cat exited with code 0

Compiling and running the above with java produdces:
&gt; javac t3ext.java
Process javac exited with code 0
&gt; java t3ext
Is Nigel best? &gt; Yes
Process java exited with code 0

BeanShell has a runtime problem:
&gt; java -classpath ../../bsh-2.0b4.jar bsh.Interpreter 
t3ext.java
Class: class t3ext main method threw 
exception:Method Invocation w.w : at Line: 23 : in file: 
t3ext.java : w .w \( \) 

Called from method: main : at Line: -1 : in file: &lt;Called 
from Java Code&gt; : &lt;Compiled Java Code&gt;
Target exception: Can't reach instance field: answer 
from static context: t3ext : at Line: 17 : in file: 
t3ext.java : super .answer 

Called from method: w : at Line: -1 : in file: &lt;Called from 
Java Code&gt; : &lt;Compiled Java Code&gt;

Process java exited with code 0

Reported by: nigel_galloway

Original Ticket: "beanshell/bugs/219":https://sourceforge.net/p/beanshell/bugs/219

**Comment by nickl-** [comment]
Can reproduce, hidden  fields not accessible via a super access expression.

In this example the call to `super.answer` still returns `this.answer`.

[t3ext.java.txt](https://github.com/beanshell/beanshell/files/10145668/t3ext.java.txt)

**Comment by nickl-** [comment]
parent #660

**Comment by nickl-** [comment]
Resolved:

```java
BeanShell 3.0.0-SNAPSHOT.3056
--> $1 = class t3ext :Class
bsh % t3ext.main({""});
Is Nigel best? > Yes
--> void
```
