### ISSUE TITLE
Cast unsuccessful

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#358]
Atempting to work around problem 1221300 with the 
following:

```java
class t4 {
  public String answer = "Yes";

  public void w() {
    String answer = "No!";
  }
}

public class t4ext extends t4 {
  public String answer = "No!";

  public void w() {
    String answer = "Maybe";
    System.out.println("Is Nigel best? > " + ((t4)this).answer);
  }

  public static void main(String[] args) {
    t4 w = new t4ext();
    w.w();
  }
}
```

Process cat exited with code 0

Works in Java:
&gt; javac t4ext.java
Process javac exited with code 0
&gt; java t4ext
Is Nigel best? &gt; Yes
Process java exited with code 0

BeanShell still hasn't read "How to make friends and 
influence people":
/home/nigel/myBsh/Pitfalls/temp/&gt; java -
classpath ../../bsh-2.0b4.jar bsh.Interpreter t4ext.java
Is Nigel best? &gt; No\!
Process java exited with code 0

Reported by: nigel_galloway

Original Ticket: "beanshell/bugs/220":https://sourceforge.net/p/beanshell/bugs/220

**Comment by nickl-** [comment]
Can reproduce, hidden  fields not accessible via a cast to a superclass type.

In this example the call to `((t4)this).answer` still returns `this.answer`.

**Comment by nickl-** [comment]
parent #660

**Comment by opeongo** [comment]
And if you change the reference to
```java
    System.out.println("Is Nigel best? > " + super.answer);
```
it still does not work in BeanShell, so it is not only casting.  Or rather it is lookups not casting that is having the problem.

**Comment by nickl-** [comment]
Some more tests:

```java
--> void
(new t4ext()).answer

--> $2 = "No!" :String
((t4)new t4ext()).answer

--> $3 = "No!" :String
```

**Comment by nickl-** [comment]
Resolved: 

```java
BeanShell 3.0.0-SNAPSHOT.3056
bsh % (new t4ext()).answer;
--> $7 = "No!" :String
bsh % ((t4)new t4ext()).answer;
--> $8 = "Yes" :String
bsh % t4ext.main({""});
Is Nigel best? > Yes
--> void
```
