### ISSUE TITLE
Runtime error using forward referrence

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#359]
&gt; cat t5.java
```java
public class t5 {
  static String f = myForwardRef();

  static String myForwardRef(){
    return ("Nigel is best");
  }
  public static void main (String[] args){
    System.out.println(f);
  }
}
```
Process cat exited with code 0

Java produces the familiar:
&gt; javac t5.java
Process javac exited with code 0
&gt; java t5
Nigel is best
Process java exited with code 0

BeanShell will do anything to avoid saying it:
&gt; java -classpath ../../bsh-2.0b4.jar bsh.Interpreter 
t5.java
Script threw exception: Sourced file: t5.java : Typed 
variable declaration : Exception invoking imported object 
method. : at Line: 2 : in file: t5.java : myForwardRef \( \) 

Target exception: 
java.lang.reflect.InvocationTargetException

java.lang.reflect.InvocationTargetException
at 
sun.reflect.NativeMethodAccessorImpl.invoke0\(Native 
Method\)
at 
sun.reflect.NativeMethodAccessorImpl.invoke
\(NativeMethodAccessorImpl.java:39\)
at 
sun.reflect.DelegatingMethodAccessorImpl.invoke
\(DelegatingMethodAccessorImpl.java:25\)
at java.lang.reflect.Method.invoke
\(Method.java:585\)
at bsh.Reflect.invokeMethod\(Unknown 
Source\)
at bsh.BshMethod.invoke\(Unknown Source\)
at bsh.BshMethod.invoke\(Unknown Source\)
at bsh.Name.invokeLocalMethod\(Unknown 
Source\)
at bsh.Name.invokeMethod\(Unknown Source\)
at bsh.BSHMethodInvocation.eval\(Unknown 
Source\)
at bsh.BSHPrimaryExpression.eval\(Unknown 
Source\)
at bsh.BSHPrimaryExpression.eval\(Unknown 
Source\)
at bsh.BSHVariableDeclarator.eval\(Unknown 
Source\)
at bsh.BSHTypedVariableDeclaration.eval
\(Unknown Source\)
at bsh.BSHBlock.evalBlock\(Unknown 
Source\)
at 
bsh.ClassGeneratorImpl.generateClassImpl\(Unknown 
Source\)
at bsh.ClassGeneratorImpl.generateClass
\(Unknown Source\)
at bsh.BSHClassDeclaration.eval\(Unknown 
Source\)
at bsh.Interpreter.eval\(Unknown Source\)
at bsh.Interpreter.source\(Unknown Source\)
at bsh.Interpreter.main\(Unknown Source\)
Caused by: java.lang.NullPointerException
at t5.myForwardRef\(BeanShell Generated via 
ASM \(www.objectweb.org\)\)
... 21 more
Process java exited with code 0

Reported by: nigel_galloway

Original Ticket: "beanshell/bugs/221":https://sourceforge.net/p/beanshell/bugs/221

**Comment by nickl-** [comment]
Exception in BeanShell 3.0.0-SNAPSHOT.841
[t5.java.txt](https://github.com/beanshell/beanshell/files/10145526/t5.java.txt)


```java
bsh % source("t5.java");
--> $0 = class t5 :Class
bsh % t5.main(new String[0]);
// Error: Internal Error: Exception in static init block <clinit> for class t5. With message: Typed variable declaration : Exception invoking imported object method. : at Line: 2 : in file: /home/intriazen/git/beanshell/t5.java : myForwardRef ( )
Caused by: java.lang.reflect.InvocationTargetException
bsh.EvalError: Method myForwardRef() not found in bsh scripted object: t5 : at Line: -1 : in file: <Called from Java Code> : <Compiled Java Code>
: <at unknown location>

bsh.EvalError: Method myForwardRef() not found in bsh scripted object: t5 : at Line: -1 : in file: <Called from Java Code> : <Compiled Java Code>
```

**Comment by nickl-** [comment]
It relates to the order in which the field and method is declared;

Method first works:
```java
BeanShell 3.0.0-SNAPSHOT.3707
class A { static int get() { return 1; } static int g = get(); }
--> $0 = class A :Class
A.g;
--> $1 = 1I :int
```

But declaring the field first which references the later declared method it fails.
```java
BeanShell 3.0.0-SNAPSHOT.3707
class A { static int g = get(); static int get() { return 1; } }
--> $5 = class A :Class
A.g;
// Error: Target Exception: Exception in static init block <clinit> for class A. With message: Typed variable declaration : 
```

**Comment by nickl-** [comment]
This is not just related to static members but instance references will also fail.

```java
BeanShell 3.0.0-SNAPSHOT.3703
class A { int g = get(); int get() { return 1; } }
--> $0 = class A :Class
new A().g;
// Error: Target Exception: Object constructor : at Line: 2 : in file: <unknown file> : new A ( ) 
Caused by: bsh.InterpreterError: Error in class instance initialization: bsh.InterpreterError: Error in class instance This initialization: bsh.TargetError: Typed variable declaration : Exception invoking imported object method. : at Line: 1 : in file: <unknown file> : get ( ) 
Caused by: java.lang.reflect.InvocationTargetException
bsh.EvalError: Method get() not found in bsh scripted object: A : at Line: -1 : in file: <Called from Java Code> : <Compiled Java Code>
```

**Comment by nickl-** [comment]
I honestly cannot believe we haven't picked this up before.
