### ISSUE TITLE
When accessing scripted class in java, error even when found

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#360]
When accessing a class in a \*.java file, beanshell finds 
the class and works correctly, but actually generates an 
error \(oddly enough\):

Loading class from source file:
Class not found in source file:

it still works though

Reported by: furashgf

Original Ticket: "beanshell/bugs/222":https://sourceforge.net/p/beanshell/bugs/222

**Comment by nickl-** [comment]
Not enough information
Close: cannot reproduce
