### ISSUE TITLE
bsh.TokenMgrError: Lexical error at line 1, column 127.  Enc

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#362]
Entering a unicode string into a Bsh Workspace seems 
to cause a problem:

2.0b5 - by Pat Niemeyer \(pat@pat.net\)
bsh % print\("Nigel is best"\);
Nigel is best
bsh % print\("\u0100"\);
// Error: Error parsing input: bsh.TokenMgrError: Lexical 
error at line 1, column 127.  Encountered: "u" \(117\), 
after : "\"\\\"
bsh % print\("\\\"\);
// Error: Parser Error: In file: &lt;unknown&gt; Encountered "\( 
print \( \"\\\\\\\\\" \) ;" at line 1, column 109.

bsh %  

Running the same commands with Beanshell produces 
as it should:

&gt; java -classpath ../bsh-2.0b5.jar bsh.Interpreter test.bsh
Nigel is best
?
\
Process java exited with code 0

If I change the unicode string:
&gt; cat test.bsh
print\("Nigel is best"\);
print\("\u005C"\);
print\("\\\"\);
Process cat exited with code 0

Then BeanShell is not happy either:
&gt; java -classpath ../bsh-2.0b5.jar bsh.Interpreter test.bsh
Nigel is best
Evaluation Error: Sourced file: test.bsh Token Parsing 
Error: Lexical error at line 2, column 17.  
Encountered: "\n" \(10\), after : "\"\\\\\"\);": &lt;at unknown 
location&gt;

Process java exited with code 0

Reported by: nigel_galloway

Original Ticket: "beanshell/bugs/224":https://sourceforge.net/p/beanshell/bugs/224

**Comment by nickl-** [comment]
Closed: Duplicate #399
