### ISSUE TITLE
BeanShell's automatic casts are more restrictive than Java

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#363]
The following code:
&gt; cat t8.java
public class t8 \{
public static void main\(java.lang.String\[\] $0s\) 
\{
byte b1;
b1 = 127;
return;
\}
\}
Process cat exited with code 0

Compiles in Java:
&gt; javac t8.java
Process javac exited with code 0

But throws an exception in Beanshell:
&gt; java -classpath ../bsh-2.0b5.jar bsh.Interpreter t8.java
Class: class t8 main method threw exception:Variable 
assignment: b1: Can't assign int to byte : at Line: 4 : in 
file: t8.java : b1 = 127 

Called from method: main : at Line: -1 : in file: &lt;Called 
from Java Code&gt; : &lt;Compiled Java Code&gt;
Process java exited with code 0

Reported by: nigel_galloway

Original Ticket: "beanshell/bugs/225":https://sourceforge.net/p/beanshell/bugs/225

**Comment by nickl-** [comment]
No exception on BeanShell 3.0.0-SNAPSHOT.841 works like java
[t8.java.txt](https://github.com/beanshell/beanshell/files/10145483/t8.java.txt)


```java
bsh % source("t8.java");
--> $0 = class t8 :Class
bsh % t8.main(new String[0]);
--> void
```

Closed works as expected
