### ISSUE TITLE
single var arg methods cannot be overwritten

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#366]
this prints "i'm method 2" with bsh-2.0b2.jar
and "i'm method 1" with bsh-2.0b4.jar .

it should still print "i'm method 2", but 
redefinition seems to fail since then.

void test\(var x\) \{ print\("i'm method 1"\); \}
void test\(var x\) \{ print\("i'm method 2"\); \}
test\(5\);

Reported by: *anonymous

Original Ticket: "beanshell/bugs/228":https://sourceforge.net/p/beanshell/bugs/228

**Comment by nickl-** [comment]
Works in BeanShell 3.0.0-SNAPSHOT.841

```java
bsh % void test(var x) { print("i'm method 1"); }
--> void
bsh % void test(var x) { print("i'm method 2"); }
--> void
bsh % test(5);
i'm method 2
--> void
```

Closed works as expected
