### ISSUE TITLE
try/catch/finally doesn't have the right behavior

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#367]
try this piece of code:

boolean canDo\(\) \{
FileOutputStream fos = null;
try \{
fos = new FileOutputStream\("f:\\\tmp\\\bsh.testfile"\);
return true;
\} catch \(IOException ie\) \{
ie.printStackTrace\(\);
return false;
\}  finally \{
try \{
fos.close\(\);
\} catch \(IOException ie1\) \{
ie1.printStrackTrace\(\);
\}
\}

// should never reach here
return false;
\}

In BeanShell, this function already return false.  If I
comment out the last 'return false' statement, bsh will
throw an exception:

in BshMethod.java \(line 395\).

Reported by kaiyang@hansky.com

Reported by: *anonymous

Original Ticket: "beanshell/bugs/229":https://sourceforge.net/p/beanshell/bugs/229

**Comment by opeongo** [comment]
I tried running these test cases under the current master (@fdddee3) and both work correctly.  This specific issue appears to be fixed,  I recommend to close this ticket as either 'fixed' or 'not reproducible'.

**Comment by nickl-** [comment]
Awesome @opeongo you RockStar!!!!

**Closed: works as expected**

**Comment by nickl-** [comment]
Mar 31, 2009
> What would be the timeline to fix this issue?
> 
> Original comment by: nobody

One day short of 10 years, who says we're not getting things done! =)
