### ISSUE TITLE
Parse error for int with highest order bit set

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#370]
bsh % print\(0x80000000\);
// Error: Parser Error: Parse error at line 1, column
589 : Error or number too big for integer type: 0x80000000

BeanShell incorrectly rejects hex representation of an
int with the high-order bit set.

submitted by Andy Putnins, putnins@lett.com

Reported by: *anonymous

Original Ticket: "beanshell/bugs/232":https://sourceforge.net/p/beanshell/bugs/232

**Comment by nickl-** [comment]
BeanShell 3.0.0-SNAPSHOT.841 knows hexadecimal

```java
bsh % print(0x80000000);
2147483648L :long
--> void
```

Cannot reproduce, works as expected
