### ISSUE TITLE
toString is not properly overridden in scripted objects

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#371]
Suppose we have the following code:

```java
test() {
    toString() { return "test"; }
    return this;
}
```

The idea here is to override Object.toString to get
something more readable than the default
XThis.toString. Now, print\(test\(\).toString\(\)\) prints
"test" as expected. Unfortunately, for some reason,
print\(test\(\)\) still prints "'this' reference \(XThis\) to
Bsh object: NameSpace: test \(bsh.NameSpace@1ee04fd\)
\(method\)" instead of "test". Interestingly, you can get
the correct result with the following trick:
print\(test\(\).getInterface\(Serializable.class\)\)

Reported by: juhal

Original Ticket: "beanshell/bugs/233":https://sourceforge.net/p/beanshell/bugs/233

**Comment by nickl-** [comment]
Feature request, implement toString override method
