### ISSUE TITLE
NullPointerException in logInvokeMethod during logging null

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#372]
In function: Reflect.logInvokeMethod

During logging null-Primitive a NullPointerException
occurs because null.getClass\(\) is invalid.

Fix:
```java
private static void logInvokeMethod(String msg, Method method, Object[] args ) {
    if ( Interpreter.DEBUG ) {
        Interpreter.debug( msg +method+" with args:" );
        for(int i=0; i<args.length; i++)
            Interpreter.debug("args["+i+"] = "+ args[i] + " type = "
                + ( (args[i] instanceof(Object) ? args[i].getClass() : args[i]) );
    }
}
```

Reported by: stewu

Original Ticket: "beanshell/bugs/234":https://sourceforge.net/p/beanshell/bugs/234

**Comment by nickl-** [comment]
Null check implemented in 3.0.0-SNAPSHOT.841

https://github.com/beanshell/beanshell/blob/5f09368e18200b80f039872b0f1ca714e8a2f4cc/src/main/java/bsh/Reflect.java#L841-L856

Closed: resolved
