### ISSUE TITLE
using a GUI Swing type style of Java

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#373]
Let's see if I can get my preferred result from a GUI 
Swing type style:

&gt; cat t92.java
```java
class A1 {
    public String out() {
        return "Nigel is best";
    }
}

abstract class Nigel {
    A1 a;
    String str;

    public Nigel(A1 a) {
        this.a = a;
    }

    public String toString() {
        return str;
    }

    public abstract void set();
}

class t92 {
    public t92(Nigel x) {
        x.set();
        System.out.println(x);
    }

    public static void main(String[] args) {
        A1 a = new A1();
        t92 t92 = new t92(
            new Nigel(a) {
                public void set() {
                    str = a.out();
                }
            });
    }
}
```

Process cat exited with code 0

Compiling and running with java produces my favourite 
result:

&gt; javac t92.java
Process javac exited with code 0
&gt; java t92
Nigel is best
Process java exited with code 0

BeanShell takes exception:

&gt; java -classpath /opt/bsh-2.0b5.jar bsh.Interpreter 
t92.java
Class: class t92 main method threw exception:Typed 
variable declaration : Error constructing inner class 
instance: bsh.ReflectError: Can't find constructor: main$1
\( A1 \) in class: main$1 : at Line: 39 : in file: t92.java : 
new Nigel \( a \) \{ 

Called from method: main : at Line: -1 : in file: &lt;Called 
from Java Code&gt; : &lt;Compiled Java Code&gt;
Process java exited with code 0

Reported by: nigel_galloway

Original Ticket: "beanshell/bugs/235":https://sourceforge.net/p/beanshell/bugs/235

**Comment by nickl-** [comment]
Works in BeanShell 3.0.0-SNAPSHOT.841
[t92.java.txt](https://github.com/beanshell/beanshell/files/10145364/t92.java.txt)

```java
bsh % source("t92.java");
--> $0 = class t92 :Class
bsh % t92.main(new String[0]);
Nigel is best
--> void
```

Closed: works as expected
