### ISSUE TITLE
using an InputStream

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#374]
&gt; cat t93.java
```java
import java.io.*;
import java.util.*;

class t93 {
    public static void main(String[] args) {
        InputStream is;
        try {
            is = t93.class.getResourceAsStream("my.properties");
            Properties properties = new Properties();
            if (is != null) {
                properties.load(is);
                Enumeration keys = properties.keys();
                while (keys.hasMoreElements()) {
                    String key = (String) keys.nextElement();
                    if (key.startsWith("Nigel_"))
                        System.out.println(key);
                }
            }
            else
                System.out.println("Nigel_is.Rubbish");
        } catch (Exception e) {}
    }
}
```

Process cat exited with code 0

&gt; cat my.properties
```ini
Root=/home/nigel/myBsh
title=Salutations
Nigel_is.Best = normal
Nigel_is.Great = extra
Nigel_is.Superb = ott
NotifyUserImpl=SwingNotifyUser
IconFileName=nigel.gif
```

Process cat exited with code 0

Compiling and executing in Java exceeds my 
expectations:

&gt; javac t93.java
Process javac exited with code 0
&gt; java t93
Nigel\_is.Best
Nigel\_is.Superb
Nigel\_is.Great
Process java exited with code 0

BeanShell as expected is less friendly

&gt; java -classpath /opt/bsh-2.0b5.jar bsh.Interpreter 
t93.java
Nigel\_is.Rubbish
Process java exited with code 0

Reported by: nigel_galloway

Original Ticket: "beanshell/bugs/236":https://sourceforge.net/p/beanshell/bugs/236

**Comment by jimjag** [comment]
Confirmed still exists in BeanShell 3.0.0-SNAPSHOT.841

**Comment by nickl-** [comment]
This is a class path issue, if you include `.` in the classpath where `my.properties` can be found it works as expected:

```shell
$ java -cp $CLASSPATH:. bsh.Interpreter t93.java
```
Produces the correct output:
```
Nigel_is.Best
Nigel_is.Superb
Nigel_is.Great
```

Without the added class path the resource cannot be found, which is also expected.

```terminal
$ java -cp $CLASSPATH bsh.Interpreter t93.java
```
Produces output:
```
Nigel_is.Rubbish
```

Closed works as expected
