### ISSUE TITLE
doesn't accept large hex ints

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#375]
This works in plain Java, but not in bsh:

int i =2; //ok
int j = 0x80; //ok
int k = 0x80000000;
// Error: Parser Error: Parse error at line 3, column 9
: Error or number too big for integer type: 0x80000000

I would expect k to be assigned -2147483648, like in
regular Java.

Reported by: *anonymous

Original Ticket: "beanshell/bugs/237":https://sourceforge.net/p/beanshell/bugs/237

**Comment by nickl-** [comment]
Output

```
bsh % int k = 0x80000000;
// Error: Internal Error: cannot assign number 2147483648 to type int
```

**Closed: works as expected**
