### ISSUE TITLE
Request for debugging API

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#376]
Beanshell is a wonderful tool but it really needs hooks
for debugging. I have implementing debugging hooks in
the past by refactoring SimpleNode and all its children
so it always does a listener call back on
SimpleNode.eval\(\). That way a debugger can intercept
code execution for breakpoints, pauses, whatever.

Unforunately, every time a new version comes out, I
need to re-integrate my hooks. I would like to requrest
that an API is added permanently. I would be happy to
contribute code to do this on the latest version.

Reported by: dsomerfield

Original Ticket: "beanshell/bugs/238":https://sourceforge.net/p/beanshell/bugs/238

**Comment by nickl-** [comment]
Closed : Nothing can be done here
