### ISSUE TITLE
An exception in break label

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#377]
&gt; cat t94.java
```java
class t94 {
    public static void main(String[] args) {
        boolean t = true;
        first :
        {
            second :
            {
                third :
                {
                    System.out.println("Who is best?");
                    if (t)
                        break second;
                }
                System.out.println("BeanShell perhaps");
            }
            System.out.println("Nigel of course");
        }
    }
}
```

Process cat exited with code 0

As expected Java knows the truth

&gt; javac t94.java
Process javac exited with code 0
&gt; java t94
Who is best?
Nigel of course
Process java exited with code 0

BeanShell just can not bring itself to print it.

&gt; java -classpath /opt/bsh-2.0b5.jar bsh.Interpreter 
t94.java
Who is best?
Class: class t94 main method threw exception:'continue' 
or 'break' in method body : at Line: 12 : in file: t94.java : 
break second ; 

Called from method: main : at Line: -1 : in file: &lt;Called 
from Java Code&gt; : &lt;Compiled Java Code&gt;
Process java exited with code 0

Reported by: nigel_galloway

Original Ticket: "beanshell/bugs/239":https://sourceforge.net/p/beanshell/bugs/239

**Comment by jimjag** [comment]
Confirmed still exists in 3.0.0-snapshot (a36bd52b5037ae9b442a077888a5e4874ac03ce0)

**Comment by nickl-** [comment]
Changed to feature request, labels are not implemented yet

**Comment by nickl-** [comment]
Tagging #379 as related

**Comment by nickl-** [comment]
Something like this? =)

```java
BeanShell 3.0.0-SNAPSHOT.3432
bsh % class t94 {
    public static void main(String[] args) {
        boolean t = true;
        first :
        {
            second :
            {
                third :
                {
                    System.out.println("Who is best?");
                    if (t)
                        break second;
                }
                System.out.println("BeanShell perhaps");
            }
            System.out.println("Nigel of course");
        }
    }
}
--> $0 = class t94 :Class
bsh % t94.main({""});
Who is best?
Nigel of course
--> void
```
