### ISSUE TITLE
Problem to continue to a label

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#379]
&gt; cat t95.java
```java
class t95 {
    public static void main(String[] args) {
        char[] c = {78, 105, 103, 101, 108, 32, 105, 115, 32, 98, 101, 115, 116};
        outer :
        for (int i = 0; i < 13; i++)
            for (int j = 0; j < 13; j++) {
                if (j > i) {
                    System.out.println();
                    continue outer;
                }
                System.out.print(c[j]);
            }
        System.out.println();
    }
}
```

Process cat exited with code 0

Compiled and executed in Java produces:

&gt; javac t95.java
Process javac exited with code 0
&gt; java t95
N
Ni
Nig
Nige
Nigel
Nigel 
Nigel i
Nigel is
Nigel is 
Nigel is b
Nigel is be
Nigel is bes
Nigel is best
Process java exited with code 0

BeanShell has problems with the continue:

&gt; java -classpath /opt/bsh-2.0b5.jar bsh.Interpreter 
t95.java
N

Ni

Nig

Nige

Nigel

Nigel 

Nigel i

Nigel is

Nigel is 

Nigel is b

Nigel is be

Nigel is bes
Nigel is best
Process java exited with code 0

Reported by: nigel_galloway

Original Ticket: "beanshell/bugs/241":https://sourceforge.net/p/beanshell/bugs/241

**Comment by jimjag** [comment]
Confirmed still exists in 3.0.0-snapshot (a36bd52b5037ae9b442a077888a5e4874ac03ce0)

**Comment by nickl-** [comment]
Changed to feature request, labels are not implemented yet

**Comment by nickl-** [comment]
Tagging #377 as related

**Comment by nickl-** [comment]
Something like this: =)

```java
BeanShell 3.0.0-SNAPSHOT.3450
bsh % class t95 {
    public static void main(String[] args) {
        char[] c = {78, 105, 103, 101, 108, 32, 105, 115, 32, 98, 101, 115, 116};
        outer :
        for (int i = 0; i < 13; i++)
            for (int j = 0; j < 13; j++) {
                if (j > i) {
                    System.out.println();
                    continue outer;
                }
                System.out.print(c[j]);
            }
        System.out.println();
    }
}
--> $0 = class t95 :Class
bsh % t95.main({""});
N
Ni
Nig
Nige
Nigel
Nigel
Nigel i
Nigel is
Nigel is
Nigel is b
Nigel is be
Nigel is bes
Nigel is best
--> void
```
