### ISSUE TITLE
Problem throwing an exception

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#381]
&gt; cat t97.java
```java
class t97 {
    static void aProc() {
        System.out.println("Exceptional Procedure");
        NullPointerException e = new NullPointerException("Nigel");
        e.initCause(new ArithmeticException("of course"));
        throw e;
    }

    public static void main(String[] arg) {
        try {
            aProc();
        } catch (NullPointerException e) {
            System.out.println("Who is best: " + e.getMessage());
            System.out.println("Are you sure?: " + e.getCause().getMessage());
        }
    }
}
```

Process cat exited with code 0

Java produces the following:

&gt; javac t97.java
Process javac exited with code 0
&gt; java t97
Exceptional Procedure
Who is best: Nigel
Are you sure?: of course
Process java exited with code 0

but BeanShell generates an exception:

&gt; java -classpath /opt/bsh-2.0b5.jar:. bsh.Interpreter 
t97.java
Exceptional Procedure
Class: class t97 main method threw 
exception:Exception invoking imported object method. : 
at Line: 12 : in file: t97.java : aProc \( \) 

Target exception: 
java.lang.reflect.InvocationTargetException

Process java exited with code 0

Reported by: nigel_galloway

Original Ticket: "beanshell/bugs/243":https://sourceforge.net/p/beanshell/bugs/243

**Comment by nickl-** [comment]
Works in BeanShell 3.0.0-SNAPSHOT.841
[t97.java.txt](https://github.com/beanshell/beanshell/files/10145341/t97.java.txt)

```java
bsh % source("t97.java");
--> $0 = class t97 :Class
bsh % t97.main(new String[0]);
Exceptional Procedure
Who is best: Nigel
Are you sure?: of course
--> void
```

Closed: works as expected
