### ISSUE TITLE
Class loading problem

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#382]
Class.forName\(\) throws ClassNotFoundException for a
loaded class in BeanShell:

How to recreate:
\- Download a jar file \(e.g hsqldb.jar from the HSQLDB
project @ SF.net\)
\- Run the BeanShell console 
\- add the jar file to class path:
addClassPath\("hsqldb.jar"\);
\- import all classes: import \*;
\- call Class.forName\("org.hsqldb.jdbcDriver"\);

Exception thrown

java.lang.ClassNotFoundException: org.hsqldb.jdbcDriver

Reported by: nileflowers

Original Ticket: "beanshell/bugs/244":https://sourceforge.net/p/beanshell/bugs/244

**Comment by jimjag** [comment]
Cannot reproduce
