### ISSUE TITLE
reference to Type is ambiguous

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#385]
When I try to build beanshell I get the following errors:

beanshell/unxlngi6.pro/misc/build/BeanShell/src/bsh/ClassGeneratorUtil.java:137:
reference to Type is ambiguous, both class
java.lang.reflect.Type in java.lang.reflect and class
bsh.org.objectweb.asm.Type in bsh.org.objectweb.asm match
this.superClassName = Type.getInternalName\(
superClass \);

^
beanshell/unxlngi6.pro/misc/build/BeanShell/src/bsh/ClassGeneratorUtil.java:137:
cannot find symbol
symbol  : method getInternalName\(java.lang.Class\)
location: interface java.lang.reflect.Type
this.superClassName = Type.getInternalName\(
superClass \);

^

What flavour of java is required to build beanshell?
I have got java-1\_5\_0-sun and java-1.4.2-sun.
Do I need IBMJava2 instead?

Reported by: *anonymous

Original Ticket: "beanshell/bugs/247":https://sourceforge.net/p/beanshell/bugs/247

**Comment by nickl-** [comment]
Closed cannot reproduce on 3.0.0-SNAPSHOT.841
