### ISSUE TITLE
Personal Java Compatability Problem

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#386]
The core interpreter package does not run on a 
Personal Java \(Java 1.1\) system. bsh.Reflection class 
contains a call to Vector.add\(\) which should instead 
be Vector.addElement\(\)

The jvm I used when I encountered this error was 
Jeode for the Pocket PC. The error also occurs on the 
personal java emulation environment \(pjee\) from sun 
which runs on a standard PC.

I would very much like to be able to use bsh on a 
Java 1.1 system, and if all the problems are like the 
one above I'm sure it won't take long to fix.

Thanks,

Christopher James Plant
\(mulletwarriorextreem@hotmail.com\)

Reported by: *anonymous

Original Ticket: "beanshell/bugs/248":https://sourceforge.net/p/beanshell/bugs/248

**Comment by nickl-** [comment]
Contacted Chris at the supplied e-mail and invited him to comment on this issue.

**Comment by nickl-** [comment]
Alas mail got bounced...
![Screenshot_20221204_071655](https://user-images.githubusercontent.com/1404606/205475789-34f8d6ed-ca9b-4663-9d09-6b0b0e735088.png)

So it is up to us...

Attempted to find pjee but and found this [forum post](https://www.javaprogrammingforums.com/cafe/43328-sun-java-runtime-environment-v3-1-personal-java-emulation-environment-3-1-pjee3-1-a.html) from someone else looking for it too, no response.

Not going to spend more time on this, if there is a need someone will raise it again and we can look into it.

Closed: stale
