### ISSUE TITLE
Memory leak of bsh.Token objects

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#387]
Hello,
please have a look to:
http://issues.apache.org/bugzilla/show_bug.cgi?id=25394#c12

beanshell 2.0b1 has a memory leak of its bsh.Token objects.
The more parsing one does (more scripts one calls) the worst the problem
gets.

This error you can also find in all
Beanshellinterpreters, also without ANT.

Reported by: *anonymous

Original Ticket: "beanshell/bugs/249":https://sourceforge.net/p/beanshell/bugs/249

**Comment by nickl-** [comment]
Need to add this to the memory leak list and test.

**Comment by nickl-** [comment]
parent #661

**Comment by nickl-** [comment]
Duplicate and resolved in #413 profiler heap dump shows that all Token objects are indeed garbage collected.
