### ISSUE TITLE
Implementation-Vendor-Id missing from manifest

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#388]
in bsh-2.0b4.jar, the manifest file 
\(META-INF/MANIFEST.MF\) does not specify an 
Implementation-Vendor-Id. 

It must be added. For instance : 

Implementation-Vendor-Id: org.beanshell 

Reported by: pascal

Original Ticket: "beanshell/bugs/250":https://sourceforge.net/p/beanshell/bugs/250

**Comment by nickl-** [comment]
'Implementation-Vendor-Id' is optional so omitting it will not cause any errors, how is this a bug?

OP fails to motivate a reason for the feature request.

Closed  stale
