### ISSUE TITLE
BSF & Beanshell: Exception Propogation

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#389]
Beanshell implementation of BSFEngine does not 
propogate the actual exception in the BSFException.

This is a serious limitation for the applications that 
dynamically invoke scripts and have a declared throws 
clause in the method signature.

This limitation makes it impossible to use standard 
exception handling to identify and take action on 
certain expected errors.

A small code change in the BeanshellBSFEngine could 
fix the problem.

Current Implementation:
catch \( TargetError e2 \) 
\{
throw new BSFException\(
"The 
application script threw an exception: "
\+ e2.getTarget
\(\)
\+ sourceInfo
\(source,lineNo,columnNo\) \);
\}

Correct Implementation:

catch \( TargetError e2 \) 
\{
throw new BSFException
\(BSFException.REASON\_EXECUTION\_ERROR,
"The 
application script threw an exception: "
\+ e2.getTarget
\(\)
\+ sourceInfo
\(source,lineNo,columnNo\), e2.getTarget\(\) \);
\}

Could someone fix this problem.

Reported by: *anonymous

Original Ticket: "beanshell/bugs/251":https://sourceforge.net/p/beanshell/bugs/251

**Comment by christiancairney** [comment]
I believe my pull request "NPE reporting fix #580" covers this as well?

**Comment by nickl-** [comment]
Tx @christiancairney 

**Closed: Duplicate #572**
