### ISSUE TITLE
Undefined variable gets printed as void

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#393]
Assume that we have an undefined variable x

bsh % System.out.println\(x\);
// Error: EvalError: Undefined argument: x  : at Line:
1 : in file: &lt;unknown file&gt; : \( x \) 

But if we print out this variable with another string:

bsh % System.out.println\(x+" test string"\);
void test string

An undefined variable should not be printed as void. 

Reported by: borgacan

Original Ticket: "beanshell/bugs/255":https://sourceforge.net/p/beanshell/bugs/255

**Comment by drosenbauer** [comment]
... This actually may be a useful way to get around the need to void/null check everywhere! I vote for actually leaving it as-is (or making this an optional strict feature).

**Comment by nickl-** [comment]
Hmmmm very interesting...

```
bsh % void + 7;
// Error: Evaluation Error: illegal use of undefined variable

bsh % void + '';
--> $6 = "void" :String
```

My first thoughts are that it must have something to do with `toString()`.
