### ISSUE TITLE
ParseException.getErrorLineNumber gives NullPointerException

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#395]
Under some situations, ParseException is constructed
with a null "currentToken" member variable. 

A call to ParseException.getErrorLineNumber therefore
fails with a NullPointerException. 

The exception message has however been correctly
populated: 

Parse error at line 35, column 20.  Encountered: \(

The source code line that caused this problem is:

response.setContent\(server.processTemplate\("\_search.html",templateVars,"text/html"\);

That is, there is a missing "\)".

Reported by: jlohrey

Original Ticket: "beanshell/bugs/257":https://sourceforge.net/p/beanshell/bugs/257

**Comment by nickl-** [comment]
Completed with test see #576
