### ISSUE TITLE
Problems with unicode in BeanShell

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#399]
When I type the following command into BeanShell 
2.0b4:
char smiley = '\u263a';

I receive the error:
// Error: Error parsing input: bsh.TokenMgrError: 
Lexical error at line 1, column 97.  Encountered: "u" 
\(117\), after : "\'\\\"

I appreciate any help.

Reported by: jamie_eaton

Original Ticket: "beanshell/bugs/261":https://sourceforge.net/p/beanshell/bugs/261

**Comment by nickl-** [comment]
BeanShell 3.0.0-SNAPSHOT.841 can smile with you

```java
bsh % char smiley = '\u263a';
--> $4 = '☺' :char
```

Cannot reproduce, works as expected
