### ISSUE TITLE
Possible bug in addClassPath with jars and recursion

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#400]
Hi,

It looks like there is a bug in addClassPath when it is
used with jars.

In the attached code sample, I have defined a sequence
in which a series of bsh scripts is called recursively.
Each of these bsh scripts anonymously extends a dummy
java class. 

I’ve included a good version of code that works, and a
bad version that is broken:

In the good version, there are no jar files involved,
and the classpath is not changed within the scripts.

The broken version is the same, except that the bsh
scripts add the jar containing the dummy class to the
classpath. A ClassCast exception occurs when the dummy
class within bean1 gets the instance of the dummy class
within bean2. 

Note that to get this code to run, you must get
bsh-2.0b4.jar and put it the directory with the rest of
the files in good version and broken version, or have
it on your classpah. I'd have put it in myself but
there is an attachment size limit.

Files in good and/or broken versions:

BugRunner: main class for running the code

DummyClass: the class that is anonymously extended
within .bsh scripts

bean1.bsh: a script called by the BugRunner

bean2.bsh: a script that should be recursively called
through the run method of DummyClass within bean1.bsh

compile.bat: script to compile java files in GoodVersion

run.bat: script to run BugRunner within GoodVersion and
BrokenVersion

makejar.bat: script to compile java files and form a
jar containing DummyClass.class within BrokenVersion

Thanks,
Dan Oreper

Reported by: *anonymous

Original Ticket: "beanshell/bugs/262":https://sourceforge.net/p/beanshell/bugs/262

**Comment by nickl-** [comment]
Need to declare home first but then sourcing bean1.bsh and bean2.bsh seems to work without exception.

```java
home = "./";
--> $0 = "./" :String
source("bean1.bsh");
--> $1 = null :null
source("bean2.bsh");
--> $2 = null :null
```
As far as `addClassPath` is concerned also appears to do what is expected:
```java
addClassPath("DummyClass.jar");
--> void
DummyClass dummy = new DummyClass();
--> $0 = DummyClass@12bb4df8 :DummyClass
bsh %
```

**Comment by nickl-** [comment]
There is a problem with DummyClass run, it never exposes the home variable to bean2.bsh, like BugRunner does for bean1.bsh. Easy enough to fix...

Running this on Windows I managed to get the same error as mentioned by OP.

```
starting up
bean1.bsh
java.lang.ClassCastException: class global$anon2 cannot be cast to class DummyClass (global$anon2 is in unnamed module of loader bsh.classpath.DiscreteFilesClassLoader @396a51ab; DummyClass is in unnamed module of loader bsh.classpath.BshClassLoader @5f5a92bb)
```

However...this should be expected.

BugRunner starts an Interpreter which sources bean1.bsh.
The DummyClass jar file is added to the classpath and a new instance of the DummyClass can be anstantiated.
All is well...

But then...
DummyClass run method starts **a new Interpreter** and sources bean2.bsh, without exposing the home variable nor adding the DummyClass jar to the classpath for the new interpreter.

It therefor makes sense that the second interpreter is oblivious about these things and will choke unless correctly informed.

Fix, also add the DummyClass.jar to the 2nd Interpreter's class path and all will be well again.

Closed: works as expected
