### ISSUE TITLE
interface static constants broken.

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#402]
Below snippet defining interface constants should work.

bsh % public interface Directions
\{
static final int NORTH = 0;
static final int SOUTH = 1;
static final int EAST = 2;
static final int WEST = 3;
\}
// Error: EvalError: Typed variable declaration : LHS
\(NORTH\) can't access field:
java.lang.IllegalAccessException: Field is final : at
Line: 1 : in file: &lt;unknown file&gt; : static final int
NORTH = 0 

Reported by: eric_lindahl

Original Ticket: "beanshell/bugs/264":https://sourceforge.net/p/beanshell/bugs/264

**Comment by nickl-** [comment]
Works as expected in 3.0.0-SNAPSHOT.841

```java
bsh % public interface Directions
{
static final int NORTH = 0;
static final int SOUTH = 1;
static final int EAST = 2;
static final int WEST = 3;
}
--> $1 = interface Directions :Class
bsh % Directions.NORTH

--> $2 = 0I :int
bsh % Directions.WEST

--> $3 = 3I :int
```
