### ISSUE TITLE
final modifier not applied

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#403]
The snippet below demonstrates that the "final" field
modifier is not applied.

bsh % class FClass \{ public static final int fnum = 100; \};
bsh % bsh % javap\( FClass \);
Class class FClass extends class java.lang.Object
public bsh.This FClass.\_bshThisFClass
public static bsh.This FClass.\_bshStaticFClass
public static int FClass.fnum
bsh % FClass.fnum = 200;
bsh % print\( FClass.fnum \);
200

Reported by: eric_lindahl

Original Ticket: "beanshell/bugs/265":https://sourceforge.net/p/beanshell/bugs/265

**Comment by nickl-** [comment]
Works as expected in BeanShell 3.0.0-SNAPSHOT.841

```java
bsh % class FClass { public static final int fnum = 100; };
--> $0 = class FClass :Class
bsh % bsh %  javap( FClass );
Class class FClass extends class java.lang.Object
public bsh.This FClass._bshThisFClass :Field
public static final bsh.This FClass._bshStaticFClass :Field
public static final java.lang.String FClass.UUID :Field
public static int FClass.fnum :Field
--> void
bsh % FClass.fnum = 200;
// Error: Evaluation Error: Cannot re-assign final variable fnum. : at Line: 5 : in file: <unknown file> : FClass .fnum = 200
```
