### ISSUE TITLE
Self reference in an Interpreter causes memory leak

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#406]
I have included below the source for a very simple 
test which can be run from the command line. Although 
the test prints out memory usage, the phenomena is 
best observed using a memory tool such a JProfiler. I 
have also attached a screen-shot from JProfiler to 
graphically illustrate the problem.

The core issue is this:
If I setup a self-referencing circle with the 
Interpreter like so \(in standard Java code\):
\{
this.interpreter = new bsh.Interpreter\(\);
this.interpreter.set\( "ref", this \);
\}
It sets up objects in the JVM memory which can never 
ever be garbage collected, even though there is no 
reference to them, and the object which is "this"
is out of scope in the calling method.

This is in contrast to, say a HashSet:
\{
this.set = new HashSet\(\);
onethis.set.add\( this \);
\}
This setup does appear to garbage collect when 
the "this" object goes out of scope.

The code for Test.java is below. Its output follows. 
Note that after the self-referencing setup, roughly 
90Kb has not been garbage collected, compared with 
20Kb for the HashSet and 200 bytes for two simple java 
objects.
```
Before tests
------------
10528
40
------------
Waiting  ...


After object ref test
---------------------
26944
208
---------------------
Waiting  ...


After HashSet test
------------------
158280
22760
------------------
Waiting  ...


After Interpreter test
----------------------
362648
91352
----------------------
Waiting  ...
```

If this test is run with JProfiler, it can be seen 
that both the self-referencing Test objects, and the 
self-referencing HashSet setup are successfully 
garbage collected.

The screen shot from JProfiler shows the objects in 
memory after the object of class Test has gone out of 
scope - at the very final part of the program.

The Interpreter is not garbage collected.
Obviously, if you do this enough in an application, it 
will cripple it for speed and eventually bomb out with 
an "Out of heap space" error.

Any thoughts?

Regards,

Stewart

```java
import java.io.*;
import java.util.*;
import bsh.*;

public class Test {
    private static Runtime r = Runtime.getRuntime();
    private static long baseline = 0L;

    public static void main(String[] args) throws Exception {
        System.gc();
        baseline = (r.maxMemory() - r.freeMemory());

        report("Before tests");

        twoObjectTest();

        report("After object ref test");

        hashSetTest();

        report("After HashSet test");

        interpreterTest();

        report("After Interpreter test");
    }

    private Test ref = null;
    private HashSet<Test> s = null;
    private Interpreter i = null;

    private static void twoObjectTest() {
        Test one = new Test();
        Test two = new Test();

        one.ref = two;
        two.ref = one;
    }

    private static void hashSetTest() {
        Test one = new Test();

        one.s = new HashSet<Test>();
        one.s.add( one );
    }

    private static void interpreterTest() throws EvalError {
        Test one = new Test();

        one.i = new Interpreter();
        one.i.set( "ref", one );
    }

    private static void report(String string) throws IOException {
        char[] lines = new char[string.length()];
        Arrays.fill(lines, '-');
        System.out.println( );
        System.out.println( string );
        System.out.println( lines );
        System.out.println( (r.maxMemory() - r.freeMemory() - baseline) );
        System.gc();
        System.out.println( (r.maxMemory() - r.freeMemory() - baseline) );
        System.out.println( lines );
        System.out.println("Waiting ...");
        new BufferedReader( new InputStreamReader(System.in )).readLine();
    }

    /**
    * I thought this might solve the problem, but of course, it never gets called.
    */
    // finalize() in Object has been deprecated and marked for removal
    //protected void finalize() throws Throwable {
    //    i.set( "ref", null );
    //    i.unset( "ref" );
    //    i = null;
    //}
}
```

[Test.java.txt](https://github.com/beanshell/beanshell/files/10304948/Test.java.txt)

Reported by: scambridge

Original Ticket: "beanshell/bugs/268":https://sourceforge.net/p/beanshell/bugs/268

**Comment by nickl-** [comment]
![beanshell_self_ref](https://user-images.githubusercontent.com/1404606/205412413-c33c6f0f-529c-4067-8430-444ca50ccfc5.png)

**Comment by nickl-** [comment]
parent #661

**Comment by nickl-** [comment]
> The Interpreter is not garbage collected.
> Obviously, if you do this enough in an application, it
> will cripple it for speed and eventually bomb out with
> an "Out of heap space" error.

In fact running this multiple times does not show any leaks:

```

After Interpreter test 1
------------------------
470272
231624
------------------------
Waiting ...


After Interpreter test 2
------------------------
326752
231688
------------------------
Waiting ...


After Interpreter test 3
------------------------
327176
227624
------------------------
Waiting ...


After Interpreter test 4
------------------------
323176
222760
------------------------
Waiting ...


After Interpreter test 5
------------------------
317640
222824
------------------------
Waiting ...


After Interpreter test 6
------------------------
317160
222888
------------------------
Waiting ...


After Interpreter test 7
------------------------
315984
222952
------------------------
Waiting ...


After Interpreter test 8
------------------------
316048
223016
------------------------
Waiting ...


After Interpreter test 9
------------------------
316112
223080
------------------------
Waiting ...
```

Nor am I able to pick up any instances of Interpreter on the heap in profiler.

**Comment by nickl-** [comment]
The increased heap size is to be expected because much more has been added to the heap then a simple `Hashtable` or `Object` instance none of which brought the usage back to base after GC. The fact that the footprint remains the same from a single `new Interpreter()` or multiple self referenced interpreters proving that nothing is leaking.

Sure we can still try and leave a smaller footprint but as for the presence of any memory leak: **cannot reproduce**
