### ISSUE TITLE
Redefining methods do not work if untyped

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#408]
Using bsh-2.0b4.jar

This case works

bsh % foo\(\) \{ print\("hi"\);\}
bsh % foo\(\) \{ print\("bye"\); \}
bsh % foo\(\);
bye

This case fails

bsh % foo\( elem \) \{ print\("a"\);\}
bsh % foo\( elem \) \{ print\("b"\); \}
bsh % foo\(1\);
a                ----&gt; SHOULD BE  "b"

This works 

bsh % foo\( int elem \) \{ print\("a"\);\}
bsh % foo\(int elem \) \{ print\("b"\); \}
bsh % foo\(1\);
b
bsh % 

Thus if you redefine a method which takes untyped 
arguments the redefinition doesnt succeed.
Testing in 2.0b2 this works therefore this is a 
regression in 2.0b\(3 or 4\).

Reported by: *anonymous

Original Ticket: "beanshell/bugs/270":https://sourceforge.net/p/beanshell/bugs/270

**Comment by opeongo** [comment]
This appears to be fixed.  Should be closed.

**Comment by nickl-** [comment]
@opeongo tyvm

**Closed: working**
