### ISSUE TITLE
type error with byte values and operator ^=

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#409]
It seems like the operator ^= is upcasting byte
arguments to ints and causing errors when used.

\-----------------------------
2.0b4 - by Pat Niemeyer \(pat@pat.net\)

bsh % void foo\(\)
\{
byte y = 0;
y ^= 5;
\}

bsh % foo\(\);
// Error: EvalError: Variable assignment: y: Can't
assign int to byte : at Line: 1 : in file: &lt;unknown
file&gt; : y ^= 5 

Called from method: foo : at Line: 1 : in file:
&lt;unknown file&gt; : foo \( \) 

bsh % void foo\(\)
\{
byte\[\] y = new byte\[1\];
byte z = 5;
y\[0\] ^= z;
\}
bsh % foo\(\);
// Error: // Uncaught Exception: null : at Line: 1 : in
file: &lt;unknown file&gt; : y \[ 0 \] ^= z 

Called from method: foo : at Line: 1 : in file:
&lt;unknown file&gt; : foo \( \) 
Target exception: java.lang.ArrayStoreException:
java.lang.IllegalArgumentException: argument type mismatch

\---------------------------

Included an array usage because the error message is
misleading as compared to the simple byte value error
message.

Reported by: tsh

Original Ticket: "beanshell/bugs/271":https://sourceforge.net/p/beanshell/bugs/271

**Comment by opeongo** [comment]
This issue has been fixed.  Should be closed.

**Comment by nickl-** [comment]
@opeongo tyvm

**Closed: working**
