### ISSUE TITLE
Overriden method ignored if method signature isn't public

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#410]
beanshell 2.0b4

I have a base class with a int getSize\(\) method that
returns a default value, and a derived class that
overrides that method and returns a different value.

If I create an instance of the derived class and call
the getSize\(\) method, BeanShell will incorrectly call
the base classes' getSize\(\) method.

If I put a "public" tag on my method, it works 'correctly'.

Example code: class fooderived shows the problem, class
barderived shows the 'workaround'.

\-----------------------------------------
class foobase
\{
int getSize\(\) \{ return 2; \}

\}

class fooderived extends foobase
\{
int getSize\(\) \{ return 4; \}
\}

fooderived aa = new fooderived\(\);
print\(aa.getSize\(\) \);   // incorrectly prints 2

class barbase
\{
public int getSize\(\) \{ return 2; \}
\}

class barderived extends barbase
\{
public int getSize\(\) \{ return 4; \}
\}

barderived bb = new barderived\(\);
print\(bb.getSize\(\) \);   // correctly prints 4

\-----------------------------------------

Reported by: tsh

Original Ticket: "beanshell/bugs/272":https://sourceforge.net/p/beanshell/bugs/272

**Comment by jimjag** [comment]
Bug fixed/no-longer-applicable in 3.0.0-snapshot
