### ISSUE TITLE
Pasting long script in GUI cli causes lock

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#411]
Pasting about 342ish bytes of text \(with ctrl-v\) and
then hitting enter causes BeanShell workspace
window/app to freeze.  Clicking the win32 closewindow
icon \(X\) in upper right corner does not cause app to
exit, however, app is still responsive to dragging by
the title bar, but repainting does not occur if part of
the window contents are overwritten.

This is with bsh-2.0b4.jar, under Windows XP, java jre
1.4.2\_06.

This only happens in the GUI cli, not the text cli.

Here is example text that causes it to freeze on my
machine \(this is example text from a previous bug
report I filed\):

\-------------------------------------------

class foobase \{  int getSize\(\) \{ return 2; \}   \}  class
fooderived extends foobase \{  int getSize\(\) \{ return 4;
\} \}  fooderived aa = new fooderived\(\);
print\(aa.getSize\(\) \);  class barbase \{  public int
getSize\(\) \{ return 2; \} \}  class barderived extends
barbase \{  public int getSize\(\) \{ return 4; \} \}
barderived bb = new barderived\(\); xxxxxxx

\------------------------------------------

I put it all on one line to eliminate any issues with
multi-line parsing problems.

Reported by: tsh

Original Ticket: "beanshell/bugs/273":https://sourceforge.net/p/beanshell/bugs/273

**Comment by opeongo** [comment]
I recall this being an issue in previous versions, but it appears to be fixed in bsh-2.1.  This issue should be closed

**Comment by nickl-** [comment]
@opeongo tyvm

**Closed: working**
