### ISSUE TITLE
Postfix Array Operators (i.e. String s[]) not handled

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#412]
I know this is noted as a known deficiency
\(http://www.beanshell.org/bsh20announce.txt\), but it is
extremely important to beanshell's java compatibility
to be able to declare arrays that allow postfix array
operators.

The great thing about beanshell is the ability to copy
and paste code from an IDE, directly into beanshell,
then back to an IDE or text file when complete.

The problem breaks that, and although there are ways to
get around it, it is so basic to the way most people
declare arrays in java, that it is a must have.

Reported by: *anonymous

Original Ticket: "beanshell/bugs/274":https://sourceforge.net/p/beanshell/bugs/274

**Comment by opeongo** [comment]
I am not sure that I understand what is meant by a postfix array operator in this bug report.

 I have tested postfix array operators on int's (e.g. `a[i]++`) and they work correctly (see attached test script).

The subject mentions string arrays.  What kind of postfix operator can be applied to a string array, other than to the array index or method parameters?

I don't see a bug here, and suggest closing this one. 
[postfix_array.bsh.txt](https://github.com/beanshell/beanshell/files/2307111/postfix_array.bsh.txt)

**Comment by nickl-** [comment]
@opeongo tyvm

**Closed: working**
