### ISSUE TITLE
Memory leak profiler inspection

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#413]
Running bsh-204b version whith jdk 1.4, I'm getting a 
memory leak when calling bsh.eval\(\)
Whith a profiler I can see that after the execution o 
bsh, there are still around 25 Mb in memory, most of 
them in unclaimed bsh.Token objects.
As said in the manula: "...BeanShell Interpreter 
instances were designed to be very light weight. 
Construction time is usually negligible and in simple 
tests, we have found that it is possible to maintain 
hundreds \(or even thousands\) of instances."...
Is there a way to free those Tokens?
The only solution is invoke the Garbage Colector?
Thanks

Reported by: convenio

Original Ticket: "beanshell/bugs/275":https://sourceforge.net/p/beanshell/bugs/275

**Comment by drosenbauer** [comment]
@nickl-, have you looked at this at all? We’re running into this when using Beanshell embedded. I can work on tracking it down if you haven’t yet.

**Comment by nickl-** [comment]
@drosenbauer we need to confirm whether this has been resolved on master, please.

Unfortunately we can't do anything for bsh-204b version anymore. 

This issue, one of many imported from sourceforge which we need help to review, is also very vague.  Do you have example code that shows the leak.

**Comment by nickl-** [comment]
Not enough information

**Comment by opeongo** [comment]
Would be nice to project some day to do a heap dump and look for orphaned objects.

**Comment by nickl-** [comment]
parent #661

**Comment by nickl-** [comment]
Tokens are released via GC but there are still a few other things we may want to tweak. using:  [Heap.java.txt](https://github.com/beanshell/beanshell/files/10304219/Heap.java.txt) Running with 5MB heap size `-Xmx5M`

Heap dump of bsh objects:

![Screenshot_20221226_192317](https://user-images.githubusercontent.com/1404606/209571467-3aa86b42-2984-4cfe-aadc-d80fafdb0108.png)
![Screenshot_20221226_192346](https://user-images.githubusercontent.com/1404606/209571480-468a500e-e665-4876-8ff8-dc499f21cf96.png)

Profiler results from [visualvm](https://visualvm.github.io/download.html)

**Comment by nickl-** [comment]
Interpreter allows for multiple eval calls and for this purpose certain state is kept. Added reset method to release additional resources optional use when completely done with interpreter.
