### ISSUE TITLE
ExternalNameSpace.setMap() causes NPE

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#414]
setMap\(\) sets this.externalMap to null, then calls
this.clear\(\), which tries call this.externalMap.clear\(\).

Reported by: jeffdrost

Original Ticket: "beanshell/bugs/276":https://sourceforge.net/p/beanshell/bugs/276

**Comment by opeongo** [comment]
Looks like fixed in 3c395bb07e157bc1bcfab7d285484495fa61c010

**Comment by nickl-** [comment]
@opeongo tyvm

**Closed: working**
