### ISSUE TITLE
build.xml compile doesn't provide class debug info

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#415]
the bsh.jar classes don't come with debug info \(showing line numbers while debugging\) but from looking at build.xml it looks like the developers do want this.

the build.xml for bsh has a javac with
&lt;javac...
debug="on"
...&gt;

Now due to some problems in ant world, the two valid options are actually debug="off" debug="true".

Once I changed my local build.xml file to debug="true" the generated jar gave me line numbers in stack traces.

Thanks
James Andrews

Reported by: *anonymous

Original Ticket: "beanshell/bugs/277":https://sourceforge.net/p/beanshell/bugs/277

**Comment by opeongo** [comment]
It looks like the ant build.xml is no longer working now that maven is in use.  Should 'build.xml' be removed?

**Comment by nickl-** [comment]
Something that needs to be decided is the multiple release strategy #493  of which we only have reference to in the build.xml

I agree we need to either make ant work as well or drop the `build.xml`

Leaving this open for now...

**Comment by nickl-** [comment]
Will remove build.xml once the information is not required anymore and #493 is resolved.
