### ISSUE TITLE
Problem defining anonymous Action object

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#417]
I tried defining the following:

JMenuItem mi = new JMenuItem\(new AbstractAction\("Item"\) \{
public void actionPerformed\(ActionEvent e\) \{
// your code here
\}
\}\);

which failed though it's valid Java code.

However, this works:

JMenuItem mm = new JMenuItem\(new AbstractAction\(\) \{
public void actionPerformed\(ActionEvent e\) \{
// your code here
\}
\}\);

Seems like not all the AbstractAction constructors are supported \(or perhaps not all anonymous declaration syntax\).

Reported by: gary_nunes

Original Ticket: "beanshell/bugs/279":https://sourceforge.net/p/beanshell/bugs/279

**Comment by opeongo** [comment]
fixed by #488.   This can be closed.
