### ISSUE TITLE
Source code link doesn't work

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#419]
The source code link on http://www.beanshell.org/developer.html to file http://www.beanshell.org/bsh-2.0b4-src.zip does not work. The response is a 404 \(not found\).

Reported by: jaydunning

Original Ticket: "beanshell/bugs/281":https://sourceforge.net/p/beanshell/bugs/281

**Comment by pgiffuni** [comment]
This has been fixed now. Thanks!
