### ISSUE TITLE
Fix build errors on JDK8

### ISSUE THREAD

**Issue by stain** [beanshell/beanshell#42]
See https://travis-ci.org/beanshell/beanshell/jobs/270826681

I think the [jdk7 and jdk6 jobs](https://travis-ci.org/beanshell/beanshell) fail due to Travis no longer support them, but at least the JDK8 build should work.

Errors include:

```
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.375 s <<< FAILURE! - in bsh.ClassGeneratorTest
[ERROR] define_interface_with_constants(bsh.ClassGeneratorTest)  Time elapsed: 0.018 s  <<< ERROR!
bsh.EvalError: Sourced file: inline evaluation of: ``interface Test { public static final int x = 1; } ;'' : Typed variable declaration : LHS (x) can't access field: java.lang.IllegalAccessException: Can not set static final int field Test.x to java.lang.Integer
	at bsh.ClassGeneratorTest.define_interface_with_constants(ClassGeneratorTest.java:77)
[INFO] Running bsh.VarargsTest
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in bsh.VarargsTest
[ERROR] calling_java_varargs_method_should_be_possible(bsh.VarargsTest)  Time elapsed: 0 s  <<< ERROR!
bsh.EvalError: Sourced file: inline evaluation of: ``helper.list(1,2,3);'' : Error in method invocation: Method list( int, int, int ) not found in class'bsh.VarargsTest$ClassWithVarargMethods'
	at bsh.VarargsTest.calling_java_varargs_method_should_be_possible(VarargsTest.java:37)
```

and

```
[ERROR] Tests run: 10, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.975 s <<< FAILURE! - in bsh.SourceForgeIssuesTest
[ERROR] misc_tests(bsh.SourceForgeIssuesTest)  Time elapsed: 0.1 s  <<< ERROR!
bsh.EvalError: Sourced file: inline evaluation of: ``String a; try { 	a = "foobar"; } catch (Exception e) { 	throw e; } return a; ;'' internal Error: null fromValue
	at bsh.SourceForgeIssuesTest.misc_tests(SourceForgeIssuesTest.java:200)
Caused by: bsh.InterpreterError: null fromValue
	at bsh.SourceForgeIssuesTest.misc_tests(SourceForgeIssuesTest.java:200)
[ERROR] sourceforge_issue_1796035(bsh.SourceForgeIssuesTest)  Time elapsed: 0.005 s  <<< ERROR!
bsh.ParseException: 
In file: inline evaluation of: ``byte array[] = new byte[0]; return array; ;'' Encountered "[" at line 1, column 11.
	at bsh.SourceForgeIssuesTest.sourceforge_issue_1796035(SourceForgeIssuesTest.java:160)
[ERROR] sourceforge_issue_1950677(bsh.SourceForgeIssuesTest)  Time elapsed: 0.005 s  <<< ERROR!
bsh.ParseException: Parse error at line 1, column 8 : Error or number too big for integer type: 0xff000000
	at bsh.SourceForgeIssuesTest.sourceforge_issue_1950677(SourceForgeIssuesTest.java:169)
[ERROR] sourceforge_issue_2081602(bsh.SourceForgeIssuesTest)  Time elapsed: 0.112 s  <<< ERROR!
bsh.TargetError: Sourced file: inline evaluation of: ``Object echo(msg, x) {    print(msg + ' ' + x);    return x; } public class A imp . . . '' : Object constructor
	at bsh.SourceForgeIssuesTest.sourceforge_issue_2081602(SourceForgeIssuesTest.java:140)
Caused by: bsh.InterpreterError: Error in class initialization: java.lang.NullPointerException
	at bsh.SourceForgeIssuesTest.sourceforge_issue_2081602(SourceForgeIssuesTest.java:140)
[ERROR] sourceforge_issue_2081602_learning_test(bsh.SourceForgeIssuesTest)  Time elapsed: 0.024 s  <<< ERROR!
bsh.TargetError: Sourced file: inline evaluation of: ``Object echo(msg, x) {    print(msg + ' ' + x);    return x; } public class A imp . . . '' : Object constructor
	at bsh.SourceForgeIssuesTest.sourceforge_issue_2081602_learning_test(SourceForgeIssuesTest.java:127)
Caused by: bsh.InterpreterError: Error in class initialization: java.lang.NullPointerException
	at bsh.SourceForgeIssuesTest.sourceforge_issue_2081602_learning_test(SourceForgeIssuesTest.java:127)
```

and others.

**Comment by stain** [comment]
@nickl and @dougmencken would you mind having a quick look with `mvn` locally with Java 8 and see if this is caused by the recent pull request merges, or if these errors also apply to the tag 2.0b6 with Java 8?  (I might have used Java 7 for that release)

**Comment by nickl-** [comment]
We are doing test driven development, writing tests that fail and then fixing them. This is an easy way for  contributors to see where they can help. At the same time you get to discover the inner workings of the library. 

The source should build with all the VMs since 5-ish (please don't hold me to that) if you disable tests with maven system property `maven.test.skip`. 

Run:

      man clean package install -Dmaven.test.skip=true

Let us know if that treats you better and please, fix some of those annoying tests that are failing . hehehe just teasing =) Seriously let me know and I will look into it.

Sounds like you are up to speed with travis, could you help us get that configured please! It would really solve a lot of hassles!!!

**Comment by nickl-** [comment]
lol @stain I didn't see you made the post too... here I am being all motivating contribution hahaha

**Comment by nickl-** [comment]
confirmed build successful against jdk 7 and 8 with the tests turned off.

Did you expect the tests to pass? I just assumed they were written to be implemented. Are you sure all the source came over to GitHub? Cause many of those tests have no sign of having any implementation... unless I am mistaken.

**Comment by nickl-** [comment]
Ok I can confirm... openJDK 1.6.0 - default java distro for macos doesn't build.

But that is because it can't seem to run maven... I'm running 3.5.0 and it chokes on:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/cli/MavenCli : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
```

**Comment by nickl-** [comment]
This [diff shows the changes](/beanshell/beanshell/compare/6087981aa8aa0911727a0dab897d15c314958217...master), compared to master, since the last successful build an travis.

Ahhh the previous ant build script still succeeded even when tests failed. Even as far back as the [2.0b6 release](https://travis-ci.org/beanshell/beanshell/jobs/110154563) there were tests that failed, only difference now is that maven would exit non 0 when that happens and travis considers it a failure.

**Comment by nickl-** [comment]
Alright then...

 * Travis is configured to skip the tests, also told to cache dependencies and now happily marks our build a success... which makes me happy too.
 * We got our travis bling on the project page configured and all is well.
 * Tests will still fail, and the build too for that matter, when manually running maven without explicitly ignoring  the tests.

If you ace happy too... issue ready to be closed.
