### ISSUE TITLE
XOR not implemented for booleans ?

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#424]
The line:

interpreter.eval\("boolean a=true; boolean b=true; boolean c=a^b; print\(c\)"\);

returns:

bsh.InterpreterError: unimplemented binary operator
at bsh.Primitive.booleanBinaryOperation\(Primitive.java:287\)

although it is valid in Java.

booleanBinaryOperation in Primitive.java does not implements XOR, I guess it lacks something like:

case XOR: return lhs ^ rhs ? Boolean.TRUE : Boolean.FALSE;

Reported by: pascal_meheut

Original Ticket: "beanshell/bugs/286":https://sourceforge.net/p/beanshell/bugs/286

**Comment by nickl-** [comment]
https://github.com/beanshell/beanshell/blob/678e6907c80d5880883648adabc3a759976aecb9/src/main/java/bsh/Operators.java#L189-L191

**Closed: already implemented**
