### ISSUE TITLE
Operator + does not always work with a null String

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#425]
String s=null; print \(s+1\);

returns error:

// Error: EvalError: illegal use of null value or 'null' literal :

instead of "null1" like java does. A workaround is to always start with an empty string: "print \(""+s+1\)".

But it would be better to support it in BSHBinaryExpression.eval by fixing the PLUS case with something like:

case PLUS:
if\(lhs instanceof String || lhs==Primitive.NULL || rhs instanceof String || rhs==Primitive.NULL\)
return lhs.toString\(\) + rhs.toString\(\);

Reported by: pascal_meheut

Original Ticket: "beanshell/bugs/287":https://sourceforge.net/p/beanshell/bugs/287

**Comment by nickl-** [comment]
The implementation wants either a lhs or a rhs string so the following works as expected.

```java
print(s + "1");
null1
```

```java
if(lhs instanceof String || lhs==Primitive.NULL || rhs instanceof String || rhs==Primitive.NULL)
    return lhs.toString() + rhs.toString();

```

I don't believe that can be correct, who is to say the null is a String Type? 

Can reproduce

```java
bsh % print(s + 1);
// Error: Evaluation Error: illegal use of null value or 'null' literal : at Line: 5 : in file: <unknown file> : ) ;

bsh % print(null + 1);
// Error: Evaluation Error: illegal use of null value or 'null' literal : at Line: 6 : in file: <unknown file> : ) ;
```

**Comment by stefanofornari** [comment]
what about using String.valueOf() instead of toString() ?

Ste

**Comment by nickl-** [comment]
We could also cast to string since we've checked `instanceof`. toString was probably used since NPE is not an issue with the Primitives being wrapped at this point.

**Comment by nickl-** [comment]
When applied to numbers it causes an NPE in java.

```
Integer i = null;
i + 1;
// java.lang.NullPointerException

Character c = null;
c + 1;
// java.lang.NullPointerException
```
