### ISSUE TITLE
Parser fails on anonymous classes in Method Invocation

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#426]
When an anonymous class with an overriden method is defined in a method invocation, the parser fails.

For instance:

interpreter.eval\("System.out.println\(new Object\(\) \{ public String toString\(\) \{ return \"hello\"; \}\}\);"\);

returns a parsing error but the code is perfectly valid. 
A simple workaround is to affect the anonymous class to a variable before and passing the variable to the method.

Reported by: pascal_meheut

Original Ticket: "beanshell/bugs/288":https://sourceforge.net/p/beanshell/bugs/288

**Comment by nickl-** [comment]
Can reproduce.

```java
bsh % System.out.println(new Object() { public String toString() { return "hello"; }});
// Error: Parser Error: In file: <unknown> Encountered:  "(" "("  at line 6, column 19.

bsh % // Error: Parser Error: In file: <unknown> Encountered:  ")" ")"  at line 1, column 1.

bsh % --> $5 = "hello" :String
bsh % // Error: Parser Error: In file: <unknown> Encountered:  "}" "}"  at line 1, column 21.

bsh % // Error: Parser Error: In file: <unknown> Encountered:  ")" ")"  at line 1, column 1.

```

The class stirs gets evaluated besides all the complaints .

**Comment by nickl-** [comment]
Fixed

```java
bsh % System.out.println(new Object() {
          public String toString() {
              return "hello";
          }
     });
hello
```
