### ISSUE TITLE
Bean Shell hangs when "Tab" key is pressed

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#427]
Bean shell is wonderfull and i am using xbsh,however there seems to be a problem with xbsh....while typing when "Tab" key is pressed....it hangs. i use kubuntu.

-Ajay Kumar .N.S

Reported by: ajaykumarns

Original Ticket: "beanshell/bugs/289":https://sourceforge.net/p/beanshell/bugs/289

**Comment by nickl-** [comment]
Need more info: how did you run bsh?

**Comment by jimjag** [comment]
Can't reproduce. No info. Stale
