### ISSUE TITLE
missing source download

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#428]
the page
http://www.beanshell.org/developer.html
has a link
that says
Source Snapshot - bsh-2.0b4-src.zip
and points
http://www.beanshell.org/bsh-2.0b4-src.zip

this link seems dead
Gives a page saying

Not Found
The requested URL /bsh-2.0b4-src.zip was not found on this server.

Apache/1.3.37 Server at beanshell.org Port 80

antony.sequeira@gmail.com

Reported by: *anonymous

Original Ticket: "beanshell/bugs/290":https://sourceforge.net/p/beanshell/bugs/290

**Comment by pgiffuni** [comment]
This has been fixed now. Thanks!
