### ISSUE TITLE
exec(String) doesn't work on Linux

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#431]
Runtime.getRuntime\(\).exec\(String\) doesn't workd due to the way Linux parses the commandline. 

Runtime.egtRuntime\(\).exec\(String\[\]\) does work

Reported by: slatemine

Original Ticket: "beanshell/bugs/293":https://sourceforge.net/p/beanshell/bugs/293

**Comment by jimjag** [comment]
Not enough info
