### ISSUE TITLE
\n in string value

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#435]
ClassManagerImpl classManager = new ClassManagerImpl\(\);
NameSpace global = new NameSpace\(classManager, "FlowLevel embedded BeanShell interpreter"\);
Interpreter bshIntepreter = new Interpreter\(null,System.out,System.err,false,global\);

String str = "String \_result = \"aaaa\nbbbb\";";

bshIntepreter.eval\(a\);

Cant evaluate string when there is an \n or \r character

my application get input from the user

Reported by: shay_te

Original Ticket: "beanshell/bugs/297":https://sourceforge.net/p/beanshell/bugs/297

**Comment by nickl-** [comment]
The problem is you need to escape the quotes, same will happen in java.

```java
bsh % String str = "String _result = "aaaa\nbbbb";";
// Error: Parser Error: In file: <unknown> Encountered:  <IDENTIFIER> "aaaa"  at line 28, column 33.

bsh % // Error: Parser Error: In file: <unknown> Encountered:  <STRING_LITERAL> "\";\""  at line 1, column 5.

bsh % bsh % String str = "String _result = \"aaaa\\nbbbb\";";
--> $4 = "String _result = "aaaa\nbbbb";" :String
bsh % String str = "String _result = \"aaaa\nbbbb\";";
--> $5 = "String _result = "aaaa
bbbb";" :String
```

You can now also you single quotes for strings larger than one char, which makes these scenarios a bit easier.
```java
bsh % String str = 'String _result = "aaaa\nbbbb";';
--> $6 = "String _result = "aaaa
bbbb";" :String
```

As you can see the `\n` works as expected.

**Closed:works as expected.**
