### ISSUE TITLE
Wrong static method called

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#437]
I have created and compiled the following Java classes:

A.java:
```java
public class A {
    public static void hello(String message) {
        System.err.println("Hello "+message);
    }
}
```
B.java

```java
public class B extends A {
    public static void hello(String message) {
        System.err.println("Ola "+message);
    }
}
```
I also have a Java test program that calls the static hello method of the B class:

```java
public class Test {
    public static void main(String[] args) {
        B.hello("world");
    }
}
```

When I compile and run the Test class in the java environment, the result is
"Ola world"

If I issue the following in the Beanshell interpreter
`B.hello("world");`
the result is
`"Hello world"`

It looks like the interpreter is looking up the static method from the superclass, and not doing the same thing that Java would do in this case.

Reported by: *anonymous

Original Ticket: "beanshell/bugs/299":https://sourceforge.net/p/beanshell/bugs/299

**Comment by nickl-** [comment]
And the good news is that if it was fixed on the BeanShell2 fork then it is fixed now on BeanShell as well.

```java
public class A {
    public static void hello(String message) {
        System.err.println("Hello "+message);
    }
}
--> $2 = class A :Class
bsh % A.hello("BeanShell");
Hello BeanShell
--> void
public class B extends A {
    public static void hello(String message) {
        System.err.println("Ola "+message);
    }
}
--> $3 = class B :Class
bsh % B.hello("BeanShell");
Ola BeanShell
```

**Closed: working**
