### ISSUE TITLE
Grammar error when defining arrays

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#438]
The form: byte\[\] array = new byte\[0\]; works but the form:  byte array\[\] = new byte\[0\]; throws an exception with message Encountered "\[" at line....

Attached is a simple test file.

Reported by: toomasr

Original Ticket: "beanshell/bugs/300":https://sourceforge.net/p/beanshell/bugs/300

**Comment by nickl-** [comment]
https://github.com/beanshell/beanshell/blob/41352867a2698223d933b13a19d76f5d292cf3a6/src/test/java/bsh/SourceForgeIssuesTest.java#L195-L217

**Closed: fixed**
