### ISSUE TITLE
IllegalAccessException with protected methods in reflection

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#439]
I traced the exception to 
bsh.Reflect:82 with the line contents:
"return invokeMethod\( method, object, args \);"

As I'm running a SVN trunk I just added a method.setAccessible\(true\) and the problem is fixed for me. 

Of-course it depends on developers in charge if this should be added to invokeMethod itself or callers should obey a contract of  invoking only accessible methods and thus seting the accessibility before calling.

Reported by: toomasr

Original Ticket: "beanshell/bugs/301":https://sourceforge.net/p/beanshell/bugs/301

**Comment by nickl-** [comment]
Your second assessment is correct. You need to enable Accessibility for BeanShell to apply reflect sotAccessible for you on privileged members. 

You can check your Accessibility status with `haveAccessibility();`

**Closed: and answered**
