### ISSUE TITLE
Migrate Sourceforge Issues to Github

### ISSUE THREAD

**Issue by nickl-** [beanshell/beanshell#44]
We should probably migrate [these issues on sourceforge](https://sourceforge.net/p/beanshell/bugs/search/?q=%21status%3Awont-fix+%26%26+%21status%3Aclosed-invalid+%26%26+%21status%3Aclosed-later+%26%26+%21status%3Aclosed-duplicate+%26%26+%21status%3Aclosed-out-of-date+%26%26+%21status%3Aclosed-accepted+%26%26+%21status%3Aclosed-remind+%26%26+%21status%3Aclosed-works-for-me+%26%26+%21status%3Aclosed+%26%26+%21status%3Aclosed-fixed) over to here.

I found a tool, [cmungall/gosf2github](/cmungall/gosf2github), which claims to be up for the task. What we need is an export from sourceforge via https://sourceforge.net/p/beanshell/admin/export which I don't have access to. We should also probably make it clear that we've only moved to GitHub and not abandoned the project.

Thoughts?

**Comment by nickl-** [comment]
It appears some of the sourceforge issues were migrated to [pejobo/beanshell2 - issue search results](https://github.com/pejobo/beanshell2/issues?utf8=✓&q=sourceforge) but this can hardly be all of them.

**Comment by nickl-** [comment]
@stain @dleuck @patniemeyer @pgiffuni @simonetripodi Does anyone know what the credentials are for the source forge project, so that we might import those issues here?

I will attempt to contact the sourceforge users dleuck, patn and spestov, indicated as the project maintainers, with the same request.

**Comment by nickl-** [comment]
Still no response from any of the old maintainers to gain access to the sourceforge project for extracting issues. 

I am running out of options here, does anyone have any other suggestions? Anyone know how to contact any of the old maintainers? Please advise...

**Comment by patniemeyer** [comment]
Nick,

Sorry, I didn’t see your earlier email.  I’ll find the credentials.  What exactly are you trying to do?  

Pat

**Comment by patniemeyer** [comment]
Nick, Please contact me at pat@pat.net <mailto:pat@pat.net> and I’ll send you the login info.

Thanks,
Pat

**Comment by nickl-** [comment]
@patniemeyer Awesome!!! Ty for the response =)

I'm on my way to draft a mail. 

>  What exactly are you trying to do?

There are still a bunch of open issues on sourceforge, I am hoping to find a simple way to import/export the sourceforge issues into here so that we can can process through them and see what is till relevant. You have any ideas?

**Comment by nickl-** [comment]
This is really not something I am looking forward to but it needs to be done and while I have the time we might as well. I believe there is a way to import these tickets to GitHub but we need access to the admin section, as far as I can tell. I definitely can't see myself trying to deal, on sourceforge, as an end user... oh the horror.

...this is the outstanding state of affairs.

Bugs 227 Open tickets
Feature Requests 17 Open tickets
Support 7 Open tickets
Patches 15 Open tickets

Dated as recent as September 2017 so there clearly is confusion about where we are at. We really can't afford leading any users astray. Can we?

Still no response from @patniemeyer via e-mail and @dleuck  also appears to be afk.

please assist...

**Comment by nickl-** [comment]
Happiness!!! Ty @patniemeyer for arranging access to sourceforge I now have access. 

Whoop whoop \o/

This issue remains open until the sourceforge issues have been ported to GitHub.

**Comment by nickl-** [comment]
Now that's an anti climax... completed features and patches cross referencing the sourceforge issues while closing them and double checked they are all done.

Next started with bugs, the big one... then after 60 odd the GitHub api starts complaining that I exceeded the rate limit, stopped it immediately wondering what I stand to do to resume it now without resubmitting the successful ones. Probably should also check what the [rate limit](https://developer.github.com/v3/#rate-limiting) is so as not to exceed it, right.

The rate limit is 5000 requests per user per hour. I haven't done a 100 issues yet =/

But that was not even the fun part yet, next thing I refresh and all the issues are gone. Every last one of the newly created issues which I meticulously cross reference checking them one by one all gone. Not All 60 bug issues which apparently exceeded rate limit, gone, the 15 patch issues which I already closed on sourceforge, gone even he 17 feature requests which I finished an hour ago, poof! 

Oh the joyce...

**Comment by nickl-** [comment]
Turned out GitHub flagged the issue importer user and needed me to please explain but from there things ran smoothly.

All done, everything imported which includes closed issues as well.
All sourceforge issues were cross referenced and closed leaving 0 issues still open.
Retired custom user from project members

Now if only there was someone to close all these new issues =)
