### ISSUE TITLE
abstract class handling

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#440]
implementing a java abstract class inside a eval and using outside the interpreter results in a  

java.lang.NoClassDefFoundError: A class required by class: getStrips/BlockNameSpace/BlockNameSpace$2 could not be loaded:
java.lang.NoClassDefFoundError: IllegalName: getStrips/BlockNameSpace/BlockNameSpace$2

Reported by: *anonymous

Original Ticket: "beanshell/bugs/302":https://sourceforge.net/p/beanshell/bugs/302

**Comment by nickl-** [comment]
More info required.

Do you have an example of the code perhaps?
