### ISSUE TITLE
Bug in auto complete: bsh.XThis

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#441]
When I use Auto Complete \(Ctrl + space\) I don't see the available members, but "bsh - bsh.XThis". See the attached screenshot.

I use Eclipse 3.3 Europa.
I run Eclipse on Ubuntu 6.06 Dapper Drake

Reported by: *anonymous

Original Ticket: "beanshell/bugs/303":https://sourceforge.net/p/beanshell/bugs/303

**Comment by nickl-** [comment]
Eclipse auto completion for beanshell scripts will have to be out of scope for now.
