### ISSUE TITLE
Tab completion throws StringIndexOutOfBoundsExceptions

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#443]
I believe this is related to bug \#1675904.

Here is a reproduceable bug with the latest release of BSH:

$ java -jar lib/bsh-2.0b4.jar \# After the shell shows up, just type "sun." and then start hitting tab. Eventually exception starts being thrown.
Start ClassPath Mapping
Mapping: Archive: file:/C:/Tomcat 5.0/webapps/app/WEB-INF/lib/bsh-2.0b4.jar
Mapping: Archive: file:/C:/j2sdk1.4.2\_07/jre/lib/rt.jar
End ClassPath Mapping
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring\(String.java:1444\)
at bsh.util.JConsole.doCommandCompletion\(Unknown Source\)
at bsh.util.JConsole.type\(Unknown Source\)
at bsh.util.JConsole.keyReleased\(Unknown Source\)
at java.awt.Component.processKeyEvent\(Component.java:5061\)
at javax.swing.JComponent.processKeyEvent\(JComponent.java:2388\)
at java.awt.Component.processEvent\(Component.java:4909\)
at java.awt.Container.processEvent\(Container.java:1569\)
at java.awt.Component.dispatchEventImpl\(Component.java:3615\)
at java.awt.Container.dispatchEventImpl\(Container.java:1627\)
at java.awt.Component.dispatchEvent\(Component.java:3477\)
at java.awt.KeyboardFocusManager.redispatchEvent\(KeyboardFocusManager.java:1713\)
at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent\(DefaultKeyboardFocusManager.java:627\)
at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent\(DefaultKeyboardFocusManager.java:831\)
at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions\(DefaultKeyboardFocusManager.java:741\)
at java.awt.DefaultKeyboardFocusManager.dispatchEvent\(DefaultKeyboardFocusManager.java:592\)
at java.awt.Component.dispatchEventImpl\(Component.java:3506\)
at java.awt.Container.dispatchEventImpl\(Container.java:1627\)
at java.awt.Window.dispatchEventImpl\(Window.java:1606\)
at java.awt.Component.dispatchEvent\(Component.java:3477\)
at java.awt.EventQueue.dispatchEvent\(EventQueue.java:456\)
at java.awt.EventDispatchThread.pumpOneEventForHierarchy\(EventDispatchThread.java:201\)
at java.awt.EventDispatchThread.pumpEventsForHierarchy\(EventDispatchThread.java:151\)
at java.awt.EventDispatchThread.pumpEvents\(EventDispatchThread.java:145\)
at java.awt.EventDispatchThread.pumpEvents\(EventDispatchThread.java:137\)
at java.awt.EventDispatchThread.run\(EventDispatchThread.java:100\)

\-------------------------------------

Here is the output from the GUI console window I was hitting TAB in:

\-------------------------------------

2.0b4 - by Pat Niemeyer \(pat@pat.net\)
bsh % sun.
sun.awt.print.NumericField
sun.awt.print.PrintStatusDialog
sun.awt.print.PrintControl
sun.awt.print.AwtPrintControl
sun.awt.print.PrinterListUpdatable
sun.awt.print.PrinterCapabilities
sun.awt.print.PrintDialog
sun.misc.resources.Messages\_zh\_CN
sun.misc.resources.Messages\_ja
sun.misc.resources.Messages\_ko
...
bsh % sun.
sun.awt.print.NumericField
sun.awt.print.PrintStatusDialog
sun.awt.print.PrintControl
sun.awt.print.AwtPrintControl
sun.awt.print.PrinterListUpdatable
sun.awt.print.PrinterCapabilities
sun.awt.print.PrintDialog
sun.misc.resources.Messages\_zh\_CN
sun.misc.resources.Messages\_ja
sun.misc.resources.Messages\_ko
...
sun.misc.resources.Messages\_ko

...

bsh % sun.
sun.awt.print.NumericField
sun.awt.print.PrintStatusDialog
sun.awt.print.PrintControl
sun.awt.print.AwtPrintControl
sun.awt.print.PrinterListUpdatable
sun.awt.print.PrinterCapabilities
sun.awt.print.PrintDialog
sun.misc.resources.Messages\_zh\_CN
sun.misc.resources.Messages\_ja
sun.misc.resources.Messages\_ko
...
sun.misc.resources.Messages\_ko

...

bsh % sun.
sun.awt.print.NumericField
sun.awt.print.PrintStatusDialog
sun.awt.print.PrintControl
sun.awt.print.AwtPrintControl
sun.awt.print.PrinterListUpdatable
sun.awt.print.PrinterCapabilities
sun.awt.print.PrintDialog
sun.misc.resources.Messages\_zh\_CN
sun.misc.resources.Messages\_ja
sun.misc.resources.Messages\_ko
...
sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

bsh % sun.
sun.awt.print.NumericField
sun.awt.print.PrintStatusDialog
sun.awt.print.PrintControl
sun.awt.print.AwtPrintControl
sun.awt.print.PrinterListUpdatable
sun.awt.print.PrinterCapabilities
sun.awt.print.PrintDialog
sun.misc.resources.Messages\_zh\_CN
sun.misc.resources.Messages\_ja
sun.misc.resources.Messages\_ko
...
sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

bsh % sun.
sun.awt.print.NumericField
sun.awt.print.PrintStatusDialog
sun.awt.print.PrintControl
sun.awt.print.AwtPrintControl
sun.awt.print.PrinterListUpdatable
sun.awt.print.PrinterCapabilities
sun.awt.print.PrintDialog
sun.misc.resources.Messages\_zh\_CN
sun.misc.resources.Messages\_ja
sun.misc.resources.Messages\_ko
...
sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

bsh % sun.
sun.awt.print.NumericField
sun.awt.print.PrintStatusDialog
sun.awt.print.PrintControl
sun.awt.print.AwtPrintControl
sun.awt.print.PrinterListUpdatable
sun.awt.print.PrinterCapabilities
sun.awt.print.PrintDialog
sun.misc.resources.Messages\_zh\_CN
sun.misc.resources.Messages\_ja
sun.misc.resources.Messages\_ko
...
sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

bsh % sun.
sun.awt.print.NumericField
sun.awt.print.PrintStatusDialog
sun.awt.print.PrintControl
sun.awt.print.AwtPrintControl
sun.awt.print.PrinterListUpdatable
sun.awt.print.PrinterCapabilities
sun.awt.print.PrintDialog
sun.misc.resources.Messages\_zh\_CN
sun.misc.resources.Messages\_ja
sun.misc.resources.Messages\_ko
...
sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

bsh % sun.
sun.awt.print.NumericField
sun.awt.print.PrintStatusDialog
sun.awt.print.PrintControl
sun.awt.print.AwtPrintControl
sun.awt.print.PrinterListUpdatable
sun.awt.print.PrinterCapabilities
sun.awt.print.PrintDialog
sun.misc.resources.Messages\_zh\_CN
sun.misc.resources.Messages\_ja
sun.misc.resources.Messages\_ko
...
sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

bsh % sun.
sun.awt.print.NumericField
sun.awt.print.PrintStatusDialog
sun.awt.print.PrintControl
sun.awt.print.AwtPrintControl
sun.awt.print.PrinterListUpdatable
sun.awt.print.PrinterCapabilities
sun.awt.print.PrintDialog
sun.misc.resources.Messages\_zh\_CN
sun.misc.resources.Messages\_ja
sun.misc.resources.Messages\_ko
...
sun.awt.print.PrinterCapabilities

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

bsh % sun.
sun.awt.print.NumericField
sun.awt.print.PrintStatusDialog
sun.awt.print.PrintControl
sun.awt.print.AwtPrintControl
sun.awt.print.PrinterListUpdatable
sun.awt.print.PrinterCapabilities
sun.awt.print.PrintDialog
sun.misc.resources.Messages\_zh\_CN
sun.misc.resources.Messages\_ja
sun.misc.resources.Messages\_ko
...
sun.awt.print.PrinterListUpdatable

sun.awt.print.PrinterCapabilities

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.awt.print.PrinterCapabilities

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

bsh % sun.
sun.awt.print.NumericField
sun.awt.print.PrintStatusDialog
sun.awt.print.PrintControl
sun.awt.print.AwtPrintControl
sun.awt.print.PrinterListUpdatable
sun.awt.print.PrinterCapabilities
sun.awt.print.PrintDialog
sun.misc.resources.Messages\_zh\_CN
sun.misc.resources.Messages\_ja
sun.misc.resources.Messages\_ko
...
sun.awt.print.PrintControl

sun.awt.print.AwtPrintControl

sun.awt.print.PrinterListUpdatable

sun.awt.print.PrinterCapabilities

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.awt.print.PrinterListUpdatable

sun.awt.print.PrinterCapabilities

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.awt.print.PrinterCapabilities

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

bsh % sun.
sun.awt.print.NumericField
sun.awt.print.PrintStatusDialog
sun.awt.print.PrintControl
sun.awt.print.AwtPrintControl
sun.awt.print.PrinterListUpdatable
sun.awt.print.PrinterCapabilities
sun.awt.print.PrintDialog
sun.misc.resources.Messages\_zh\_CN
sun.misc.resources.Messages\_ja
sun.misc.resources.Messages\_ko
...
sun.awt.print.PrintStatusDialog

sun.awt.print.PrintControl

sun.awt.print.AwtPrintControl

sun.awt.print.PrinterListUpdatable

sun.awt.print.PrinterCapabilities

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.awt.print.PrintControl

sun.awt.print.AwtPrintControl

sun.awt.print.PrinterListUpdatable

sun.awt.print.PrinterCapabilities

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.awt.print.PrinterListUpdatable

sun.awt.print.PrinterCapabilities

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.awt.print.PrinterCapabilities

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.awt.print.PrintDialog

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_zh\_CN

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ja

sun.misc.resources.Messages\_ko

...

sun.misc.resources.Messages\_ko

...

bsh % sun.

\-------------------------------------

Note: I didn't insert all those extra linefeeds manually. Bean Shell put those on my clipboard running under Sun Java 6 and Windows Server 2000.

Additionally, it's worth noting that I first decided to try reproducing this error because this exception was the last to be thrown before Bean Shell froze hard trying to tab complete something in a project at work, but I am so far unable to reproduce \*that\* bug consistently.

Reported by: smirk-

Original Ticket: "beanshell/bugs/305":https://sourceforge.net/p/beanshell/bugs/305

**Comment by nickl-** [comment]
Doesn't seem to be a problem anymore.
```
bsh % sun.
sun.rmi.server.MarshalInputStream
sun.rmi.server.ActivatableRef
sun.rmi.server.UnicastServerRef2
sun.rmi.server.UnicastServerRef
sun.rmi.server.ActivatableServerRef
sun.rmi.server.WeakClassHashMap
sun.rmi.server.PipeWriter
sun.rmi.server.Activation
sun.rmi.server.ActivationGroupImpl
sun.rmi.server.UnicastRef2
```

**Closed: cannot reproduce**
