### ISSUE TITLE
TargetException should stop script execution

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#446]
When a service object within the script throws an exception, I'd expect that script execution would halt:

Example:

Beanshell Script

```java
public void doSomething(ServiceObject serv)  {
    serv.throwUncheckedException(); //Should stop execution here
    print("this should not run");
}
```

Method invoked in compiled code via:

activeBshInterpreter.eval(beanshellReader).invokeMethod("doSomething",new Object[]{servImpl}, activeBshInterpreter);

Output:
"This should  not run"

Reported by: *anonymous

Original Ticket: "beanshell/bugs/308":https://sourceforge.net/p/beanshell/bugs/308

**Comment by nickl-** [comment]
Seems to be working now.

```java
bsh % doSomething(new Object());
// Error: Evaluation Error: Error in method invocation: Method throwUncheckedException() not found in class'java.lang.Object' : at Line: 10 : in file: <unknown file> : serv .throwUncheckedException ( )

Called from method: doSomething : at Line: 13 : in file: <unknown file> : doSomething ( new Object ( ) )
```

With no further output...

**Closed: cannot reproduce**
