### ISSUE TITLE
Parser doesn't properly grok unicode

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#451]
try this:

print\('\u00FF'\);

It will fail.  I tried various escape patterns, but nothing worked.

ray.bruece@ngc.com

Reported by: *anonymous

Original Ticket: "beanshell/bugs/313":https://sourceforge.net/p/beanshell/bugs/313

**Comment by nickl-** [comment]
Works now...

```java
bsh % print('\u00FF');
ÿ
```

**Closed; cannot reproduce**
