### ISSUE TITLE
octal number problem

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#452]
this works: "a=027;print\(a\);"
but this: "print\(088\);" ends with "Parse error at line 2, column 6.  Encountered: \("

Reported by: *anonymous

Original Ticket: "beanshell/bugs/314":https://sourceforge.net/p/beanshell/bugs/314

**Comment by nickl-** [comment]
Number too large, also doesn't work in java.

**Closed: works as implemented.**
