### ISSUE TITLE
Link to Source-File does not work...

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#454]
The Link to the sources does not work \(http://www.beanshell.org/bsh-2.0b4-src.zip\)

Could you please correct this or give me a link where I could download the file?

thx in advance

nomike aka Michael Postmann

Reported by: nomike

Original Ticket: "beanshell/bugs/316":https://sourceforge.net/p/beanshell/bugs/316

**Comment by pgiffuni** [comment]
This has been fixed now. Thanks!
