### ISSUE TITLE
Scripted interface : problems with boolean in fields

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#456]
When implementing a Java interface with a bsh script, boolean primitive fields values are not retained for several invocations of the scripted interface methods \(although they are retained for int primitive fields, or even Boolean fields\). 

For example, if we have a Java interface called IFoo :
```java
package foo;
public interface IFoo {
    public void run();
}
```
We can define a script which implement this interface:
```java
import foo;
boolean fieldBool = false;
int fieldInt = 0;
Boolean fieldBool2 = false;
void run() {
    fieldBool = ! fieldBool;
    fieldBool2 = ! fieldBool2;
    fieldInt++;
    print("fieldBool: "+fieldBool);
    print("fieldBool2: "+fieldBool2);
    print("fieldInt: "+fieldInt);
}
```

An then evaluate the bsh script to get the Java interface implementation:
```java
Interpreter bsh = new Interpreter();
bsh.eval(script);
IFoo script = bsh.getInterface(IFoo.class);
```

When calling `script.run()`, the value of fieldBool is always false, although the valule of fieldBool2 swtich from false to true as expected.

Reported by: *anonymous

Original Ticket: "beanshell/bugs/318":https://sourceforge.net/p/beanshell/bugs/318

**Comment by nickl-** [comment]
**Closed by commit**
