### ISSUE TITLE
NullPointerException Thrown by Overriden Method

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#457]
The following script throws NullPointerException.

import java.lang.Integer;
import java.sql.Timestamp;

public class A
\{
public A \(int id\)
\{
testMethod\( "I" \);
\}

public void testMethod \(String testString\)
\{
\}

\}

public class B extends A
\{
public B \( int id \)
\{
super \(id\);
\}

public void testMethod \(String testString\)
\{
\}
\}

B mInOut = new B \( 0 \);

By removing the testMethod\(\) in constructor of A, it does not report anymore error. Why?

import java.lang.Integer;
import java.sql.Timestamp;

public class A
\{
public A \(int id\)
\{
// testMethod\( "I" \);
\}

public void testMethod \(String testString\)
\{
\}

\}

public class B extends A
\{
public B \( int id \)
\{
super \(id\);
\}

public void testMethod \(String testString\)
\{
\}
\}

B mInOut = new B \( 0 \);

Reported by: *anonymous

Original Ticket: "beanshell/bugs/319":https://sourceforge.net/p/beanshell/bugs/319

**Comment by nickl-** [comment]
https://github.com/beanshell/beanshell/blob/41352867a2698223d933b13a19d76f5d292cf3a6/src/test/java/bsh/SourceForgeIssuesTest.java#L128-L148

**Closed: fixed**

**Comment by nickl-** [comment]
https://github.com/beanshell/beanshell/blob/41352867a2698223d933b13a19d76f5d292cf3a6/src/test/java/bsh/SourceForgeIssuesTest.java#L154-L183

**Closed: fixed**
