### ISSUE TITLE
Broken link to source code on website

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#458]
The developer page http://www.beanshell.org/developer.html contains a broken link to the 2.0b4 source snapshot at http://www.beanshell.org/bsh-2.0b4-src.zip

Reported by: *anonymous

Original Ticket: "beanshell/bugs/320":https://sourceforge.net/p/beanshell/bugs/320

**Comment by pgiffuni** [comment]
This has been fixed now. Thanks!
