### ISSUE TITLE
Fork to investigate possible merge

### ISSUE THREAD

**Issue by nickl-** [beanshell/beanshell#46]
@jaktao pointed us to [pejobo/beanshell2](/pejobo/beanshell2) in  #45  

Looks like these guys forked us to code.google.com/p/beanshell2 and continued development. That project has come to an end too it seem. Keen to see what progress they made!

**Comment by jaktao** [comment]
This fork is abandoned.

**Comment by nickl-** [comment]
Yes indeed it is rather dead. But they made tons of fixes before its demise. Still not sure what happened yet... google abruptly closed up shop, but surely that's not the reason, why didn't they just move? 

I think it's best to merge as a priority before we drift further apart, it's already a challenge to keep the advances we've made from falling through the cracks and things will only get worse.

I't doesn't seem like they've really added much new functionality but what I've ported so far have been crucial fixes and loads of cleanups in particular getting rid of the 1.1/1.2 backward support spaghetti. There definitely is value there and I wouldn't like to see it go to waste.

**Comment by pejobo** [comment]
We didn't move because this here has been started ;)
Nice to see at least some progress here...

**Comment by nickl-** [comment]
Glad to have your support!

**Comment by nickl-** [comment]
This is complete.
