### ISSUE TITLE
BeanShell code can't be debugged in Eclipse

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#460]
Hi, I think this is not a bug but I didn't find other place to put this requirement. We have beanshells in our project and the only way to debug them is to create a Java class with the code and then instatiate that class in the beanshell, then after all testing is done We copy the code from the class to the beanshell.

It would be great if We can debug the beanshell without the need of creating a separated class, this could avoid errors when copy-pasting the code and make the development faster \(our test connection is really slow\).

We are using Eclipse 3.4 \(Ganymede\).

If there exists a plugin We would appreciate if you tell us what is.

My email: hec50@hotmail.com

Thanks for the great work\!\!\!

Reported by: *anonymous

Original Ticket: "beanshell/bugs/322":https://sourceforge.net/p/beanshell/bugs/322

**Comment by opeongo** [comment]
This is an enhancement request, not a bug.

Could be fixed with a Truffle/Graal implementation (#43) ;)

**Comment by nickl-** [comment]
Tx @opeongo 

Wondering if this is not out of scope for BeanShell as this would be implemented in/for Eclipse to debug bsh scripts.

**Comment by opeongo** [comment]
Definitely out of scope.  I think the flavour de jour is a [language server](https://microsoft.github.io/language-server-protocol/).  Also definitely out of scope.
