### ISSUE TITLE
Debug fails if called method argument is null

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#462]
In bsh.Reflect.java the below code fails if debug is turned on and one of method arguments is null.

Since args\[i\] is null, args\[i\].getClass\(\) throws NullPointerException.

This makes debuging impossible in some cases.

Line:
+" type = "+args\[i\].getClass\(\) \);

Should be:
+" type = "+\(args\[i\] == null ? "void" : args\[i\].getClass\(\)\) \);

private static void logInvokeMethod\( 
String msg, Method method, Object\[\] args \)
\{
if \( Interpreter.DEBUG \)
\{
Interpreter.debug\( msg +method+" with args:" \);
for\(int i=0; i&lt;args.length; i++\)
Interpreter.debug\(
"args\["+i+"\] = "+args\[i\]
+" type = "+args\[i\].getClass\(\) \);
\}
\}

Reported by: *anonymous

Original Ticket: "beanshell/bugs/324":https://sourceforge.net/p/beanshell/bugs/324

**Comment by nickl-** [comment]
https://github.com/beanshell/beanshell/blob/41352867a2698223d933b13a19d76f5d292cf3a6/src/test/java/bsh/SourceForgeIssuesTest.java#L103-L121

**Closed: fixed**
