### ISSUE TITLE
Broken link to 2.0b4 source download

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#466]
Hi,

You have broken link to 2.0b4 source download.
I noticed I can download 2.0b5 if I enter link directly. It may be worth updating download section and source download section of the website.

Sincerely,
Ivica Ceraj

Reported by: iceraj

Original Ticket: [beanshell/bugs/328](https://sourceforge.net/p/beanshell/bugs/328)

**Comment by pgiffuni** [comment]
THis has been fixed now. Thanks!

**Comment by pgiffuni** [comment]
This has been fixed now. Thanks!
