### ISSUE TITLE
Memory leak with WeakReferences

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#467]
Hello,

You have memory leak in the bsh.classpath. ClassManagerImpl. public
void addListener\( Listener l \) \{ at
listeners.addElement\( new WeakReference\( l, refQueue\) \);

Checked with JProfiler in NetBeans.
Objects are added to listeners collection but are never removed, in
short time \(with massive code execution – test stress framework\) it
causes Java Heap Out of Space.
Tested with  Java 1.6

Also bsh.Name and java.util.Hashtable$Entry are massively used just
like native String class\!
The line in code are NameSpace.getNameResolver for java.util.Hashtable
And BSHAmbiguousName. getName for bsh.Name
You should try to tweak its memory usage, since I execute the same
code and it is not complicated, but memory foot print is huge.

Bye\!

Reported by: *anonymous

Original Ticket: [beanshell/bugs/329](https://sourceforge.net/p/beanshell/bugs/329)

**Comment by nickl-** [comment]
https://github.com/beanshell/beanshell/blob/41352867a2698223d933b13a19d76f5d292cf3a6/src/test/java/bsh/SourceForgeIssuesTest.java#L87-L99

**Closed: fixed**
