### ISSUE TITLE
Unicode patch breaks readLine() of JConsole input

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#469]
Attempting something like this:
Reader consoleIn = console.getIn\(\);
BufferedReader bufConsoleIn = new BufferedReader\(\(InputStreamReader\)consoleIn\);
...
String line = bufConsoleIn.readLine\(\);

Will block.

The "unicode patch" applied to acceptLine\(\) in JConsole.java is incompatible with readLine\(\).  This flaw makes JConsole much less useful for applications outside the built-in interpreter.

Reported by: *anonymous

Original Ticket: [beanshell/bugs/331](https://sourceforge.net/p/beanshell/bugs/331)

**Comment by nickl-** [comment]
`console` is undefined

**Closed: cannot reproduce**
