### ISSUE TITLE
bsh.engine.BshScriptEngine impls Compilable, throws Error

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#470]
bsh.engine.BshScriptEngine \(JSR-223 javax.script support\) implements Compilable, indicating to script hosts that the engine currently supports compilation. I believe that a runtime instanceof Compilable and cast is the main way of determining whether pre-compilation to a CompiledScript is supported by the current ScriptEngine.

In BeanShell 2.0b4 the ScriptEngine class bsh.engine.BshScriptEngine implements Compilable, but then goes on to:

public CompiledScript compile\( Reader script \) throws
ScriptException
\{
// todo
throw new Error\("unimplemented"\);
\}

See http://ikayzo.org/svn/beanshell/BeanShell/engine/src/bsh/engine/BshScriptEngine.java

This is unfortunate for clients with pluggable ScriptEngine-s, of which BeanShell may be one, as they can expect to be able to pre-compile scripts due to the presence of the interface, but will always receive the thrown error.

Recommend that the Compilable interface is removed until BeanShell and the BshScriptEngine support compilation.

Reported by: brett_s_r

Original Ticket: [beanshell/bugs/332](https://sourceforge.net/p/beanshell/bugs/332)

**Comment by nickl-** [comment]
https://github.com/beanshell/beanshell/blob/41352867a2698223d933b13a19d76f5d292cf3a6/src/main/java/bsh/engine/BshScriptEngine.java#L174-L205

**Closed: implemented**
