### ISSUE TITLE
Parsing of long hex literals fails

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#471]
Beanshell 2.0b4 cannot parse long hexadecimal literals.

Ex: 
long foo = 0x0000000001L;  
yields the error 
inline evaluation of: \`\`long foo = 0x0000000001L;'' unknown error: For input string: "0x0000000001"

however decimal long literals work \(eg: long foo = 1234556789L; \)

Reported by: jlewis42

Original Ticket: [beanshell/bugs/333](https://sourceforge.net/p/beanshell/bugs/333)

**Comment by nickl-** [comment]
```
bsh % long foo = 0x0000000001L;
--> $4 = 1L :long
```

**Closed: cannot reproduce**
