### ISSUE TITLE
Nullpointer when Interpreter.DEBUG == TRUE

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#472]
Hello,

I am using beanshell version 1.3.0 in DEBUG mode. In the java class bsh.Reflect I get an Nullpointer Exception when my method argument is NULL.
The Nullpointer occured in method invokeOnMethod.

\--&gt; Interpreter.debug\("tmpArgs\[" + k + "\] = " + aobj1\[k\] + " type = " + aobj1\[k\].getClass\(\)\);  // when aobj1\[k\] is null then getClass will cause the NullPointerException

Code:

private static Object invokeOnMethod\(Method method, Object obj, Object aobj\[\]\)
throws ReflectError, InvocationTargetException
\{
Object aobj1\[\];

....

aobj1 = new Object\[aobj.length\];
Class aclass\[\] = method.getParameterTypes\(\);
try
\{
for\(int j = 0; j &lt; aobj.length; j++\)
\{
aobj1\[j\] = NameSpace.getAssignableForm\(aobj\[j\], aclass\[j\]\);
\}

\}
catch\(UtilEvalError utilevalerror\)
\{
throw new InterpreterError\("illegal argument type in method invocation: " + utilevalerror\);
\}
aobj1 = unwrapPrimitives\(aobj1\);
if\(Interpreter.DEBUG\)
\{
Interpreter.debug\("Invoking method \(after massaging values\): " + method + " with tmpArgs:"\);
for\(int k = 0; k &lt; aobj1.length; k++\)
\{
Interpreter.debug\("tmpArgs\[" + k + "\] = " + aobj1\[k\] + " type = " + aobj1\[k\].getClass\(\)\);  // when aobj1\[k\] is null then getClass will cause the NullPointerException
\}

\}
....

Maybe it is possible to get a patch for release 1.3.0 that fixes this error?

Kind regards,

Marco.

Reported by: *anonymous

Original Ticket: [beanshell/bugs/334](https://sourceforge.net/p/beanshell/bugs/334)

**Comment by nickl-** [comment]
**Closed: merged with beanshell2 fork**
