### ISSUE TITLE
Class definition exposes non-public members

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#474]
for example:

class SomeClass\{\};
print\(java.util.ArrayList.serialVersionUID\);

execution attempt should cause error kinda "No static field or inner class: serialVersionUID of class java.util.ArrayList", but it prints field value

used version - 2.0b4

Reported by: ruslanv

Original Ticket: [beanshell/bugs/336](https://sourceforge.net/p/beanshell/bugs/336)

**Comment by nickl-** [comment]
This is because `setAccessibility` was true then BeanShell will use `setAccessible` when using reflection. Accessibility is now false by default and you can check accessibility with `haveAccessibility();`

See:

```
bsh % haveAccessibility();
--> $0 = false :boolean
bsh % print(java.util.ArrayList.serialVersionUID);
// Error: Evaluation Error: No static field or inner class: serialVersionUID of class java.util.ArrayList : at Line: 1 : in file: <unknown file> : java .util .ArrayList .serialVersionUID

bsh % setAccessibility(true);
--> void
bsh % print(java.util.ArrayList.serialVersionUID);
8683452581122892189

```

**Closed: works as implemented**
