### ISSUE TITLE
update the manual to include servlet security

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#475]
Here is a patch to the beanshell manual \(servletmode.xml, which I believe turns into bshmanual.html\) which adds an example configuration to request a password when using the /eval servlet.  This provided a bit more security, and it's important that people know how to set this up.

This adds the security-constraint, login-config and security-role entries needed in the web.xml file.

Reported by: erh

Original Ticket: [beanshell/bugs/337](https://sourceforge.net/p/beanshell/bugs/337)

**Comment by nickl-** [comment]
[servletmode.xml.diff.txt](https://github.com/beanshell/beanshell/files/2259227/servletmode.xml.diff.txt)

**Comment by nickl-** [comment]
Transferred to #82
