### ISSUE TITLE
Misspecified version numbers (breaks maven ranges)

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#478]
The org.beanshell.bsh version numbers are misspecified. 

Rather than 2.0b5 it should be 2.0.5-beta \(c.f. http://www.sonatype.com/books/mvnref-book/reference/pom-relationships-sect-pom-syntax.html\)

The current format of 2.0b5 does not work with maven version ranges - e.g. net.sourceforge.fmpp.fmpp-0.9.14 depends upon org.beanshell.bsh with a version range of \[1.3,2.1\), but since the release of 2.0b5, this no longer works as this cannot be understood as part of a range.

I\'ve also raised this issue with fmpp - c.f. https://sourceforge.net/tracker/?func=detail&aid=3537710&group\_id=794&atid=100794

Reported by: *anonymous

Original Ticket: [beanshell/bugs/340](https://sourceforge.net/p/beanshell/bugs/340)

**Comment by nickl-** [comment]
We are now using the maven release numbers appropriately.

Current build release number: 2.1.0-SNAPSHOT

**Closed: fixed**
