### ISSUE TITLE
Proprietary License notice in javax/script/package.html

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#480]
While most java files faithfully reproduce the official dual license, there is one subdirectory, where files have a contradicting license header:

BeanShell-2.0b5/engine/javax-src/javax/script/*

Here the licensed declaration is:
    /*
     * %W% %E% %U%
     *
     * Copyright 2005 Sun Microsystems, Inc. All rights reserved.
     * SUN PROPRIETARY/CONFIDENTAIL. Use is subject to license terms.
     */</pre>

Please clarify if this is correct.

Reported by: jnweiger

Original Ticket: [beanshell/bugs/342](https://sourceforge.net/p/beanshell/bugs/342)

**Comment by pgiffuni** [comment]
Yes .. this was an issue. At first it was not considered a big issue since the code doesn't mix iwth the generate code so binary versions won't ship any of it.

I recall, when preparing to relicense under the Apache License this code was removed.
