### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#481]
Pat and the beanshell team,

I have been using beanshell since version 1.27. I am 
testing the 2.0 beta.

I write to express my sincere thanks and appreciation 
for a very fine product you have produced.  It is nothing 
short of brilliant.

Please keep up the good work.

Ben

Reported by: *anonymous

Original Ticket: "beanshell/support-requests/1":https://sourceforge.net/p/beanshell/support-requests/1

**Comment by pgiffuni** [comment]
Pat deserves this one :)
