### ISSUE TITLE
Interpreter Identity

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#482]
Hi.

I am using beanshell 2.0b4. I'm using the 
interpreter's "getIntergace\(Class\)" method to obtain an 
object implementing a certain interface, whose methods 
are scripted.

I found the following problem with the objects returned 
by Iterpreter.getIntergace\(Class\):

Executable rule = compiler.compileRule\(br\);
System.out.println\("equals?" + rule.equals\(rule\)\);
System.out.println\("toString?" + rule.toString\(\).equals
\(rule.toString\(\)\)\);

When I execute this, I find that rule.equals\(rule\) always 
returns false.
I came to this because I was having trouble using those 
objects as keys in a hashtable. They never appeared to 
be in the hashtable, and I diagnosed it down to 
the .equals\(\) method of those objects.

Funny thing is that rule.toString\(\).equals\(rule.toString\(\)\) 
does indeed return true. In the mean time I'm planning 
to use rule.toString\(\) instad of rule, as keys for the 
hashtable. However, I fear that maybe the hashcode will 
change in time. żis this a bug, or is this indeed inteded?

thank you for your time

Reported by: *anonymous

Original Ticket: "beanshell/support-requests/2":https://sourceforge.net/p/beanshell/support-requests/2

**Comment by nickl-** [comment]
I don't know what an `Executable` is nor a `compiler` and you never said what interface you are returning from `Iterpreter.getInterface(Class):`

To answer pour question:
> is this a bug, or is this indeed inteded?

The result you get is the result from invoking the `equals` method on that instance, that is the intention

**Comment by nickl-** [comment]
Closed: stale
