### ISSUE TITLE
Cant output text to a file

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#483]
I am trying to output text from beanshell to a file.
Here is the code that I am using:

System.setProperty\("outfile", "C:/temp/test.txt"\);
System.out.println\("hello world"\);
cat\("C:/temp/test.txt"\);

When I run it, "hello world" is printed to the console but 
not to the file specified.

Can you help please?

Reported by: markbrodie

Original Ticket: "beanshell/support-requests/3":https://sourceforge.net/p/beanshell/support-requests/3

**Comment by opeongo** [comment]
Question answer, I suggest to close the ticket

**Comment by nickl-** [comment]
Tx @opeongo 

**Closed: answered**
