### ISSUE TITLE
Interpreter put

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#485]
Hi i use method put of Interpreter class for pass java
class instance to bean shell. How i limit to use only
public method of java instance class?
Now i can invoke olso private and protect method.

thanks

Reported by: webdel

Original Ticket: "beanshell/support-requests/5":https://sourceforge.net/p/beanshell/support-requests/5

**Comment by opeongo** [comment]
I am not able to reproduce this problem.  I have added a test case to see that this works as expected.

**Comment by nickl-** [comment]
Tx @opeongo 

**Closed: resolved**
