### ISSUE TITLE
Applet issue using BeanShell

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#486]
While using BeanShell from within the applet, The JVM 
uses Applet classloader for Std java classes where as 
for classes used in beanshell script it try's to use 
the different classloader which try's to get the 
classes from the server using the AppletCodeBase. 

How can I stop this behaviour and ask it to look for 
classes within the Applet JAR. 

Reported by: sushilkc

Original Ticket: "beanshell/support-requests/6":https://sourceforge.net/p/beanshell/support-requests/6

**Comment by nickl-** [comment]
Apologies for the late response.

[JEP 289](http://openjdk.java.net/jeps/289) deprecates the applet api so I am assuming this is not an issue anymore.

If you do have any more questions feel free to open a new issue.

**Closed: applets deprecated**
