### ISSUE TITLE
Interpreter in Processing IDE

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#487]
Trying to get beanshell working in processing 3.0a5 IDE. Not sure why the processing method calls don't work. Any tips would be much appreciated!

Reported by: rtavakko

Original Ticket: [beanshell/support-requests/7](https://sourceforge.net/p/beanshell/support-requests/7)

**Comment by opeongo** [comment]
There is not enough information here about what the problem is.  I suggest to close this with 'insufficient information to reproduce'

**Comment by nickl-** [comment]
Tx @opeongo 

**Close: insufficient information to reproduce**
