### ISSUE TITLE
NPE in TargetError

### ISSUE THREAD

**Issue by stefanofornari** [beanshell/beanshell#498]
NPE when cause is null in

https://github.com/beanshell/beanshell/blob/merge-fork-beanshell2/src/main/java/bsh/TargetError.java#L75

due to 

https://github.com/beanshell/beanshell/blob/merge-fork-beanshell2/src/main/java/bsh/TargetError.java#L94

I would suggest to check for cause != null in getMessage(),

**Comment by nickl-** [comment]
ouch!! `t.toString()` it just never ends =)

Tx for feedback
