### ISSUE TITLE
(Q) how to access static methods?

### ISSUE THREAD

**Issue by stefanofornari** [beanshell/beanshell#503]
probably a stupid question, but I could not find the answer... how can I access static methods in beanshell? for example:

```
public class Utils {
  public static dosomething() {}
}
```
in bsh:
```
import Utils;

Utils.dosomething();
```
Thanks in advance. #

**Comment by nickl-** [comment]
@stefanofornari 
Did you answer your own question? Because that looks correct. 

You shouldn't need the import unless you supplied another `package` statement earlier.

```java
public class Utils {
  public static dosomething() { print("hello BeanShell"); }
}
--> $3 = class Utils :Class
bsh % Utils.dosomething();
hello BeanShell
--> $4 = null :null
```

But `import static` might be useful...

```java
bsh % import static Utils.dosomething;
--> void
bsh % dosomething();
hello BeanShell
--> $5 = null :null
```

Unless I misunderstand the question...

**Comment by stefanofornari** [comment]
It was indeed a stupid question... it could not find the method because of a mismatch in the parameters...

**Comment by nickl-** [comment]
>  it could not find the method because of a mismatch in the parameters

Lol... yip that would be a problem. Could we perhaps improve the error message to avoid the confusion?

> It was indeed a stupid question

There are no stupid questions... glad you came right.
