### ISSUE TITLE
Memory leak in blocks

### ISSUE THREAD

**Issue by nickl-** [beanshell/beanshell#504]
Consider the following loop:

```java
len = 500000;
cnt = 0;
while (cnt < len) {
    cnt++;
}
```

At best it takes 20s to complete bun run it 10 times and progressively it gets worse while consuming ever more memory.

Profiling output:
```
0 loop from 0 to 500000
84Mb duration:15.15629s
1 loop from 0 to 500000
254Mb duration:19.19166s
2 loop from 0 to 500000
197Mb duration:47.47549s
3 loop from 0 to 500000
399Mb duration:29.29400s
4 loop from 0 to 500000
147Mb duration:77.77562s
5 loop from 0 to 500000
271Mb duration:42.42519s
6 loop from 0 to 500000
353Mb duration:50.50194s
7 loop from 0 to 500000
435Mb duration:54.54047s
8 loop from 0 to 500000
74Mb duration:97.97873s
9 loop from 0 to 500000
214Mb duration:45.45386s
```

The profiling script that produced the output.

```java
import static java.time.Duration.ofNanos;
import static java.lang.Runtime.runtime;
import static java.lang.System.nanoTime;

len = 500000;
for (i=0; i<10; i++) {
    strt = nanoTime();
    cnt = 0;
    print(i+" loop from "+cnt+" to "+len);


    while (cnt < len) {
        cnt++;
    }


    mem = (runtime.totalMemory() - runtime.freeMemory())/1000000;
    d = ofNanos(nanoTime() - strt);
    print(mem+"Mb duration:"+d.getSeconds()+"."+d.toMillis()+"s");
}
```

The main problem lies with the creation of the block scoped namespace, every iteration.

**Comment by opeongo** [comment]
Is the memory really leaking, or are unused objects just waiting for a gc to happen?

What happens to the memory consumption if you put a 
```java
System.gc();
```
prior to the memory size calculation?

**Comment by nickl-** [comment]
@opeongo gc is working as you can see at 7 we used 435MB and at 8 it's down to 74MB so maybe "memory leak" is not the correct description but the exponential reduction in performance alone should be a concern. 500000 repetitions should not take 20 seconds let alone 100 seconds.

If we remove the block it completes in under 5 seconds for all 10 repeats combined.

Give it a try:

```java
import static java.time.Duration.ofNanos;
import static java.lang.System.nanoTime;

len = 500000;
strt = nanoTime();
for (i=0; i<10; i++) {
    cnt = 0;
    while (cnt < len)
        cnt++;
}
d = ofNanos(nanoTime() - strt);
print("duration:"+d.getSeconds()+"."+d.toMillis()+"s");
```

I have it down to 6 seconds now with the block declaration...
