### ISSUE TITLE
Problem unsetting variables in other namespaces

### ISSUE THREAD

**Issue by opeongo** [beanshell/beanshell#505]
There seems to be an error when trying to unset a variable in the bsh.system namespace.  The following bit of code
```java
bsh.system.abcd = 2;
print("bsh.system.abcd should be 2: "+bsh.system.abcd);

unset("bsh.system.abcd");
print("bsh.system.abcd should be void: "+(bsh.system.abcd == void));
```
produces this output:
```text
bsh.system.abcd should be 2: 2
bsh.system.abcd should be void: false
```
Here is a short test script for this problem.
[unset.bsh.txt](https://github.com/beanshell/beanshell/files/2303523/unset.bsh.txt)

**Comment by nickl-** [comment]
Interesting... will have to give this a closer look.

Thoughts off the bat, which may be wrong: afaik system exports to bsh. So what would happen if we try and unset `bsh.abcd` I wonder.

**Comment by nickl-** [comment]
This cannot worked, `arg` will be null because the parameter is called `name`

https://github.com/beanshell/beanshell/blob/84550d0ae7f1a7c79c9f0942609d7970cb807edb/src/main/resources/bsh/commands/unset.bsh#L10-L16

This never worked... From the first commit: https://github.com/beanshell/beanshell/commit/c4fc63a1e39e0637ac17090e4f27c0aec95cc2b9#r94982914

**Comment by nickl-** [comment]
The variable name is definitely not `bsh.system.abcd`, so trying to find this in any name space will be pointless, the variable `bsh.system` points to a separate namespace and `abcd` in contained therein.

Also the unset method on class `Interpreter` is unable to unset the value.

**Comment by nickl-** [comment]
The closest working solution I have found:

```java
BeanShell 3.0.0-SNAPSHOT.2886
bsh.system.abcd = 2;
--> $0 = 2I :int
bsh.system.abcd;
--> $1 = 2I :int
bsh.system.namespace.unsetVariable("abcd");
--> void
bsh.system.abcd;
--> void
bsh.system.abcd == void;
--> $2 = true :boolean
```

**Comment by nickl-** [comment]
Resolved:

```java
bsh.system.abcd = 2;
print("bsh.system.abcd should be 2: "+bsh.system.abcd);

unset("bsh.system.abcd");
print("bsh.system.abcd should be void: "+(bsh.system.abcd == void));
```
produces this output:
```text
bsh.system.abcd should be 2: 2
bsh.system.abcd should be void: true
```
