### ISSUE TITLE
What version 2.0b6 or 2.1.8

### ISSUE THREAD

**Issue by sergioszy** [beanshell/beanshell#510]
I'm confused, in the main page mentions that the latest version is 2.0b6. And below it mentions that it supports variable arguments for the methods. But it does not work. Scanning a bit I found version 2.1.8, but it is not compatible with 2.0b6. Which one supports variable arguments?

Thanks in advance.

Best regards

**Comment by nickl-** [comment]
Ty @pgiffuni 

**Closed: answered**
