### ISSUE TITLE
Implement Compilable for JSR-223

### ISSUE THREAD

**Issue by jmetertea** [beanshell/beanshell#52]
Add JSR-223 javax.script support,

Need to implement Compilable inteface in BshScriptEngine, 
Currently compile throw new Error("unimplemented");

**Comment by nickl-** [comment]
I think this support was enabled on the BeanShell2 fork, please try the [work in progress / merge-fork-beanshell2 branch](https://github.com/beanshell/beanshell/tree/merge-fork-beanshell2) and let us know how it goes.

**Comment by jmetertea** [comment]
Beanshell2 have different license/copyrights than beanshell/apache, is it ok to use the code as is?

**Comment by nickl-** [comment]
Beanshell 2 is abandoned and the only reason beanshell changed over to the apache license was because it went into incubation but that also fell through in the end.

I am not the right the person to decide on which license to use but I doubt anyone will argue against progress.

What are your concerns exactly?

**Comment by nickl-** [comment]
@jmetertea can you confirm whether the merged branch works?

**Comment by jmetertea** [comment]
I modified classes and test it, and the Compilable works in beanshell 1

**Comment by jmetertea** [comment]
I'm not sure, when I did my changes locally (before the merge) it works,
But in the merged branch I failed to execute TestBshScriptEngine
manager.getEngineByName( "beanshell" ) return null
It seems that it has only NashornScriptEngineFactory

**Comment by jmetertea** [comment]
I created a pull request with my changes:
https://github.com/beanshell/beanshell/pull/56

**Comment by nickl-** [comment]
Completed see:

https://github.com/beanshell/beanshell/blob/a6a18efdf4fc6ad0df94e08fe9fffec435acd31f/src/test/java/bsh/TestBshScriptEngine.java#L1-L137
