### ISSUE TITLE
Static import failing with 2.0b6

### ISSUE THREAD

**Issue by DodoMorph** [beanshell/beanshell#520]
Hi I am using jmeter 4.0 which has an updated version of bsh
and now it fails with a static import see sample

static import net.sf.json.JSONSerializer.*;

with dep;
		<dependency>
			<groupId>net.sf.json-lib</groupId>
			<artifactId>json-lib</artifactId>
			<version>2.4</version>
		</dependency>
works with 2.0b4 2.0b5 but not with 2.0b6
gives;
In file: eval stream Encountered "import" at line 1, column 8.

	at bsh.Parser.generateParseException(Parser.java:6106)
	at bsh.Parser.jj_consume_token(Parser.java:5977)
	at bsh.Parser.Block(Parser.java:2771)
	at bsh.Parser.Statement(Parser.java:2668)
	at bsh.Parser.BlockStatement(Parser.java:2819)
	at bsh.Parser.Line(Parser.java:172)
	at bsh.Interpreter.Line(Interpreter.java:1011)
	at bsh.Interpreter.eval(Interpreter.java:641)
	at bsh.Interpreter.eval(Interpreter.java:731)
	at org.epo.beanshell.BeanShell.main(BeanShell.java:26)

**Comment by mohaqueorcl** [comment]
Hi Nick. Do you have an estimate on when the next release will be since 2.0b6 issues are not being addressed?

**Comment by nickl-** [comment]
> Hi Nick. Do you have an estimate on when the next release will be since 2.0b6 issues are not being addressed?

As soon as we complete the [roadmap](
https://github.com/beanshell/beanshell#development-road-map) or the length of a piece of string, whichever is shortest. =)

A major task is getting through all the outstanding issues where you can jump in if you want to help things progressing along faster. Shout if you need more info...

In the meantime you should be able to replace the beanshell.jar with a custom build version... theoretically speaking. That said I have to add that my knowedge of jmeter is absolutely nil so ymmv.

**Comment by jmetertea** [comment]
Hi DodoMorph, Did you try the correct way  import static rather than static import
https://javarevisited.blogspot.com/2012/10/what-is-static-import-in-java-5-example-tutorial.html

**Comment by DodoMorph** [comment]
Hi jmetertea,
Thanks for the tip. Corrected the import and it works perfectly.
