### ISSUE TITLE
Remove built in functions?

### ISSUE THREAD

**Issue by StarTrekRules** [beanshell/beanshell#525]
How can i do this, I am trying to use this as a sort of plugin language.. but dont want the functions that are there interfering, i tried removing them from the commands but i could not build the project when i was done, the jar that resulted was always empty

**Comment by nickl-** [comment]
Yes, the only way commands are accessible is by having them available.

I can't think why the jar would build but be empty, assuming you are skipping tests.

```
mvn -DskipTests
```

Will look into this.

**Comment by nickl-** [comment]
> May i suggest an option to disable the commands inside BeanShell, It would be useful for others who wish to use it as a scripting language as well

If the command cannot be found it is disabled. This allows you to create custom commands.

Still not sure why the jar file should be empty. Doesn't make sense...

**Comment by CSharpandLua** [comment]
It says i should mark things for inclusion but I have no idea how to do that and think it should be the projects job to do that

**Comment by nickl-** [comment]
Not sure this was resolved though.

**Comment by nickl-** [comment]
Removing the commands work as expected.

```shell
$ rm src/main/resources/bsh/commands/*
$ mvn package -DskipTests
$ ll target/bsh-3.0.0-SNAPSHOT.jar
-rw-r--r--  1 interperon  staff   535K 20 Jun 15:08:25 2019 target/bsh-3.0.0-SNAPSHOT.jar
$ unzip -l target/bsh-3.0.0-SNAPSHOT.jar | grep commands
        0  06-20-2019 15:08   bsh/commands/
     3670  06-20-2019 13:06   bsh/commands/dir.class
```

The jar file is not empty and all that remains of the `/bsh/commands` package is the java source (not bsh script) command `dir` which you can also delete and remove before packaging a jar file.

```shell
$ ll src/main/java/bsh/commands
total 16
-rw-r--r--  1 interperon  staff   5.0K 20 Jun 15:03:37 2019 dir.java
```

To return the commands:

```shell
git checkout src/main/resources/bsh/commands
```

See #493 current development for separate distributed artefacts ie.` bsh-core-3.0.0.jar` and `bsh-commands-3.0.0.jar` etc.

**Closed: works as expected**
