### ISSUE TITLE
error: String index out of range

### ISSUE THREAD

**Issue by vpode** [beanshell/beanshell#531]
I have a strange error. maybe anybody has the answer to it.

If I use:

```
i = new Interpreter();

i.eval("import org.opencms.ocee.cluster.*");
execLine = "CmsClusterManager.getInstance().getMacAddress()";

 ret = i.eval(execLine);

%><%=ret%><br/><%

```

I get the method evaluation ok.

but, if I use:

```
i = new Interpreter();

execLine = "org.opencms.ocee.cluster.CmsClusterManager.getInstance().getMacAddress()";

 ret = i.eval(execLine);

%><%=ret%><br/><%
```

then, I get an error message:

> javax.servlet.ServletException: Sourced file: inline evaluation of: ``org.opencms.ocee.cluster.CmsClusterManager.getInstance().getMacAddress();'' unknown error: String index out of range: 3 : at Line: 1 : in file: inline evaluation of: ``org.opencms.ocee.cluster.CmsClusterManager.getInstance().getMacAddress();'' : org .opencms .ocee .cluster .CmsClusterManager .getInstance ( ) .getMacAddress ( ) 

I don't get to see where is the problem.
Anybody can help me?

**Comment by nickl-** [comment]
@vpode strange indeed, are you using the development branch merge-fork-beanshell2?

**Comment by nickl-** [comment]
Cannot reproduce on master.

There has been many fixes made to import.

**Closed: cannot reproduce**
