### ISSUE TITLE
Load resource from a jar.  [proposed feature]

### ISSUE THREAD

**Issue by orbitalair** [beanshell/beanshell#534]
Hi,
First, thanks to everyone working on this project.  

I create projects that are single jar files, and when I put beanshell inside, it needs to load resources from the jar.   Ages ago at 2.0b4  I added another source() input that took a URL.   This allowed me easy way to use scripts from inside a jar by calling ClassLoader.getSystemResource("some_script.bsh").

public Object source( URL url)
public Object source( URL url, NameSpace nameSpace )

Since no one else has ever added this, am I doing it wrong??  

Would this addition and an example of usage be helpful?

**Comment by nickl-** [comment]
> Would this addition and an example of usage be helpful?

Yes please! Perhaps we can combine both functionalities as a seamless fall through.

**Comment by nickl-** [comment]
Source already supports the use of an URL as argument.

https://github.com/beanshell/beanshell/blob/04ae91a212e96c8a39cd4dc82bb52c2df4773cdf/src/main/resources/bsh/commands/source.bsh#L17-L20

Example:

```java
scriptPath = "\bsh_scriphs\some_script.bsh";
bcm = this.interpreter.getClassManager();
url = bcm.getResource(scriptPath);
source(url);
```

**Closed: implemented**

**Comment by nickl-** [comment]
Ahh I see now... this is in the `source` command but not on interpreter.

Fix coming that syncs interpreter and the source command and having support for all:

- String filename
- File file
- URL url

See referenced commit to follow.

**Comment by orbitalair** [comment]
Yes thats correct.   Its for use when you embed the beanshell jar as a
supporting tool inside a single jar application.

I guess not too many do that anymore, but we do.  Its convenient for our
customers to have single jar apps.

I can make an example/template from my working projects, and will do so.

Where can I put it?   I can make my own git project, (tho I like fossil
better) which could be linked, or a zip?

This is the Interpreter.java diff I have made against the last old release
before git.  I think you probably know what to do, but here is how I did it.

39a40
> import java.net.URL;
586a588,622
>
> /**
> Read text from URL and eval it.
> */
>     public Object source( URL url, NameSpace nameSpace )
> throws FileNotFoundException, IOException, EvalError
> {
> BufferedReader sourceIn = new BufferedReader(
>  new InputStreamReader(url.openStream(),"UTF-8")
>  );
>
>
> String filename = url.getFile();
> if ( Interpreter.DEBUG ) debug("Sourcing file: "+ filename);
>
> try {
>  return eval( sourceIn, nameSpace, filename );
>  } finally {
>    sourceIn.close();
>    }
> }
>
>
> /**
> Read text from URL and eval it.
> */
>     public Object source( URL url )
> throws FileNotFoundException, IOException, EvalError
> {
> return source( url, globalNameSpace );
> }
>

Thanks
Joe Robertson
orbitalair@gmail.com

**Comment by orbitalair** [comment]
Sent a gmail reply before realizing that I could reply here.

You assessment is the correct one.  It is needed when creating single jar file apps where you embed beanshell jar as a tool.

Thanks.

**Comment by nickl-** [comment]
@orbitalair There you go...

I am sure these will do the trick.

https://github.com/beanshell/beanshell/blob/b9d3a1b661dbe26ad503a60f4478245acc73eb18/src/main/java/bsh/Interpreter.java#L551-L613

**Comment by nickl-** [comment]
And the command now does the same:

https://github.com/beanshell/beanshell/blob/b9d3a1b661dbe26ad503a60f4478245acc73eb18/src/main/resources/bsh/commands/source.bsh#L12-L23
