### ISSUE TITLE
Gui does not start in java 8 (place holder)

### ISSUE THREAD

**Issue by nickl-** [beanshell/beanshell#543]
Adding this issue on the top of the pile as placeholder and reminder for #4

**Comment by JamesOlvertone** [comment]
Java 11+12:
Couldn't start desktop: Sourced file: inline evaluation of: ``desktop();'' : Method Invocation bcm.getClassPath : at Line: 40 : in file: /bsh/commands/makeWorkspace.bsh : bcm .getClassPath ( ) 

Called from method: desktop : at Line: 1 : in file: inline evaluation of: ``desktop();'' : desktop ( ) 
Target exception: java.lang.NullPointerException

**Comment by nickl-** [comment]
@JamesOlvertone Tx

**Comment by nickl-** [comment]
Closed with #4 placeholder not required anymore.
