### ISSUE TITLE
NullPointerException at bsh.Util.HttpdConnection.run(Httpd.java:100) - by 2.0b6

### ISSUE THREAD

**Issue by plumstar** [beanshell/beanshell#547]
Hello,
    When I use http-client mode to interactive with BeanShell, it occurs NullPointerException at bsh.Util.HttpdConnection.run(Httpd.java:100), version 2.0b6.
    But in master version, Httpd.java:100 already fixd this problem.

**Comment by nickl-** [comment]
Yes we recommend use master

**Comment by plumstar** [comment]
Thanks. It's best to post a new tag.

**Comment by nickl-** [comment]
We will make a new release as soon as the [roadmap](https://github.com/beanshell/beanshell#development-road-map) is complete.

Closed answered.
