### ISSUE TITLE
Untyped variable was accessible globally before bsh-2.0b6 but in bsh-2.0b6 untyped variable is only accessible within the local scope.

### ISSUE THREAD

**Issue by tanwar4you** [beanshell/beanshell#548]
void enteredActive(State state) {
    Log log = LogFactory.getLog();
    if (true) {
        y = 2; // Untyped variable assigned
        int x = 1; // Typed variable assigned
    }

    for (i = 1; i < 2; i++) {
        log.warn("y = " + y);
        log.warn("x = " + x);
    }
}

Result before bsh-2.0b6
y = 2
x = void
Result in bsh-2.0b6
y = void
x = void

**Comment by nickl-** [comment]
bsh-2.0b6 is not supported, please test against master.
