### ISSUE TITLE
How Beanshell dynamic code execution work in run time ? 

### ISSUE THREAD

**Issue by Buhadod** [beanshell/beanshell#549]
Hi all.

I have a question about how Beanshell works. 

Does it take a code as a string and convert it to some sort of class and load it in Java VM? 
or does it interrupt the code line by line and try to emulate what code do (as normal line by line interpreter).

Cause I noticed there is a class loader class in git repo.

https://github.com/beanshell/beanshell/blob/04ae91a212e96c8a39cd4dc82bb52c2df4773cdf/src/main/java/bsh/classpath/BshClassLoader.java#L97

I do understand that in Java there are two ways to load dynamic code. either use classloader lib or dexclassloader. So, I wonder if beanshell use any one of these.

lets assume that we have the following code.

```
Interpreter i = new Interpter();
i.eval("int x;");
i.eval("x = 1+2");
```

so in this case, how eval works in runtime. does it create a class for (int x) command and execute it. then create another class for all previous code (int x and x = 1+2) and execute both of them.
Please, may you verify?

Thanks.

**Comment by nickl-** [comment]
It is not clear what exactly you are asking so I am not sure how to proceed with an answer.

For instance your code example refers to `int x;` which doesn't make any sense as `int` is a primitive and not a class so it is unclear where you aim to go with this illustration.

The only difference between what you refer to as classloader lib and dexclassloader is that the latter 
loads classes from apk files, aside from that they serve the same purpose. The BeanShell classloader allows us to load classes per interpreter instance, BeanShell can use any compiled java classes.

@Buhadod  Please be more specific if this did not answer your question.

**Comment by nickl-** [comment]
You might also find the answers you are looking for from the documentation.

http://beanshell.org/manual/contents.html

These are by no means up to date but most of the original concepts still apply today.

**Comment by nickl-** [comment]
@Buhadod  #501 has a section titled Works like JAVA which can give additional insights.

**Closed: answered**
