### ISSUE TITLE
Untyped variable was accessible globally before bsh-2.0b6 but in master/bsh-2.0b6 untyped variable is only accessible within the local scope.

### ISSUE THREAD

**Issue by tamminenih** [beanshell/beanshell#550]
Script used to test is as follows.I have taken screenshots of the result for the script in all master , bsh-2.0b6.jar and bsh-2.0b1.jar.
As per the documentation,the untyped variable is global scoped but it is not working as expected.
![beanshell_documentation_Reference](https://user-images.githubusercontent.com/6551494/58147153-d3a06480-7c76-11e9-88fa-048d65f205b1.PNG)

================================= 
foo() {
	 if (true) {
        y = 2; // Untyped variable assigned
        int x = 1; // Typed variable assigned
		print("Inside if block");
		print(" y = " + y);
        print("x = " + x);
    }
	print("outside if block");
	    print("y = " + y);
        print("x = " + x);
}
foo();
========================================
![untypedVariable_block_scoping_Issue_b6](https://user-images.githubusercontent.com/6551494/58146506-0dbc3700-7c74-11e9-8e26-cafae55378f0.png)
![untypedVariable_block_scoping_Issue_master](https://user-images.githubusercontent.com/6551494/58146507-0dbc3700-7c74-11e9-9526-54c6cc10f4da.png)
![untypedVariable_block_scoping_noIssue](https://user-images.githubusercontent.com/6551494/58146508-0dbc3700-7c74-11e9-8763-637052c1d232.PNG)

**Comment by tamminenih** [comment]
Any update on this.

**Comment by nickl-** [comment]
We do not support  **bsh-2.0b6** please use master.

**Comment by tamminenih** [comment]
We have used master to test and it is not working as expected.Please read my comments in the issue created.
