### ISSUE TITLE
Untyped variable is not accessible globally in master

### ISSUE THREAD

**Issue by tamminenih** [beanshell/beanshell#554]
As per the documentation,the untyped variable is global scoped but it is not working as expected in master.
Documentation reference:
![documentationReference](https://user-images.githubusercontent.com/6551494/58570825-40f35d00-8256-11e9-980d-7ade369e4436.png)

Script to test:
-------------------------------------------------
foo() {
if (true) {
y = 2; // Untyped variable assigned
int x = 1; // Typed variable assigned
print("Inside if block");
print(" y = " + y);
print("x = " + x);
}
print("outside if block");
print("y = " + y);
print("x = " + x);
}
foo();
---------------------------------------------------------
Script execution in master:
![master_script_execution](https://user-images.githubusercontent.com/6551494/58570980-90d22400-8256-11e9-9e0c-280a62bb4a01.png)

**Comment by nickl-** [comment]
Beanshell now follows block scope rules as per JAVA for variables. Variables typed or untyped are only accessible inside the block where it was declared.

If you change your script:

```java
foo() {
    y = null; // Untyped variable declared
    int x; // Typed variable declared

    if (true) {
        y = 2; // Untyped variable assigned
        x = 1; // Typed variable assigned
        print("Inside if block");
        print(" y = " + y);
        print("x = " + x);
    }
    print("outside if block");
    print("y = " + y);
    print("x = " + x);
}
foo();
```

It should work as before.

**Close: Works as implemented**

**Comment by nickl-** [comment]
@tamminenih  Thank you for using and testing master in preparation for official release.
