### ISSUE TITLE
Can't build b

### ISSUE THREAD

**Issue by sergioszy** [beanshell/beanshell#559]
Can't build 3.0.0-SNAPSHOT

this is the error
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project bsh: Compilation failure
[ERROR] /home/local/beanshell-master/src/main/java/bsh/BSHArrayInitializer.java:[277,32] cannot find symbol
[ERROR]   symbol:   method jjtGetChildren()
[ERROR]   location: variable node of type bsh.Node

**Comment by nickl-** [comment]
@sergioszy  My sincerest apologies for the inconvenience!

The [build is now successful](https://travis-ci.org/beanshell/beanshell/builds/546225986?utm_source=github_status&utm_medium=notification) with all unit tests passing.

**Closed: fixed**

**Comment by sergioszy** [comment]
No problem!
Thank you very much for the project, it is great and we need it very much.
