### ISSUE TITLE
Eval function through function pointer

### ISSUE THREAD

**Issue by morris821028** [beanshell/beanshell#563]
Hi,

I have a scenario about communication cost. In following example, it spent most of time on parse the string.

```java
package bsh;

import java.util.Scanner;

public class PerformanceStateTest {
	public static String getName(String s) {
		return s + "A";
	}
	
	public static void main(String[] args) {
		final Interpreter interpreter = new Interpreter();

		long start;
		long end;
		
		Scanner cin = new Scanner(System.in);
//		
		cin.next();
		
		try {
			interpreter.eval("import bsh.PerformanceStateTest;");
			interpreter.eval("String getName(String s) { return \"\" + PerformanceStateTest.getName(s); }");
		} catch (EvalError e) {
			e.printStackTrace();
		}
		
		start = System.currentTimeMillis();
		try {
			String v = null;
			for (int i = 0; i < 500000; i++) {
				v = (String) interpreter.eval("getName(\"123\")");
			}
			System.out.println(v);
		} catch (EvalError e) {
			e.printStackTrace();
		}
		end = System.currentTimeMillis();
		final long goldTime = end - start;
		System.out.printf("time %d", goldTime);
	}
}
```

![Visual VM - Sampling Snapshot](https://user-images.githubusercontent.com/4697855/61180582-31d03f00-a64b-11e9-9796-da7d1d32d355.png)

I think we could provide a BSHFunction by `interpreter.getFunc(String name);`. And then, use `func.invokeMethod(args)`. They should be more efficient.

```java
BSHFunction func = interpreter.getFunc("getName");
Object[] args = new Object[]{"123"};
v = func.invokeMethod(args);
```

**Comment by morris821028** [comment]
Solution: 5x faster

```java
try {
	BshMethod method = interpreter.getNameSpace().getMethod("getName", new Class<?>[] { String.class });
	String v = null;
	for (int i = 0; i < 500000; i++) {
//				v = (String) interpreter.eval("getName(\"123\")");
		v = (String) method.invoke(new Object[] {"123"}, interpreter);
	}			
	System.out.println(v);
} catch (EvalError | UtilEvalError e) {
	e.printStackTrace();
}
```

**Comment by nickl-** [comment]
@morris821028  You can also use the class `bsh.PreparsedScript` which is similar to what you are doing.

**Comment by morris821028** [comment]
@nickl-  Thanks for your reminder.

It seems that one source one method. If one source has multiple methods or have some dependent source, the total code size in memory will grow.

In real world, I need to use `getCommand()` to find the methods from `importCommands()`.

**Comment by nickl-** [comment]
@morris821028 When doing millions of iterations the parallel garbage collector stumbles and performance starts degrading exponentially. See [this comment](https://github.com/beanshell/beanshell/issues/529#issuecomment-505395963) for more details and rather use `-XX:+UseSerialGC` when these symptoms appear.
