### ISSUE TITLE
Compiling from source missing ParserConstants.java and Token.java in master

### ISSUE THREAD

**Issue by efjoubert** [beanshell/beanshell#567]
Compiling from source missing ParserConstants.java and Token.java in master. These files are not in src/java/bsh . I am missing some files which is generated by javacc that ar missing in master. Are they not checked in....

**Comment by nickl-** [comment]
Only the modified sources originally generated by javacc are being source controlled. If you are using maven the pom includes a javacc plugin to generate the outstanding sources if required.

The preferred method to build the sources are with:
```
mvn install
```

These files, generated by javacc and jjtree, will be located at `target/generated-sources` from where they are compiled and included in the distribution.

Having to guess why this is a problem for you:
You can add these generated sources to your IDE source path, if this is why you are having problems. If you are manually generating the javacc parser source these sources will need to be included accordingly.

More information about what exactly you are trying to do is required if the above stabs at guessing your problem missed.

**Comment by efjoubert** [comment]
Will do so just want use the latest version of beanshell in back office
system that Im building

**Comment by nickl-** [comment]
Feel free to shout if you have and problems!

**Closed: resolved**
