### ISSUE TITLE
Beanshell via BSF unhelpful Null Pointer Exception in line 0 issue

### ISSUE THREAD

**Issue by christiancairney** [beanshell/beanshell#572]
Hi

I found when using BeanShell via BSF we get unhelpful error messages, such as 

> Null Pointer Exception in line 0

In the stack trace I don't see a lot of information to help me track down the problem.  I found the problem was with the  bsh.util.BeanShellBSFEngine class, attached is my fix for this:

[BeanShellBSFEngine.zip](https://github.com/beanshell/beanshell/files/3871592/BeanShellBSFEngine.zip)

I'm currently using this fix and it reports the exact line number and code details of the issue, hope this helps.

**Comment by opeongo** [comment]
The best way to get this change in to the system is to fork the repository, make and test your change, and then send a pull request.

**Comment by christiancairney** [comment]
Thanks opeongo, and will do!

**Comment by christiancairney** [comment]
FYI Pull request: NPE reporting fix #580

**Comment by nickl-** [comment]
Thank you for supplying a solution, please see review comments at PR and help us work on it to get it committed.

**Comment by Christian-Cairney-sp** [comment]
Hi Nickl, I've responded to your comments on my PR as your suggestions will break Exception chaining, BR
