### ISSUE TITLE
Performance issue while executing logic via beanshell script vs calling external Java class

### ISSUE THREAD

**Issue by ajain-adeptia** [beanshell/beanshell#581]
We have a Java plugin that replaces the pipe character to the hyphen (or dash) in the input file and are using BeanShell API to evaluate the plugin script.

**Version**: 2.0b6 (we also tried the same with v3.0 SNAPSHOT JAR with same results)

**Code**:
```java
bsh.Interpreter interpreter = new bsh.Interpreter();
String script = new String(Files.readAllBytes(Paths.get(scriptFile)));
try {
	interpreter.eval(script);
} catch (EvalError e) {
	e.printStackTrace();
}
```

**Approach 1**:

1. Write the complete logic in a script file as defined in the attached file "Plugin_ReplaceChar.txt".
2. Execute the script file via BeanShell.

Execution time: 60 seconds

**Approach 2**:

1. Write the logic in a Java file as defined in the attached file "GBICharConverter.java".
2. In the script file, call the Java file as defined in the attached file "Plugin_JavaCall_ReplaceChar.txt".
3. Execute the script via BeanShell.

Execution time: 1 second (with the same input file)

**Question**:  With approach 1, why it is taking so much time to execute the same logic in comparison to approach 2 where the logic is moved to the Java file?

[Plugin_JavaCall_ReplaceChar.txt](https://github.com/beanshell/beanshell/files/4047710/Plugin_JavaCall_ReplaceChar.txt)
[Plugin_ReplaceChar.txt](https://github.com/beanshell/beanshell/files/4047711/Plugin_ReplaceChar.txt)
[GBICharConverter.txt](https://github.com/beanshell/beanshell/files/4047729/GBICharConverter.txt)

**Comment by nickl-** [comment]
The java call from "Plugin_JavaCall_ReplaceChar.txt"

```java
new GBICharConverter().replaceChar("C:/test/test.csv", "C:/test/output.csv", '|', '-');
```

and the bsh script from "Plugin_ReplaceChar.txt"

```java
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;


String repositoryIN = "C:/test";
String filename_in = "input.csv";
String filename_out = "output.csv";

char charToBeReplaced = '|';
char charToBeReplacedWith = '-';

String file_in = repositoryIN + "/" + filename_in;
String file_out = repositoryIN + "/" + filename_out;

FileOutputStream fos = null;
FileInputStream fis = null;
try {
	fis = new FileInputStream(new File(file_in));
	fos = new FileOutputStream(new File(file_out));
	byte[] buffer_in = new byte[4096];
	byte[] buffer_out = new byte[4096];
	int read = 0;
	while ((read = fis.read(buffer_in)) > 0) {
		for (int i = 0; i < read; i++) {
			char c = (char) buffer_in[i];
			if (c == charToBeReplaced) {
				c = charToBeReplacedWith;
			}
			buffer_out[i] = ((byte) c);
		}
		fos.write(buffer_out);
		fos.flush();
	}
} catch (Exception e) {
	e.printStackTrace();
} finally {
	if (fis != null) {
		try {
			fis.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	if (fos != null) {
		try {
			fos.flush();
		} catch (IOException e1) {
			e1.printStackTrace();
		}
		try {
			fos.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
```

**Comment by nickl-** [comment]
> **Question**: With approach 1, why it is taking so much time to execute the same logic in comparison to approach 2 where the logic is moved to the Java file?

The difference in performance is because while java is compiled code BeanShell needs to be interpreted and you weren't completely fair wit your benchmarks.

### Java class

- syntax is parsed during compile time (not included in your benchmark) 
- source code is compiled to byte code (not included in your benchmark) 
- byte code is executed

### Beanshell script

- syntax is parsed during execution (interpreted)
- an Abstract syntax tree (AST) is instantiated representing the code
- the AST is evaluated 

## Conclusion

If you want to make a fair comparison also wrap the code in a function, also exclude the initial parsing and AST instantiation (which was not included for compiling the java code) and repeat the execution several times.

The java code will still be faster but at least it will be a more realistic comparison.

```java
replaceChar(file_in, file_out, charToBeReplaced, charToBeReplacedWith) {
    try {
	fis = new FileInputStream(new File(file_in));
	fos = new FileOutputStream(new File(file_out));
	byte[] buffer_in = new byte[4096];
	byte[] buffer_out = new byte[4096];
	int read = 0;
	while ((read = fis.read(buffer_in)) > 0) {
		for (int i = 0; i < read; i++) {
			char c = (char) buffer_in[i];
			if (c == charToBeReplaced) {
				c = charToBeReplacedWith;
			}
			buffer_out[i] = ((byte) c);
		}
		fos.write(buffer_out);
		fos.flush();
	}
    } catch (Exception e) {
	e.printStackTrace();
    } finally {
	if (fis != null) {
		try {
			fis.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	if (fos != null) {
		try {
			fos.flush();
		} catch (IOException e1) {
			e1.printStackTrace();
		}
		try {
			fos.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
    }
}

i = 100;
while (i-- > 0)
      replaceChar("C:/test/test.csv", "C:/test/output.csv", '|', '-');
```

and compare i to: 

```java
int i = 100;
while (i-- > 0)
    new GBICharConverter().replaceChar("C:/test/test.csv", "C:/test/output.csv", '|', '-');
```

Let us know what you found.

**Comment by nickl-** [comment]
Closed: asked and answered
