### ISSUE TITLE
Can we use the code having lambda expressions and generics and methods of Streams API with beanshell interpreter?

### ISSUE THREAD

**Issue by Sanket110297** [beanshell/beanshell#589]
Will eval method supports something like following:

1. `List<Integer> a=new ArrayList<>();`
2. `a.stream().map(value->value)....... something`

**Comment by nickl-** [comment]
> Will eval method supports something like following:
> 
>     1. `List<Integer> a=new ArrayList<>();`

Yes this works:

```java
bsh % List<Integer> a=new ArrayList<>();
--> $0 = [] :List
```

>     2. `a.stream().map(value->value)....... something`

Streams will work, lambdas won't.
