### ISSUE TITLE
JavaCC 21

### ISSUE THREAD

**Issue by revusky** [beanshell/beanshell#591]
Since you guys are heavy users of that legacy dinosaur JavaCC project, I thought you might find an update on the work going on in the space to be useful. Or interesting, at least. I'm referring to [JavaCC 21](https://javacc.com/) which is my second run at reviving JavaCC as an actively developed project. The first attempt was back in 2008 and I decided, after dropping it for a decade to pick it up again. Anybody interested can read the whole history of that [here.](https://doku.javacc.com/doku.php?id=ancient_history)

There are a lot of things to tell you about but this may be the biggest one:

You know, there's this very longstanding bug in JavaCC that nested lookahead does not work properly. That is basically a showstopper in terms of any very sophisticated use of the tool. You can't use LOOKAHEAD recursively. It's [right there in their FAQ.](https://javacc.github.io/javacc/faq.html#question-4.8)

Anyway, on my last iteration of refactoring and cleaning up the code, I realized that nailing that bug was now low-hanging fruit. [So I fixed it.](https://javacc.com/2020/07/15/nested-syntactic-lookahead-works/)

I hope that piques people's interest. There are a bunch of other quite nifty improvements that came on line in the last few months. For example, this [new up-to-here marker construct](https://javacc.com/2020/07/31/new-feature-for-scan-up-to-here/) or this new feature I call [Lookbehind](https://javacc.com/2020/07/24/lookbehind-predicates/).

Well, that's enough said for now. Pardon the shameless plug, but you have to understand that this project is at a severe disadvantage visibility-wise so there is really little choice. Besides, somebody should break it to you guys that you are using something that is totally obsolete!

**Comment by stefanofornari** [comment]
Hi Jonathan,
very cool to know! is JavaCC 21 already in a maven repository? I could not
find it and I could not find any mention of it.

Stefano

PS: https://parsers.org/ seems to be down

**Comment by revusky** [comment]
JavaCC 21 is not currently on Maven Central. That is on my TODO list but
has kind of fallen through the cracks. So far... The project is rather
undermanned right now. Meanwhile, you can download the jar [here](
https://javacc.com/download/javacc-full.jar)

Parsers.org is up, I'm pretty sure. You may have to hit reload a few times,
typically the first time you visit the site. But after that it tends to
work okay. There does seem to be a glitch in the Discourse installation,
and that is also on my TODO list to look into.

**Comment by nickl-** [comment]
Tagging #90 as related

**Comment by nickl-** [comment]
Managed to configure maven to generate sources based on the example java grammar, using the following configuration:

```xml
      <plugin>
        <groupId>com.googlecode.maven-download-plugin</groupId>
        <artifactId>download-maven-plugin</artifactId>
        <version>1.6.8</version>
        <executions>
          <execution>
            <id>install-javacc21</id>
              <phase>generate-sources</phase>
            <goals>
              <goal>wget</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <outputDirectory>${user.home}/.m2/</outputDirectory>
          <url>https://javacc.com/download/javacc-full.jar</url>
          <unpack>false</unpack>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <id>generate-ast</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>exec</goal>
            </goals>
            <configuration>
              <executable>java</executable>
              <commandlineArgs>-jar ${user.home}/.m2/javacc-full.jar -n -q -d ../../target/generate-sources -jdk18 examples/java/Java.javacc</commandlineArgs>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

It does not consider the project sources of overwritten files to exclude, like the `ph` plugin does, but this is fine for now as the modified sources will need to be compared and updated anyway.

**Comment by nickl-** [comment]
Current progress and concerns:

Managed to configure the package and node prefix as per the current implementation.

Wondering what the best way would be to add our customization to the standard java grammar while allowing easy updates from upstream as the grammar evolves.

Can't find any settings to not generate the visitor code, this was optional (I think) for the current solution as there appears to be commented settings in our grammar for such:

https://github.com/beanshell/beanshell/blob/270dd71ab97ce20096275294504f40b43ed1a5a7/src/main/jjtree/bsh.jjt#L47-L54

I don't believe we need to use a visitor which makes having the code generated redundant, I might be wrong.

**Comment by nickl-** [comment]
Strong motivation for changing over to javacc21, from [the documentation](https://doku.javacc.com/doku.php?id=key_differences).

> JavaCC 21 is being actively developed
> JavaCC 21 now supports the full Java language up through Java 15. Note that this grammar successfully parses all the Java source code in the OpenJDK 15, as well as all the Java source code in JRuby, Jython, and FreeMarker. So, if anybody needs a Java code parser for use in their own projects, this is quite usable!

I believe the support is now JAVA 19, correct me if I am wrong, updated since this documentation was written.

If there is a better way to fulfill our number 1 mandate: to work like JAVA does, at least as far as parsing valid source goes, I am keen to know.

**Comment by revusky** [comment]
Yesterday I had a bit of insomnia and was actually looking at your bsh.jjt file. It requires more adjustment than I would have thought. The biggest single problem that you will run into is here: https://github.com/beanshell/beanshell/blob/master/src/main/jjtree/bsh.jjt#L800

Though, actually, I think the same construct occurs in 14 other places. And, to be honest, this could be considered a little glitch in the JavaCC 21 syntax/grammar. Let me explain:

In this code:

    void ConditionalOrExpression() :
    { Token t=null; }
    {
      ConditionalAndExpression()
      ( ( t = <BOOL_OR> | t = <BOOL_ORX> )
        ConditionalAndExpression()
        { jjtThis.kind = t.kind; } #BinaryExpression(2) )*
    }

The last line, you have:

        { jjtThis.kind = t.kind; } #BinaryExpression(2) )*

The problem is that the code action before `#BinaryExpression(2)` is going to eat the following `#` character. You see, in JavaCC21, a code block can be followed by `#` to indicate that it is also used in lookahead. If there is no `#` after the closing brace, the code action is *only* inserted in parsing, but not in a lookahead. This, by the way, cannot be specified in legacy JavaCC, so this feature actually is to fix that flaw. BUT... in the above construct, you see, it is getting parsed as:

     {jjtThis.kind = t.kind;}# <== code block and the # means it applies in lookahed
     BinaryExpression(2) <== nonterminal with the single integer argument 2.

And that, of course, is not your intent. There are two fairly simple solutions. You could rewrite the production with an extra parentheses as in:

   void ConditionalOrExpression() :
    { Token t=null; }
    {
      ConditionalAndExpression()
      ( ( (t = <BOOL_OR> | t = <BOOL_ORX> )
        ConditionalAndExpression()
        { jjtThis.kind = t.kind; }) #BinaryExpression(2) )*
    }
       
Then there is no problem. The other solution would be to move the `#BinaryExpression(2)` up a line, so you'd have:

   void ConditionalOrExpression() :
    { Token t=null; }
    {
      ConditionalAndExpression()
      ( ( t = <BOOL_OR> | t = <BOOL_ORX> )
        ConditionalAndExpression() #BinaryExpression(2) 
        { jjtThis.kind = t.kind; } )*
    }

Probably the second solution is a bit better. And really, it might be better (due to this glitch) to disallow a tree-building annotation after a code action -- because really, there is no reason (AFAICS) that anybody needs to put a tree-building annotation right after a code action anyway. Well, actually, on second thought, it could be necessary IF you are manipulating the node stack in the code action. That is possible, but probably unusual. But, in any case, in that situation, you could use solution 1, which is to add the extra parentheses.

You'll hit some other issues migrating, that I am perfectly happy to comment on, but I'll close this message here. I don't think it's a good idea to overload people!

**Comment by nickl-** [comment]
> The biggest single problem that you will run into is here: 

This actually came from the original java grammar, I think BeanShell started with the javacc example java grammar, was before my time so I am guessing. Anyway, these (standard JAVA grammar) are not going to be ported, and is expected to come from the javacc21 grammar. However, there are several customization to the standard grammar like support for array slices (from python) for example, which does.

**Comment by vlsi** [comment]
@nickl- , I have contacted Jonathan previously, and I even contributed to JavaCC21: https://github.com/javacc21/javacc21/pull/15 (it even included publishing to Maven Central!)
The PR was merged, however, later Jonathan went off rails when [I asked to clarify the license](https://github.com/javacc21/javacc21/pull/16), so all the contributions were reverted, and I stopped communication with javacc21.

Unfortunately, Jonathan's behaviour is toxic: https://github.com/javacc/javacc/discussions/227#discussioncomment-3099167. So I would suggest you study the links before proceeding with javacc21.

Jonathan contacted me this October; unfortunately, the case is still the same.

**Comment by revusky** [comment]
> I believe the support is now JAVA 19, correct me if I am wrong, updated since this documentation was written.

I think the only unsupported Java constructs are still preview features -- I think in particular switch-case with pattern matching, which is obviously on my mental TODO list.

Just looking through the `bsh.jjt` you really should be able to put it on a very major diet! Now, generally speaking, you can just put:

      INCLUDE JAVA

towards the top of your grammar and it just *includes* the entire Java grammar that is actually in the javacc-full.jar file. It could be possible that an intermediate step is just to do:

      INCLUDE JAVA_LEXER

and try to get rid of all the lexical specification first.

Here is another big problem that you can (and will) run into in migration. The `token.kind` field is gone. There is now a type-safe enum in its place and also access is encapsulated. Well, generally, variables are properly encapsulated in the generated code in JavaCC 21. So, for example, there is no direct access to the `image` field. So, just taking an example, consider: https://github.com/beanshell/beanshell/blob/master/src/main/jjtree/bsh.jjt#L584

You have the line:

      jjtThis.name = name.image;

What you need this to be now is:

     jttThis.setName(name.getImage());

Both the `name` and the `image` are encapsulated in a getter/setter pattern, right.

You get/set for `image` is already there, but what you need for name at this point is:

     INJECT BSHClassDeclaration :
     {
          @Property String name;
     }

And then the generated node subclass will have:

            private String name;
          
            public String getName() {return name;}
 
            public void setName(String name) {this.name = name;}

*injected* into it. And this is going to be the general pattern that you'll need to use to resolve this sort of issue. 

BTW, I would suggest (though obviously you can do what you want in this instance) that you drop this "BSH" prefix stuff. Just put the generated nodes in their own package and things should be fine. This kind of "poor man's namespace" stuff with these kludgy looking prefixes is...  But again, that's just an aesthetic thing really. And besides, the prefix stuff is really just supported for backward compatibility. But it's your call...

**Comment by nickl-** [comment]
> I have contacted Jonathan previously
@vlsi Not sure what you want from me here? As far as politics are concerned you are going to get no response from me, sorry. 

Lets focus on the work, there is a lot that needs to get done and not enough time and resources, so any help is appreciated. Thank you and welcome!!

**Comment by nickl-** [comment]
> Just looking through the bsh.jjt you really should be able to put it on a very major diet! Now, generally speaking, you can just put: `INCLUDE JAVA` towards the top of your grammar and it just includes the entire Java grammar that is actually in the javacc-full.jar file.

Ahh good, so it will be possible to "overwrite" or change the things from the included grammar? Maybe that's wishful thinking...

**Comment by nickl-** [comment]
> BTW, I would suggest (though obviously you can do what you want in this instance) that you drop this "BSH" prefix stuff. Just put the generated nodes in their own package and things should be fine. This kind of "poor man's namespace" stuff with these kludgy looking prefixes is... But again, that's just an aesthetic thing really. And besides, the prefix stuff is really just supported for backward compatibility. But it's your call...

Yes I read the comment on the documentation, it is not so much a namespace as a naming convention for `Nodes`. It allows us to use package scope accessors while still distinguishing between nodes and custom code, which we won't get from using separate packages. I'm leaving this to a legacy inherited which I can live with. The alternative is an even bigger major change with no real benefit.

**Comment by nickl-** [comment]
> Both the name and the image are encapsulated in a getter/setter pattern, right.

Currently they are just local fields and not generated by javacc, needs to be coded in the node or it causes parser errors. If I am not mistaken.

I am happy with properties and especially if it gets generated, the custom code will generally work the same.

**Comment by revusky** [comment]
> Ahh good, so it will be possible to "overwrite" or change the things from the included grammar? Maybe that's wishful thinking...

No, that's not wishful thinking at all! You can use `INCLUDE JAVA` and redefine things on an as-needed basis underneath. What is also particularly useful is that you can *inject* code into Node classes. In fact, you can see that being used internally, for example: https://github.com/javacc21/javacc21/blob/master/src/javacc/JavaCC.javacc#L302

There, you see that the JavaCC grammar which *includes* the Java grammar, *injects* some useful little convenience methods into the `CompilationUnit` node (that's the top-level node representing a Java source file.)

**Comment by nickl-** [comment]
> No, that's not wishful thinking at all!

Wow, so I can have my cake and eat it too! This answers the question on how we can accept updates to the standard java grammar. Awesome!!

> What is also particularly useful is that you can inject code into Node classes.

So you would prefer all custom code to be in the grammar? This will allow changes to generated nodes to be superfluous if we don't keep any modified Nodes in repo but work only with generated nodes. We could also move the more complex customization to external classes to minimize the amount of injected code, also saves us from having to develop in grammar all the time which could get frustrating. hmmmm some food for thought...

**Comment by revusky** [comment]
> > What is also particularly useful is that you can inject code into Node classes.
> 
> So you would prefer all custom code to be in the grammar? 

Well, actually, not exactly. It's a more nuanced question than that really. Certainly, for very trivial convenience methods, it is *extremely* useful to be able to inject those methods into the `XXXNode.java`. So, for example, if you have:

       Foo : Bar Baz ;

and you think there should be a couple of setters, well, you can just have right after that:

       INJECT Foo : 
       {
             Bar getBar() {return firstChildOfType(Bar.class);}
             Baz getBaz() {return firstChildOfType(Baz.class);}
       }

A very big (IMHO) advantage of this is the ability to define things close to where they are used and relevant. In the above, you define the grammar rule, and then right next to it, you define your two accessor methods. And the whole thing gets regenerated in a clean build, right?

But it is also true that, on occasion, you want to *inject* so much code into an `XXXNode.java` that you would prefer to maintain the file separately -- the main practical reason being that you don't have any tooling editing JavaCC21 grammars, so once the code gets a bit too involved...

But again, you can have your cake and eat it too actually. So, consider this point in the JavaCC grammar: https://github.com/javacc21/javacc21/blob/master/src/javacc/JavaCC.javacc#1122

The `BNFProduction` class is actually maintained separately as regular Java code. The system "knows" this because the class name is fully specified with the package. So you can see it here: https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/core/BNFProduction.java

But, you see, it's a nuanced question. For a Node type that only requires you to inject a field or three and some getter/setter type stuff, it is, on balance, much better to simply define that with an `INJECT` in the grammar because of the advantages of things being defined close to where they are used etcetera. However, once you are defining a lot of behavior in there, eventually, the advantage tilts towards checking it in as a regular Java source file, because then you have the benefits of tooling when you edit the code, which is not a big deal when you're only writing get/set stuff. In particular, the ability to just use the @Property pseudo-annotation can be very useful.

> This will allow changes to generated nodes to be superfluous if we don't keep any modified Nodes in repo but work only with generated nodes.

For fairly trivial code injections, that's where the advantage would lie.

> We could also move the more complex customization to external classes to minimize the amount of injected code, also saves us from having to develop in grammar all the time which could get frustrating.

Yes, if you find yourself injecting a lot of moderately complex stuff into the Node, you'd probably want to take it to a separate .java file that is checked in. In fact, if you look at this package: https://github.com/javacc21/javacc21/tree/master/src/java/com/javacc/core there, you see some of these things that are Nodes in the tree, like `ExpansionSequence` and `ExpansionChoice` were actually at an earlier point defined just within the grammar, but I made the judgment that, on balance, it was better to break them out.

But, you see, this is a much richer, more flexible system than there ever was in the old JJTree.

**Comment by nickl-** [comment]
This is going to be a major change so we might as well do some redesign to get as much gain as possible from the effort.

Goals:

-  Allow easy updates from upstream without breaking BeanShell
- Limit need for grammar changes to new features and bug fixes
- Limit amount of custom code required on the nodes themselves
- Ideally use only generated nodes and have none in the repo

This will already resolve the concern raised before of duplicate files generated which we have custom revisions of in code.

Any other requests or suggestions?

**Comment by nickl-** [comment]
> The `BNFProduction` class is actually maintained separately as regular Java code. The system "knows" this because the class name is fully specified with the package.

If I follow correctly

```java
public class BNFProduction extends BaseNode {
    private Expansion expansion, recoveryExpansion;
    private String lexicalState, name, leadingComments = "";
    private boolean implicitReturnType;
```

Here `BNFProduction` extends `BaseNode` but it could also extend a specific definition like `BlockStatement` or am I confusing things? Perhaps it would be used instead of BlockStatement rather since we are specifying the class for that definition. 

I was thinking an easy way to handle custom code is to create subclasses of the generated code which overwrites and implements the parent methods called by the parser. But how do we get the parser to instantiate the subclass? Am I making sense?...

**Comment by nickl-** [comment]
> you see some of these things that are Nodes in the tree, like `ExpansionSequence` and `ExpansionChoice` were actually at an earlier point defined just within the grammar

I think this is what I am referring to, `ExpansionChoice` extends `Expansion` which in turn extends `BaseNode` but this would require the Parser to instantiate an `ExpansionChoice` when needed, am I correct?

**Comment by revusky** [comment]
> Here `BNFProduction` extends `BaseNode` but it could also extend a specific definition like `BlockStatement` or am I confusing things?

Sure, it could extend some other Node subclass that, in turn, is either generated or not.

>I think this is what I am referring to, ExpansionChoice extends Expansion which in turn extends BaseNode but this would require the Parser to instantiate an ExpansionChoice when needed, am I correct?

Yes, and that's what is specified here: https://github.com/javacc21/javacc21/blob/master/src/javacc/JavaCC.javacc#1444 

So, the fact that the classname is fully specified with the package means that it doesn't generate the class. It's there in the source tree. But, there is the contract that the class does implement the base Node API. But it can do that by subclassing `BaseNode` or some other class that, in turn, subclasses `BaseNode`. 

Also, a generated Node subtype can be specified as subclassing some other Node subtype that is, in turn either generated or not. So, for example here: https://github.com/javacc21/javacc21/blob/master/src/javacc/JavaCC.javacc#1484

The generated `ExpansionWithParentheses` node type is specified to subclass `com.javacc.core.Expansion`, which is maintained separately.

Or you see that an entire intuitive type hierarchy is defined *in the Java grammar* for the various nodes: https://github.com/javacc21/javacc21/blob/master/examples/java/Java.javacc#L522-L577

Well, all this stuff is largely unchanged (some minor enhancements) from a couple of years ago. When I implemented this stuff I wrote a run-down of it here: https://javacc.com/2021/01/12/just-like-home-made/



Of course, if you don't

**Comment by revusky** [comment]
> I don't believe we need to use a visitor which makes having the code generated redundant, I might be wrong.

There shouldn't be any need to generate any base Visitor sort of code. The `Node.Visitor` class can be used. Actually, you can look at various uses internally. It is used internally in the following places:

https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/output/congo/SyntaxConverter.java
https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/core/nfa/NfaBuilder.java
https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/core/SanityChecker.java#L58-L82
https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/output/java/JavaFormatter.java
https://github.com/javacc21/javacc21/blob/master/src/java/com/javacc/output/java/DeadCodeEliminator.java

So, for example, the syntax converter that [I wrote recently](https://discuss.congocc.org/d/21-ann-syntax-converter-available) is in fact a `Node.Visitor`. 

I can't resist pointing out something about this. Over the past few years, people have got on my case over the lack of much explicit testing in the project. My general approach to testing any new feature is that I try, as soon as possible, to use the feature in internal development. And the result of this is that if some basic thing gets broken, it becomes impossible to even do a full rebuild (I mean rebootstrapping the build jar) because the functionality is used internally.

**Comment by nickl-** [comment]
Replaced by #685
