### ISSUE TITLE
Memory leak due to lots of java.lang.Class accumulated in multi-threaded environment

### ISSUE THREAD

**Issue by ghYura** [beanshell/beanshell#598]
Is there any solution to avoid Memory leak due to lots of java.lang.Class accumulated in multi-threaded environment inspite of each thread has its own new Interpreter() but parsing java-source classes constantly being fed-up by application?

**Comment by nickl-** [comment]
Can you please elaborate? Sample code to reproduce would be awesome.

**Comment by nickl-** [comment]
The new `Interpreter.reset` may help or just calling `getClassManager().reset();` should help to release the classes loaded.

https://github.com/beanshell/beanshell/blob/3d65498d5d9c6968364313b9f978418aef9698d1/src/main/java/bsh/Interpreter.java#L760-L768

Can't do much more with this issue unfortunately, reopen if there is more information.
