### ISSUE TITLE
Simple jmeter Single http request &  beanshell script generating hmac authentication.

### ISSUE THREAD

**Issue by clintFortinbras** [beanshell/beanshell#600]
Hi All,
I am looking to increase our jmeter test throughput for the following scenario

a simple http request with beanshell script generating hmac authentication.

How can i speed up the authentication computaion ?

One thought that comes to mind is Pre-compute HMACS (300K ) and store them in the app.

Then when i go to run the 7K of threads, simply pull the authentication from a list.

Can any one help with suggestions around this ?

**Comment by nickl-** [comment]
@clintFortinbras did you manage to resolve this?

**Comment by nickl-** [comment]
Closed: assume resolved
