### ISSUE TITLE
 sourced file 'sourceFileInfo' incorrectly formatted as a URL

### ISSUE THREAD

**Issue by opeongo** [beanshell/beanshell#611]
Commit 96de3d9fcade8007f80495f9cbe321ac02150ca2 refactored the `Interpreter.source(String filename)` method so that it converted the filename to a URL, and stored this result in the `sourceFileInfo` field.  Although the `source()` command still works, this breaks using the `sourceRelative()` command because the tolls cannot construct an absolute path name from a relative path and a URL.

As an example, the following is broken:
---- file test.bsh ---
```java
sourceRelative("test2.bsh");
```
--- end of file  ---

Then within the interpreter:
```java
source("test1.bsh");
```

Regardless of the absence of `test2.bsh` this command will blow up because the interpreter can no longer resolve the relative reference.

**Comment by nickl-** [comment]
#612 is RTBC

**Closed: Resolved in PR**
