### ISSUE TITLE
Parser Error in Comment Token

### ISSUE THREAD

**Issue by morris821028** [beanshell/beanshell#62]
Hi all,

There is a simple case for unicode decoding.  I think the unicode behavior is good in string literal, but not all the scope to get a token.

```java
System.out.println("\u51ea");
// \uzzzzzz
```

The main problem happened in the method `readChar()` of `JavaCharStream.java`.  How to change this parser? I also open issue in https://github.com/pejobo/beanshell2/issues/112

**Comment by morris821028** [comment]
BTW, the number of release version in this repository is small than pejobo/beanshell2. It is confused for me.

**Comment by nickl-** [comment]
@morris821028 yes this project has had many trials and tribulations, a group with @pejobo forked the project and bumped the version to 2 in an attempt to distinguish the two projects. 

We have done extensive work to [merge-fork-beanshell2](https://github.com/beanshell/beanshell/tree/merge-fork-beanshell2) and release v2.1 but fell short [19 commits](https://github.com/pejobo/beanshell2/commits/v2.1) shy of completion.

Ideally we need to complete the merge before adding new features, so close but still so far. It would really help if you could checkout the  [merge-fork-beanshell2](https://github.com/beanshell/beanshell/tree/merge-fork-beanshell2) branch, kick the tyres and see... will you let me know what you find, please.

I hope this leaves you less confused, but feel free to ask should you have more questions.

**Comment by nickl-** [comment]
This works upstream...

Also made some enhancements to string usage in general, come and see.
