### ISSUE TITLE
New team member: Opeongo

### ISSUE THREAD

**Issue by nickl-** [beanshell/beanshell#622]
Pending acceptance of the invitation of course, it will be my pleasure to welcome @opeongo to the Beanshell core development team.

Over the last few months you have been keeping the Beanshell flame alive, kudos for that! While opensource project team members get overwhelmed by "real life", it always falls on the community to step up and pick up the slack. For tenacity alone you should be rewarded, but granting commit access is more motivated towards making the best utilization of your availability and involvement presence to give free reign for your efforts not to be hindered by lack of support staff.

Had a quick look over the submitted PRs and although not able to test now the code looks professional with no immediate alarms going off which lends you my confidence that the project as a whole will benefit from your expertise. You can consider them all ready to be committed and should you accept please help yourself by merging as your first task.

Will attempt to rebuild a dev environment and allocate some time over the holidays where we might be able to catch up and address some outstanding issues and new strategies.

Welcome to the team!

**Comment by opeongo** [comment]
Thanks Nick.  I am looking forward to helping contribute.  BeanShell has some very attractive characteristics as a lightweight scripting language for Java, and it is nice to have a community for it.

**Comment by opeongo** [comment]
@nickl- By the way, welcome back after being away for a while.  You are the powerhouse in this project and and I am looking forward to helping move things along.

**Comment by nickl-** [comment]
Welcome, welcome, so glad you accepted the invite! The project is blessed by your presence.

Yes yes not really back back yet but in the same sense didn't go anywhere either =) sometimes life just happens.

Thank you for the welcomes...
