### ISSUE TITLE
Project travis build fails.

### ISSUE THREAD

**Issue by nickl-** [beanshell/beanshell#625]
Need assist from someone with travis know how to debug and resolve please.

**Comment by Sailsman63** [comment]
Which issue?

- If it's the fact that the Travis build hasn't run since July, Travis has migrated to a Github-apps type integration. To get it running again:
    - An *organization owner* needs to sign up on travis-ci.com and authorize the travis app (it can use your github id for SSO - no need for an extra password)
    - Said owner will also need to select a plan and give travis billing information (PPI, including a physical address), even if you select the free "Trial" plan. (Open source projects never count against paid credits, so it won't actually *cost*, but still)
    - If the above seems out of line, perhaps time to migrate the auto-builds to Github Actions? I might be willing to take that on, with the proviso that my OSS contribution time is limited, so no guarantees on timeframe.
- If you are trying to troubleshoot the error that stopped the auto-build *before* Travis did their site migration, it's actually a Maven error in `org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0` due to a missing method. I think it's related to [this Maven bug report.](https://issues.apache.org/jira/browse/MCHECKSTYLE-384). The fix seems to be to do some version updating, but I haven't experimented yet.
    - **Question:** Is the Maven build actually maintained, or is the ant file preferred?

**Comment by opeongo** [comment]
>       * **Question:** Is the Maven build actually maintained, or is the ant file preferred?
I am using maven, and it appears from the commit history that this is the system that has been getting updates.

**Comment by opeongo** [comment]
Maybe it is time to review the build configuration and make a plan about what to change.  Lots of change has happened over the past few years and there may be better tooling that we can use.

Currently the project has web hooks for 
- https://scrutinizer-ci.com
- https://codecov.io
- https://notify.travis-ci.org
- https://snyk.io

Is this suite still appropriate?  Is there anything new that we should be using in addition?

As you suggest Github Actions is available and could be used to set up a workflow to run a maven build with each push or pull request.  Would this be an equivalent replacement for the travis webhook?  I think we should be testing under several jdk's (jdk8 and the latest).

Also I see that Github offers access to code security scanning tools with just a few clicks (under the Security tab, Code scanning alerts).  Are any of these worth setting up?

Anything else worth changing?

**Comment by opeongo** [comment]
I added an action for a maven build and disabled the travis webhook and now I can successfully merge PR's.

@Sailsman63 if you have experience in this area could you review my changes and let me know what you think?

**Comment by Sailsman63** [comment]
I don't really have a lot of experience here. I'd be mostly working from the documentation to construct even a basic Actions definition. What you've put together is pretty much where I would have started: It builds and runs the test suite, which is sort of the baseline for what is needed.

- It wouldn't be too hard to add a JDK version matrix to get compile and test coverage on several JDKs. (8, 11 & 17?)
- Keep in mind that existing PRs will not benefit from this workflow unless the contributor re-bases them.

I don't really have an opinion on the current webhooks vs. the Github built-ins. Note, however:

- If resurrecting the Travis build itself is not going to happen, the [https://notify.travis-ci.org] hook and the badging integration on the `README.md` should be removed, as well as `.travis.yml`.
- Both the [https://codecov.io] and coverity integrations seem to be broken (Last scans were from last year and 2018 respectively)

**Comment by opeongo** [comment]
Thanks for the help on this.  
I added a matrix strategy for the lts jdk's [8, 11, 17] and that is working.
I deleted the travis webhook and changed the status badge to the maven github action.

I am not sure what to do about codecov and coverity.  Any suggestions on what is wrong here and how to fix? Codecov seem useful to get going again.

**Comment by Sailsman63** [comment]
I've never actually worked with either. A few years ago, github changed how 3rd-party service integration worked, and many OSS projects never transitioned.

From just a very quick overview of their respective websites:

- Codecov has a marketplace app -free for open source projects- : https://github.com/marketplace/codecov/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4xNg==#pricing-and-setup This is something that a project owner should be able to set up in a few minutes.
- Coverity Scan, on the other hand, requires that you explicitly do a custom build for upload, using a closed-source tool that they provide. (Or move back to travis-ci to automate it.)

**Comment by opeongo** [comment]
After a bit of fiddling codecov is working and it's providing useful info.  

Snyk, coverity and scrutinzer had been set up, but I cannot seem to get them fully working.  I think my access to get snyk integrated is limited because someone else no longer participating in the project is the owner of this integrated.   Coverity seems to have a more demanding setup that I'm not interested in.  scrutinizer sort of works but meh.

I added sonatype lift, it installed easily and it has useful defect analysis.  It doesn't provide a status badge (nice to have feature) but otherwise it's looking pretty good.  

I am thinking of deleting all references to snyk, coverity and scrutinizer and just going with lift.  I don't see the point in having more than one of these tools.  Thoughts?

**Comment by Sailsman63** [comment]
Synk seems to be running again. It appears mostly to be a database of CVEs, and alerts you if your dependencies have a known flaw. (The recent Log4J 2 kerfluffle would have raised an alert, I think)

Lift appears (again, have not used it) to mostly target specific PRs, so I wouldn't expect badging to make sense.

Honestly, I've never done *any* work with these sort of tools, so I don't really have a useful opinion.

**Comment by nickl-** [comment]
> I am thinking of deleting all references to snyk, coverity and scrutinizer and just going with lift. I don't see the point in having more than one of these tools. Thoughts?

Agreed, coverity and scrutinizer was PT to get working originally and I can't imagine they have gotten any easier.

Well done getting codecov working!! You're a superStar!

**Comment by nickl-** [comment]
Very nice codecov reports =D #637

**Comment by nickl-** [comment]
I see here is something else we missed: #626 Flacocobot

**Comment by nickl-** [comment]
I see we are using [Java CI with Maven](https://github.com/beanshell/beanshell/blob/master/.github/workflows/maven.yml) now instead of travis.
