### ISSUE TITLE
Error in file META-INF/services/javax.script.ScriptEngineFactory

### ISSUE THREAD

**Issue by maroph** [beanshell/beanshell#628]
The file META-INF/services/javax.script.ScriptEngineFactory in bsh-2.1.0.jar still contains the class name 

bsh.engine.BshScriptEngineFactory

but the class is refactored to

bsh.BshScriptEngine

**Comment by nickl-** [comment]
I am not quite following, perhaps I'm being thick so my apologies in advance if I am missing something.

The factory produces script engines, they are not of the same so cannot replace one another. You can certainly instantiate script engines without the factory but that doesn't make it redundant.

Both classes are in the `bsh.engine` package so there is no problem here either.

What am I missing?

We unfortunately can't support 2.1.0 anymore the code base has evolved too much, please build your own jar files.

**Comment by maroph** [comment]
Okay, have already done so
