### ISSUE TITLE
How to Build the Source Code?

### ISSUE THREAD

**Issue by morris821028** [beanshell/beanshell#63]
I try to change the `src/main/jjtree/bsh.jjt`, so the `src/main/javacc/bsh.jj` will be generated by jjtree, and the `src/main/java/bsh/Parser*.java` also generated by javac. I run the command in the README.

```
mvn clean install -DskipTests
```

That seems nothing changed.  I can use the `build.xml` to compile the source code in [pejobo/beanshell2](https://github.com/pejobo/beanshell2), but here not.  Can someone help me?

**Comment by nickl-** [comment]
Again I need to point you to the merge branch:  [merge-fork-beanshell2](https://github.com/beanshell/beanshell/tree/merge-fork-beanshell2)

This is configured in the maven build and generates the parser automagically, just like you expect. The master branch does not. There are already many enhancements made to the compiler on the merge branch...

**Comment by nickl-** [comment]
I have made it the default branch, that should make things more intuitive. The only reason it's not merged with master yet is cause were not quite finished with the fork merge yet... 19 commits still outstanding. Once they are complete the plan is to release ver 2.

**Comment by morris821028** [comment]
Thanks for your effort. :)

**Comment by morris821028** [comment]
So, the `beanshell/src/main/javacc/bsh.jj` can be removed(never see it changed), right?

We only need `beanshell/src/main/jjtree/bsh.jjt`. The parser code will be generated in the folder `target/generated-sources/javacc/bsh/Parser*.java` after executing `mvn clean install -DskipTests`. 

I don't know how to work with maven pom.xml. If they just generate in the target folder, it means that the IDE(for example, Eclipse) could not access these source code. Could it modify to copy the newest version into src folder, and then add the auto-generated file into .gitignore?

Thanks

**Comment by morris821028** [comment]
They still need to add into eclipse. Otherwise, IDE displays a lot of error information.

1. Import ... > Maven > Existing Maven Projects
2. Add target folder: Use as Source Folder.

<img width="437" alt="step1" src="https://user-images.githubusercontent.com/4697855/39615932-605a2b80-4fab-11e8-8bbc-69357f85c6df.png">
<img width="469" alt="step2" src="https://user-images.githubusercontent.com/4697855/39615938-6277e3f8-4fab-11e8-91cf-5a62fb35da9a.png">

**Comment by nickl-** [comment]
No don't add target folder as source... that creates a loop and doesn't work.

Instead follow these instructions for [Showing or hiding files in the Project Explorer view](https://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-48b.htm)

**Comment by nickl-** [comment]
Closed: Answered

If you still have problems please raise a new issue.
