### ISSUE TITLE
Possibility of ArrayIndexOutOfBoundsException in BSHIfStatement

### ISSUE THREAD

**Issue by max-m-s** [beanshell/beanshell#639]

**Comment by max-m-s** [comment]
The following script code will cause an ArrayIndexOutOfBoundsException within BSHIfStatement, as it only contains one element in children:

```
int i = 0;
if (i == 0);
  i++;
```

Though the ';' on the If is obviously a mistake, this syntax is accepted in Java. The code following the if statement is executed unconditionally.

**Comment by nickl-** [comment]
Reported at #342 will deal with it as one issue

Closed: duplicate
