### ISSUE TITLE
Disable beanshell commands and syntax

### ISSUE THREAD

**Issue by Rotstein1** [beanshell/beanshell#642]
Is there a way to disable the extra Beanshell commands and the additional syntax, like "loosely typed" variables? My application is some sort of a java learning app, so I only want "plain" java code to be executed.
Thanks.

**Comment by Sailsman63** [comment]
You're probably looking for [strict mode] (http://beanshell.org/manual/strictjava.html#Strict_Java_Mode).

**Comment by Rotstein1** [comment]
Thanks.

**Comment by nickl-** [comment]
@Sailsman63 thank you!
