### ISSUE TITLE
Memory leak in BSHBlock.cache

### ISSUE THREAD

**Issue by wech71** [beanshell/beanshell#643]
Memory leak in BSHBlock.cache in try blocks because BSHBlock.evalBlock with overrideNamespace=false creates a new BlockNamespace on blockspaces

Hi There,

after several weeks hunting down a massive memory leak in our application I found the origin of the problem in the bsh-3 code base from github master branch.

The list of blockspaces grows bigger and bigger each time I call eval on script containing try/catch statement, because the corresponding namespace is never removed again when BSHBlock.evalBlock is called with overrideNamespace=false from BSHTryStatement.

The code flow is:

BSHTryStatement.java:86 calls the eval overload, without the overrideNamespace parameter, effectively setting it to false.

    ret = tryBlock.eval(callstack, interpreter);

which leads to  BSHBlock.evalBlock having overrideNamespace = false which then leads to adding a new BlockNamespace being added to blockspaces 

    Object evalBlock(
        CallStack callstack, Interpreter interpreter,
        boolean overrideNamespace, NodeFilter nodeFilter )
        throws EvalError
    {
        Object ret = Primitive.VOID;
        NameSpace enclosingNameSpace = null;
        if ( !overrideNamespace )
            enclosingNameSpace = callstack.swap(
                    blockspaces.get(callstack.top()));

Later this Namespace  is never being removed from blockspaces.

This namespace then leads to the bsh-function parameters (100 kbyte arrays) to be held in memory forever and accumulate over time.

Here is a sample to reproduce the problem:

```java
String scriptText1 =  
				"public byte[] test(byte[] in) throws Exception\n"
				+ "{ \n"
				+ "   try \n"
				+ "	  {\n"
				+ "			byte[] a = new byte[10*1000000]; \n"
				+ "			return a;\n"
				+ "   	} \n"
				+ "	  	catch (Exception e)\n"
				+ "		{\n"
				+ "		}\n"
				+ "} \n"
				+ "\n"
				+ "/*S*/ return test((byte[])param0);";

byte[] in = new byte[100*1000000];
		for (int i=0; i < 100; i++)
		{
		
			Interpreter interpreter = new Interpreter();
			try
			{
				interpreter.set("param0", in);
				byte[] result = (byte[])interpreter.eval(scriptText1);
			}
			catch(Exception e)
			{
				System.out.print(e.toString());
			}
		}
```

The problem only occurs with a try/cath block.

I've managed to fix the problem locally, and wich still successfully runs all tests, and would happily provide a patch.

Thanks for maintining this cool project!

**Comment by wech71** [comment]
https://github.com/beanshell/beanshell/pull/644

**Comment by nickl-** [comment]
Won't setting `overrideNameSpace` to true also resolve the issue?

**Comment by wech71** [comment]
> Won't setting `overrideNameSpace` to true also resolve the issue?

This was my first attempt, but unfortunately this breaks several tests which expect the block to contain block-local variables as far as I understood the check.

Unfortunately I experienced some more memory leaks and the only solution I could find was brute-force removing of the offending block namespace. 

See:
  https://github.com/wech71/beanshell/commit/3f8370c1a188d1575a15916b94e9a60cf5408717
and
  https://github.com/wech71/beanshell/commit/a79907264f82f34a203110cb142e752f13483ec1

With the additional changes my code now runs several month without OutOfMemory problems, while before it did happen every 1-2 days on busy instances.

As my analysis of the problem was several weeks ago, so I don't remember everything exactly, so I might be wrong on the following:

Maybe my understanding of what mechanism should remove the namespace objects is not complete, but to me it does not work like intended, as the namespace objects pile up over time. If I remember right, the Namespace instances are being used as keys in "blockspaces". Maybe making the key a WeakReference<Namespace> would solve the problem too.

**Comment by nickl-** [comment]
Will make some time to look into this.

**Comment by opeongo** [comment]
There is a significant memory leak of BlockNameSpace objects in the ReferenceCache.  [Have a look here](https://github.com/beanshell/beanshell/commit/32e8be51001be388743dac45376a699c9549c41a#r91461392)  for a simple fix for this.

**Comment by opeongo** [comment]
I have been noticing some problems lately and I suspect the my problems are related to this namespace issue.  Check out #655

**Comment by nickl-** [comment]
> There is a significant memory leak of BlockNameSpace objects in the ReferenceCache. [Have a look here](https://github.com/beanshell/beanshell/commit/32e8be51001be388743dac45376a699c9549c41a#r91461392) for a simple fix for this.

Hmmm that is weird, we are specifically using `CacheReference` so that we don't need to do this.

**Comment by opeongo** [comment]
Oops, I misstated the problem.  I should have said that there is a significant leak of Reference objects in the ReferenceCache.  The BlockNameSpace object are being cleared by the GC when there are no hard or soft references from any active threads, this is true.  But the Reference objects that are in the cache object remain.  In a long running program you can have hundreds of thousands of these building up and they will never be released automatically:  there needs to be an explicit action taken in the ReferenceQueueMonitor to remove them from the cache.

**Comment by nickl-** [comment]
parent #661

**Comment by nickl-** [comment]
GC clears them just fine, works with 5MB or 150MB of heap (eg. using -Xmx150M)

```java
    @Test
    public void memory_leak_test() {
        int size = 1024*1024;
        int count = 151;
        MemoryUsage mu = ManagementFactory.getMemoryMXBean().getHeapMemoryUsage();
        assumeThat("Assumes available memory less than 151MB", mu.getInit(), lessThan((long)size * count));
        String scriptText1 = TestUtil.script(
				"public byte[] test(byte[] in) throws Exception {",
				"    try {",
				"        byte[] a = new byte[in.length];",
				"        return a;",
				"    } catch (Exception e) { }",
				"}",
				"",
				"return test((byte[])param0);");

        byte[] in = new byte[size];
        for (int i=0; i < count && BlockNameSpace.cacheSize() >= i; i++) {
            Interpreter interpreter = new Interpreter();
            try {
                interpreter.set("param0", in);
                byte[] result = (byte[])interpreter.eval(scriptText1);
                assertArrayEquals(in, result);
                System.gc();
            } catch(Exception e) { /* ignore */ }
        }
        assertThat("Block name space cache size less than "+count, BlockNameSpace.cacheSize(), lessThan(count));
    }
```

Needs cacheSize exposed on BlockNameSpace:

```java
    /** For debugging get the size of the cache */
    static int cacheSize() {
        return blockspaces.size();
    }
```

You can keep the test going for more than 150MB of heap space if you want the result will be the same. Once we run out of memory GC will clear the references before an OutOfMemoryError occurs, as is intended.

Don't see the point in adding this test, there are several reference cache tests that prove the same.

Closed: works as expected
