### ISSUE TITLE
Restrict access to specific classes and any keyword that we mention(custom defined keyword)

### ISSUE THREAD

**Issue by KameshwarB** [beanshell/beanshell#645]
Hello !!!
in my project i want to restrict certain imports and keywords not to be use by script, therefore when it sees it terminates and throw exception.
Let's say we have class imports from **java.sql. or spring.jpa. or spring.jdbc. or any code defined keywords** we want to restrict beanshell from executing the script and throw exception.

is it possibile?

**Comment by nickl-** [comment]
Interesting. How would we implement this with standard java security policy? ...it should work as expected.

**Comment by nickl-** [comment]
Also see #35

**Comment by nickl-** [comment]
Closed - lack of further discussion assumes security policy resolved the issue
