### ISSUE TITLE
FYI: Java 9+ Beanshell internal API use

### ISSUE THREAD

**Issue by norrisgc** [beanshell/beanshell#65]
I'm working on making a Java program work with Java 9+. I've removed a bunch of uses of internal APIs which cause problems with Java 9+. The program also uses a number of other packages, one of which is Beanshell, currently 2.0b6. This Beanshell version also uses an internal Java API:

>jdeps -verbose -jdkinternals bsh.jar
bsh.jar -> C:\Program Files\JAVA\jdk1.8.0_172\jre\lib\rt.jar
   bsh.util.AWTConsole (bsh.jar)
      -> java.awt.peer.ComponentPeer                        JDK internal API (rt.jar)
      -> java.awt.peer.TextComponentPeer                    JDK internal API (rt.jar)

Warning: JDK internal APIs are unsupported and private to JDK implementation that are
subject to be removed or changed incompatibly and could break your application.
Please modify your code to eliminate dependency on any JDK internal APIs.
For the most recent update on JDK internal API replacements, please check:
https://wiki.openjdk.java.net/display/JDK8/Java+Dependency+Analysis+Tool

JDK Internal API                         Suggested Replacement
----------------                         ---------------------
java.awt.peer.ComponentPeer              Should not use. See https://bugs.openjdk.java.net/browse/JDK-8037739
java.awt.peer.TextComponentPeer          Should not use. See https://bugs.openjdk.java.net/browse/JDK-8037739

Edit: Can't spell "bean"!

**Comment by nickl-** [comment]
Yes we are aware of these and many more security related issues, currently support JDK8 only.

Ty for the mention.

**Comment by nickl-** [comment]
Complete: see beanshell/beanshell@b977eee running with ` --illegal-access=deny` Java 9 and/or 10
