### ISSUE TITLE
How to download snapshot releases

### ISSUE THREAD

**Issue by peterkronenberg** [beanshell/beanshell#650]
The doc says to use Snapshot releases based on the main branch.  I don't see those on Maven Central?  How can I download the snapshot releases?

**Comment by nickl-** [comment]
Clone the repository and build a SNAPSHOT release yourself.

**Comment by nickl-** [comment]
The BeanShell 3.0 SNAPSHOT release should now be available under:

groupId: org.beanshell
artifactId: bsh

nJoy!

**Comment by nickl-** [comment]
Closed: resolved
