### ISSUE TITLE
Goal: organize backlog by 12/12

### ISSUE THREAD

**Issue by nickl-** [beanshell/beanshell#665]
Over the last week, with the help of @jimjag, we have managed to reduce the total backlog by 25% and reorganized many more.

I want this completed by weeks end.

Strategy: Run through the [outstanding issues](https://github.com/beanshell/beanshell/issues?q=is%3Aopen+label%3A%22auto-migrated+sourceforge%22+-label%3Achecked) (currently 68) migrated from sourceforge, and organize.

Close the issue if one of the following conditions apply:
I added a label  for those without permissions to close open issues, please give the reason for closing from the list below in a comment and add the label <kbd>can close</kbd>, then a team member can follow up.

* works in BeanShell 3.0, resolved
* cannot reproduce
* not enough information given
* duplicate of another existing issue
* stale, not an issue in 2022

If an issue is deemed necessary for further consideration, please elaborate in comment and add your findings. To help us categorize the issues better one or more of the following labels may apply.

* <kbd>GUI</kbd> pertains to swing or awt from the gui application or applets
* <kbd>documentation</kbd> pertains to wrong or missing documentation
* <kbd>parsing</kbd> problem with grammar, there are parser errors
* <kbd>patch</kbd> provides a change to the BeanShell source code
* <kbd>feature</kbd> due to a java feature not implemented yet, or feature request
* <kbd>out of scope v3</kbd> not considered for next release like strict java support

Finally please add the label <kbd>checked</kbd> to indicate that the issue has been reviewed, comments added, labels applied, and it can be filtered off the list of [outstanding issues](https://github.com/beanshell/beanshell/issues?q=is%3Aopen+label%3A%22auto-migrated+sourceforge%22+-label%3Achecked). Which if empty means our goal is done!

Thank you in advance for your assistance.

**Comment by nickl-** [comment]
Admittedly, a slightly [more restricted list of outstanding issues](https://github.com/beanshell/beanshell/issues?q=is%3Aopen+label%3A%22auto-migrated+sourceforge%22+-label%3Achecked+-label%3Apatch+-label%3AGUI+-label%3ADocumentation+-label%3A%22out+of+scope+v3.0%22) also excluding all patches, documentation, GUI, and out of scope for v3.0 issues, is all finished and done, one day before the deadline. [chuffed]

Who said it cannot be done?

Of the [original list](https://github.com/beanshell/beanshell/issues?q=is%3Aopen+label%3A%22auto-migrated+sourceforge%22+-label%3Achecked) of 68 issues only 19 remain.

**Comment by nickl-** [comment]
Only 10 [more to go](https://github.com/beanshell/beanshell/issues?q=is%3Aopen+label%3A%22auto-migrated+sourceforge%22+-label%3Achecked)...

**Comment by nickl-** [comment]
All issues have been processed round 1, thank you for all the assist.

Next we'll have to do bug triage and see what we've got.

Closed: list is complete

**Comment by opeongo** [comment]
Congraulations, well done.  Sorry that I could not have been of more assistance on this
