### ISSUE TITLE
Some question about process

### ISSUE THREAD

**Issue by revusky** [beanshell/beanshell#695]
Hi all. 

As you might have noticed, I created a branch called `congo` for the work on migrating to JavaCC 21. The branch is called congo instead of javacc21 because there is an imminent rebranding to the name CongoCC in the works. See [here](https://discuss.congocc.org/d/1-whence-the-congo-naming). I know that is from nearly a year ago, but it's really going to happen now. (I swear...)

But... let's see... for example, [here](https://github.com/beanshell/beanshell/blob/master/src/main/java/bsh/SimpleNode.java#L60) we have `protected int id` and the first thing that occurred to me (aside from why in a language like Java, where you have runtime type information, you even need something like this, since an object "knows" its type without any `type` or `id` field) is why the variable needs `protected` visibility. So, naturally, what I did was to see what would happen if I changed this to `private int id`. Well, the answer in this case is *absolutely nothing*. There is no need for `id` to be visible outside the class. Everything compiles and works as before.

So, it would seem that making the variable `private` is just an unambiguous (albeit minor!) improvement. So what I'm wondering about is whether changes of this nature should just be committed to master directly as well. I mean, I created my branch thinking I would work exclusively on the branch, but a change like this is so uncontroversial that...

Well, anyway, that's just an example. There seem to be various fields that have protected and package access that really should be private. Should I just commit that kind of change to master or hold off? Again, I wouldn't commit anything that potentially has any real effect.

**Comment by nickl-** [comment]
Yes there are issues with the Nodes, if we are talking about nodes specifically, especially with regards to the scope of fields, which should arguably all be properties. What is benefit to commit these changes to master now, when we are planning on merging the branch anyway? Are we still going to have the nodes committed to source?

Anyway if you want to make improvements any help is appreciated.  We have extensive commit validation running continuous integration against several (3) different java versions to ensure it compiles, runs, and that all tests pass. Additionally there are checks for code smells, ensure code coverage does not decline, and code style remains consistent. These sometimes raise issues that can be disregarded but ideally we want all commits to be green. 

The unofficial process is to create a branch and [submit a PR](https://github.com/beanshell/beanshell/pulls?q=is%3Apr+is%3Aclosed) to verify that all the checks pass. Even though there is no protection on master we should avoid doing force commits on master. By using this process we can do force commits and rebases on the PR branch until the checks pass and then when all is green and happy we can do a clean merge unto master.

**Comment by nickl-** [comment]
Closed: asked and answered
