### ISSUE TITLE
Motivations for jUnit and obstacles to adopt assertj.

### ISSUE THREAD

**Issue by nickl-** [beanshell/beanshell#73]
In another thread @stefanofornari posted:
> hi nick,
>
> do you have any issues using fluent assertions provided by assertj (
http://joel-costigliola.github.io/assertj/) ?
>
> Ste

I had a closer look at assertj... looks interesting but there are some problems that will prevents adoption.

 * assertThat is in name conflict with the junit assert
 * assertj relies on lambda expressions, not something currently supported in beanshell. This may seem trivial but the alternative, having interfaces implemented, is rather cumbersome.

We already use junit and the script tests are runnable via a junit test suite, which may be junit 3 but I am not convinced there is enough reason to look for a replacement. jUnit integrates seamlessly with surefire on maven and we have existing tests in jUnit so do we need an alternative?

If an alternative strategy (unit testing framework) has sufficient benefits over jUnit, are we still able to run existing unit tests?

**Comment by stefanofornari** [comment]
Hi Nick,

maybe we have been thinking at different approaches,

assertj does not necessarily replace JUnit, it sits at the end on top of
it. It does not actually rely on lambda expressions, you can be happy
without them (I am not sure it can be declared in public, but I hate
lambdas and I will never use them... :) ). Also, what I like the most is
not assertThat, but then(). You can write your assertions fluently like:

import ...

public class ThisIsNicelyFluent {

@Before
public void somethingBefore() {}

@Test
public void somethingFluent() {
    PleaseDoSomething do = new ...

    then(do.extecute()).IsNotNull().contains("hello world");
    then(do.sayBye()).isEqualTo("Bye bye");
    then(do.list()).isNotEmpty();
}

HTH

Ste

**Comment by nickl-** [comment]
@stefanofornari I understood that you meant to only include assertj support. The argument however can apply to finding a replacement for junit as well.

In anyway, besides the name conflict `assertThat` all assertj adds is another DSL for accomplishing what junit asserts already does. I would rather motivate towards jUnit5 compatibility which if I am not mistaken is closer to assertj than jUnit4.

Why add another dependency to maintain if the current solution is adequate. Sure assertj has merits but is it worth the extra effort required to maintain another dependency?

**Comment by stefanofornari** [comment]
ok @nickl-, thanks for the feedback.

Ste
