### ISSUE TITLE
What qualifies as a scripted object?

### ISSUE THREAD

**Issue by opeongo** [beanshell/beanshell#733]
Scripted objects are method declarations that return a reference to a namespace.  Typically they are coded as:
```java
apple(String variety, int grade) {
    type = "apple";
    return this;
}
```

But what about method declaration that return a namespace reference indirectly.  Do these also count as scripted objects?
```java
apple(String variety, int grade) {
    type = "apple";
    return this;
}

apple(String variety) {
    return apple(variety, -1);
}

apple(String variety, String letterGrade) {
    if ("A".equalsIgnoreCase(letterGrade))
        return apple(variety, 1);
    else if ("B".equalsIgnoreCase(letterGrade))
        return apple(variety, 2);
    else
        return apple(variety, -1);
}
```

Do we need to adjust [the code that detects if a method is a scripted object](https://github.com/beanshell/beanshell/blob/47cbe833b7709fe0c5b6c67ee51b731746a7bfe5/src/main/java/bsh/BSHMethodDeclaration.java#L79) to detect all of these other cases?

**Comment by nickl-** [comment]
I would say no. 

The first method apple1 is a scripted object, apple2 and apple3 only returns the object apple1, which doesn't give them object scope within themselves in return.

Interesting problem, forced me to think for a minute.

Closed: works as expected
