### ISSUE TITLE
The bsh.Console not working for Mac 

### ISSUE THREAD

**Issue by klcolon** [beanshell/beanshell#735]
I am trying to run the beanshell console on my Mac and came across this error. The interpreter seems to work fine but I just can't render the GUI. Below is the following error message. 

$ java bsh.Console

Couldn't start desktop: Sourced file: inline evaluation of: ``desktop();'' : Method Invocation bcm.getClassPath : at Line: 40 : in file: /bsh/commands/makeWorkspace.bsh : bcm .getClassPath ( ) 

Called from method: desktop : at Line: 1 : in file: inline evaluation of: ``desktop();'' : desktop ( ) 
Target exception: java.lang.NullPointerException

Looking at line 40, this is what I see.

this.bcm = this.caller.namespace.getClassManager();
		if ( bcm != null ) {
			classNamesSource = bcm.getClassPath();
			nct.add( classNamesSource );
		}
Thank you for your support.

**Comment by nickl-** [comment]
You are testing against master right, or using the [BeanShell 3.0 SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/beanshell/bsh/3.0.0-SNAPSHOT/) release?

This error looks familiar and is something that was fixed recently.
