### ISSUE TITLE
Download link for bsh.jar in readme.md does not work 

### ISSUE THREAD

**Issue by TianYuanSX** [beanshell/beanshell#745]
Hi, thanks for your useful tool.

I just found that the download link for bsh.jar in the readme.md doesn't work.

https://bintray.com/artifact/download/beanshell/Beanshell/org/apache-extras/beanshell/bsh/2.0b6/bsh-2.0b6.jar

Maybe you can replace it with a correct one.

**Comment by nickl-** [comment]
duplicate #744
