### ISSUE TITLE
[Question] Beanshell compatibility with gradle

### ISSUE THREAD

**Issue by Alexenon** [beanshell/beanshell#749]
Hello everyone,
I am wondering, It is possible to use beanshell not just with maven, but with gradle too ?

Will this work on my gradle project ?
```
dependencies {
    implementation 'org.beanshell:bsh:2.0b6'
}
```

**Comment by James-Pannell** [comment]
``` kotlin
// https://mvnrepository.com/artifact/org.apache-extras.beanshell/bsh
implementation("org.apache-extras.beanshell:bsh:2.0b6")
```

If you are starting a new project, you might want to consider creating a Gradle task to clone the master branch and then build the project to generate a 3.0 artifact.

**Comment by nickl-** [comment]
This is the correct "implementation" for the [BeanShell 3.0 SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/beanshell/bsh/3.0.0-SNAPSHOT/) release.

groupId: org.beanshell
artifactId: bsh

I'm guessing that translates to:

``` kotlin
// https://oss.sonatype.org/content/repositories/snapshots/org/beanshell/bsh/3.0.0-SNAPSHOT/
implementation("org.beanshell:bsh:3.0.0-SNAPSHOT")
```

But not using gradle myself so please confirm.

**Comment by friuns2** [comment]
org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.beanshell:bsh:3.0.0-SNAPSHOT.

**Comment by nickl-** [comment]
*Closed* no response from owner assumed resolved.
