### ISSUE TITLE
support varargs simple function

### ISSUE THREAD

**Issue by geovanny1781** [beanshell/beanshell#761]
Support varargs?, I try this simple function:
interpreter.eval("int sumTwoNum(int... numeros) { return 1;}");
and error:
bsh.ParseException: Parse error at line 1, column 18. Encountered: int

**Comment by nickl-** [comment]
Seems to work for me, please ensure that you are using BeanShell 3.0.0-SNAPSHOT

```java
BeanShell 3.0.0-SNAPSHOT.5569
bsh % int sumTwoNum(int... numeros) { return 1;}
--> void
bsh % sumTwoNum(1,2,3,4);
--> $0 = 1I :int
```

**Closed** cannot reproduce.
