### ISSUE TITLE
How to create arrays from "scripted objects"

### ISSUE THREAD

**Issue by Raffa064** [beanshell/beanshell#763]
If i do something like:

`
FakeClass() {
    prop = "Something";
    return this;
}

instance = FakeClass();
`

How can I create an array of this FakeClass?

**Comment by nickl-** [comment]
Your `FakeClass` is not a class but a function, method, or structure. 

I am not sure how we can define arrays of scripted objects because they do not constitute a type.

You cannot for example say:

```java
FakeClass instance = FakeClass();
```
Never thought about this before. Anyone else have any ideas?

**Comment by opeongo** [comment]
funcs = new Object[] { FakeClass(), FakeClass(), FakeClass() };

print( funcs[0].prop );

**Comment by nickl-** [comment]
```java
bsh % FakeClass() {
  prop = "Something";
  return this;
}
--> void
bsh % funcs = new Object[] { FakeClass(), FakeClass(), FakeClass() };
--> $0 = {'this' reference to Bsh object: NameSpace: FakeClass (bsh.NameSpace@44e81672) (method) , 'this' reference to Bsh object: NameSpace: FakeClass (bsh.NameSpace@61baa894) (method) , 'this' reference to Bsh object: NameSpace: FakeClass (bsh.NameSpace@768debd) (method) } :Object[]
bsh % print( funcs[0].prop );
Something
--> void
```

**Comment by nickl-** [comment]
Thank you @opeongo 

**Closed: asked and answered**
