### ISSUE TITLE
Try/catch block not working for exceptions thrown in nested methods

### ISSUE THREAD

**Issue by lukas-lang** [beanshell/beanshell#78]
Consider the following example:

```java
void bar() { throw new IllegalArgumentException(); }

class foobar {
    void foo() { bar(); }
}

class foobar2 {
    void foo() { new foobar().foo(); }
}

try { bar(); }
catch (IllegalArgumentException ex) {}

try { new foobar().foo(); }
catch (IllegalArgumentException ex) {}

try { new foobar2().foo(); }
catch (IllegalArgumentException ex) {}
```

For me, the third example fails to catch the exception. It seems as if the try/catch block only unwraps a single `TargetException` layer, while there may be multiple layers in some cases (such as the last one). I have also encountered the issue with intermixed `UndeclaredThrowableException` layers in more complex cases.

Clearly, this makes catching specific types of exceptions very tedious.

**Comment by nickl-** [comment]
@lukas-lang They say great minds think alike =) 

Also came across the `UndeclaredThrowableException` issue with `TargetException` and I believe the commit at beanshell/beanshell@3de12d8 should resolve this. 

if you would kindly confirm... much joy.

**Comment by nickl-** [comment]
That snippet would look stunning wrapped in a [test script](https://github.com/beanshell/beanshell/blob/merge-fork-beanshell2/src/test/resources/TestTemplate.bsh)

nudge...nudge...wink

**Comment by nickl-** [comment]
My Bad these issues are not related.

Can reproduce.

**Comment by nickl-** [comment]
Closed: Fixed
