### ISSUE TITLE
New BeanShell release

### ISSUE THREAD

**Issue by nickl-** [beanshell/beanshell#81]
Created on behalf of @pgiffuni

Start considering a new release (2.0?).

Which next major release version number would you prefer?

[![](https://api.gh-polls.com/poll/01CHGF0S2MPRRZV3546T759VAR/BeanShell%203)](https://api.gh-polls.com/poll/01CHGF0S2MPRRZV3546T759VAR/BeanShell%203/vote)
[![](https://api.gh-polls.com/poll/01CHGF0S2MPRRZV3546T759VAR/BeanShell%208)](https://api.gh-polls.com/poll/01CHGF0S2MPRRZV3546T759VAR/BeanShell%208/vote)

See next post for details.

**Comment by nickl-** [comment]
I see two questions to this issue:

### 1. What is the next release version number?

There has been a lot of confusion in the BeanShell community since the beanshell2 fork which can be mitigated by a major release version number greater than 2 as a clear indicator of which version has preference. While contemplating this I thought of two options:

**BeanShell 3**

The most logical next increment of major release version numbers greater than beanshell 2.

**BeanShell 8**

As you may be aware the minimum JAVA requirement for the new release will be JDK 1.8.  Perhaps the major version number can also be an indicator of the minimum Java requirement. 

Hope I have polls correctly configured then perhaps we can put it up for a vote.

Which next major release version number would you prefer?

/polls "BeanShell 3" "BeanShell 8"

### 2. When can we release?

It has been several years since the last release so it would be safe to say there is no big urgency for the next release. A lot of effort has gone into this release so I would like it to be as stable as possible before opening the flood gates again. One way to ensure a stable release is through wide adoption which is not a realistic goal at the moment. Another approach, which is more attainable, would be through good test coverage and ensuring all reported issues have been addressed. 

There is a [road map](/beanshell/beanshell#development-road-map) maintained in the readme as a change log as well as checklist of things that need done before we can release. Please let us know your thoughts on this.

**Comment by stain** [comment]
@nickl- are you willing to be Release Manager..? Are we keeping the groupId of `org.apache-extras.beanshell`

Let me know if you need your account added for https://repository.sonatype.org/ to be associated with that groupId -- see https://central.sonatype.org/pages/ossrh-guide.html

**Comment by nickl-** [comment]
@stain Not sure if I want the official title but it is probably best if we spread the permissions around.

I added jira account nickl on sonatype, is there anything else you require?

**Comment by stain** [comment]
Sorry for the delay!

I dont think we should have any official titles, but it would be a role to wear for a particular release, agree it should be spread around so we can change hats.

Raised with Sonatype as [OSSRH-41303](https://issues.sonatype.org/browse/OSSRH-41303) to give you access for org.apache-extras.beanshell 

Note that I dont have the org/beanshell groupId in Sonatype so to get ownership of that I think we need some of the original folks involved?

**Comment by stain** [comment]
Release should be just mvn release:prepare and mvn release:perform and then log in to https://repository.sonatype.org/ to promote the staged repository.  (famous last words!)

**Comment by nickl-** [comment]
@stain Awesomeness, I will revisit this closer to release time and confirm. Only scanned the docs briefly thus far which at least allows for a nod and a "Thank you very much for your efforts". =)

**Comment by wilx** [comment]
> There is a road map maintained in the readme as a change log as well as checklist of things that need done before we can release. Please let us know your thoughts on this.

Don't try to be perfectionists. As long as you do not regress, release often.

**Comment by nickl-** [comment]
Not striving for perfection,and I agree with you 100% it will be the norm to release often.

just want to catch up on the back log (12 years worth) before we open the flood gates again

Any assistance you can give would me very much appreciated!

**Comment by pgiffuni** [comment]
I just pulled out 2-0b4-legacy: I didn't want it to make it very visible as it was only the very old release from the website so I could move the artifacts away.
Unfortunately it appears on the top of the release page and In order for it to not be tagged "Latest Release" I added a pre-release tag. Once a release is rolled out, there appears to be no way to remove it.

Can we make a real pre-release now? I would certianly prefer that on the top.

**Comment by nickl-** [comment]
@pgiffuni  Not ready for release yet see [road map](/beanshell/beanshell#development-road-map)

**Comment by drosenbauer** [comment]
My view is mainly promotional. The release is a decade coming, the library is viewed as old and stodgy, and there needs to be a fanfare.

- If syntax will be feature-compatible with JDK8 (especially lambdas), go with Beanshell8.
- If not, go with Beanshell**7** and jump to Beanshell8 when syntax is JDK8-compatible.

That will produce _two_ fanfares, one "wow Beanshell actually got an update!" and one "wow Beanshell can do lambdas!"

**Comment by nickl-** [comment]
@drosenbauer you raise a very interesting conundrum, if BeanShell8 only means minimum required JDK version 8 then users might expect this to also mean feature complete JDK 8.

This motivates in favour of going with BeanShell3 instead.

**Comment by nickl-** [comment]
BeanShell3 it is, thank you for your participation.

**Comment by netbeansuser2019** [comment]
Sorry to say, but I think that it should be no more waiting for release as common picture to me and I guess even to others if there is missing a release for long time that project is dead.

Especially as there are broken links on "readme page" and mentioned "next release will be a production ready major version" so that sounds like that there is no such release and such library is just for fan.

I would like to suggest to be released as soon as and then setup a cycle as e.g. Oracle with Java.

Additionally I think that same as other person herein that major version could be a highest version of Java of that syntax is supported, but as seems it has been decided already.

Frankly speaking there is even no roadmap even it is called as that, but it is not a roadmap to me as there is no "when/frequency a year".
