### ISSUE TITLE
Simpler Bean syntax

### ISSUE THREAD

**Issue by sourceforge-issue-exporter** [beanshell/beanshell#94]
Creating a JavaBean and setting several properties can
get very wordy in BeanShell.  

For example in BeanShell...

SomeBean bean = new SomeBean\(\);
bean.prop1 = value1;
bean.prop2 = value2;
bean.prop3 = value3;
bean.prop4 = value4;
bean\{ "prop5" \} = value5;

This syntax is ugly.  Please find a way to reduce.

Examples:

SomeBean bean = new SomeBean\( 
prop1=value1;
prop2=value2;
prop3=value3;
prop4=value4;
prop5=value5 \);

Syntax like this is much more readable, and easy to use
when scripting.

Reported by: *anonymous

Original Ticket: "beanshell/feature-requests/5":https://sourceforge.net/p/beanshell/feature-requests/5

**Comment by nickl-** [comment]
We have the map expressions, they should suffice.

```java
map = new Map { "a"=1, "b"=2, "c"=3 };
map = new { "a"=1, "b"=2, "c"=3 };
map = { "a"=1, "b"=2, "c"=3 };
--> { "a"=1, "b"=2, "c"=3 } :Map
```

Lets test with:

```java
public class TestClass {
    private static int statProp;
    private int instProp;
    private boolean instBoolProp;

    public int getInstProp() { return instProp; }
    public void setInstProp(int instProp) { this.instProp = instProp; }
    public boolean isInstBoolProp() { return instBoolProp; }
    public void setInstBoolProp(boolean instBoolProp) { this.instBoolProp = instBoolProp; }
    public static int getStatProp() { return statProp; }
    public static void setStatProp(int var) { statProp = var; }
}

bsh % new TestClass { "TestClass"=2, "instBoolProp"=true, "instProp"=23 }
```

**Comment by nickl-** [comment]
In fact it might just work as anonymous class:

```java
bsh % new TestClass() { statProp=2; instBoolProp=true; instProp=23; }
--> $3 = global$anon1@48140564 :global$anon1
bsh % $3.isInstBoolProp();
--> $4 = true :boolean
bsh % $3.getInstProp();
--> $5 = 23I :int
bsh % $3.statProp;
--> $6 = 2I :int
```

So do we actually need something else...wondering

**Comment by nickl-** [comment]
Map expressions don't include the `( )` so perhaps that should be with beans too:

```java
bsh % new TestClass { "TestClass"=2, "instBoolProp"=true, "instProp"=23 }

// Error: Target Exception: Error in array initializer: Cannot cast Entry to TestClass : at Line: 16 : in file: <unknown file> : {
Caused by: java.lang.ClassCastException: Cannot cast Entry to TestClass
```

**Comment by nickl-** [comment]
There are now 2 supported bean syntax sugar:

Anonymous class:
```java
bean = new TestClass() { statProp=2; instBoolProp=true; instProp=23; };
```

And bean initializer expression:
```java
bean = new TestClass { statProp=2, instBoolProp=true, instProp=23 };
```
